return {
	main=
	{
		[1]=
		{
			id = 1,
			name = "龙虾兑换",
			start_time = 1592263800,
			end_time = 1592841599,
			use_goods = {"prop_zongzi",},
			goods_type = 1,
			email_id = 1,
			award_id = 1,
			enable = 0,
		},
		[2]=
		{
			id = 2,
			name = "香粽换好礼",
			start_time = 1592868600,
			end_time = 1593446399,
			use_goods = {"prop_zongzi_1",},
			goods_type = 1,
			email_id = 2,
			award_id = 2,
			enable = 0,
		},
		[3]=
		{
			id = 3,
			name = "龙虾兑换",
			start_time = 1597707000,
			end_time = 1598284799,
			use_goods = {"prop_fish_drop_act_0",},
			goods_type = 1,
			email_id = 3,
			award_id = 3,
			enable = 0,
		},
		[4]=
		{
			id = 4,
			name = "五星换好礼",
			start_time = 1601335800,
			end_time = 1601913599,
			use_goods = {"prop_031_aster",},
			goods_type = 1,
			email_id = 4,
			award_id = 4,
			enable = 0,
		},
		[5]=
		{
			id = 5,
			name = "火鸡换好礼",
			start_time = 1606176000,
			end_time = 1606751999,
			use_goods = {"prop_gej_hj",},
			goods_type = 1,
			email_id = 5,
			award_id = 5,
			enable = 0,
		},
		[6]=
		{
			id = 6,
			name = "火鸡换好礼-cjj",
			start_time = 1606176000,
			end_time = 1606751999,
			use_goods = {"prop_gej_hj",},
			goods_type = 1,
			email_id = 6,
			award_id = 6,
			enable = 0,
		},
		[7]=
		{
			id = 7,
			name = "双十二换好礼",
			start_time = 1607385600,
			end_time = 1607961599,
			use_goods = {"prop_12_12_lh",},
			goods_type = 1,
			email_id = 7,
			award_id = 7,
			enable = 0,
		},
		[8]=
		{
			id = 8,
			name = "双十二换好礼-cjj",
			start_time = 1607385600,
			end_time = 1607961599,
			use_goods = {"prop_12_12_lh",},
			goods_type = 1,
			email_id = 8,
			award_id = 8,
			enable = 0,
		},
		[9]=
		{
			id = 9,
			name = "冬至换好礼",
			start_time = 1607990400,
			end_time = 1608566399,
			use_goods = {"prop_dz_jz",},
			goods_type = 1,
			email_id = 9,
			award_id = 9,
			enable = 1,
		},
		[10]=
		{
			id = 10,
			name = "冬至换好礼-cjj",
			start_time = 1607990400,
			end_time = 1608566399,
			use_goods = {"prop_dz_jz",},
			goods_type = 1,
			email_id = 10,
			award_id = 10,
			enable = 1,
		},
		[11]=
		{
			id = 11,
			name = "圣诞福利",
			start_time = 1609200000,
			end_time = 1609775999,
			use_goods = {"prop_yd_jyb",},
			goods_type = 1,
			email_id = 11,
			award_id = 11,
			enable = 1,
		},
		[12]=
		{
			id = 12,
			name = "圣诞福利-cjj",
			start_time = 1609200000,
			end_time = 1609775999,
			use_goods = {"prop_yd_jyb",},
			goods_type = 1,
			email_id = 12,
			award_id = 12,
			enable = 1,
		},
		[13]=
		{
			id = 13,
			name = "元旦好礼",
			start_time = 1609200000,
			end_time = 1609775999,
			use_goods = {"prop_yd_jyb",},
			goods_type = 1,
			email_id = 13,
			award_id = 13,
			enable = 1,
		},
		[14]=
		{
			id = 14,
			name = "元旦好礼-cjj",
			start_time = 1609200000,
			end_time = 1609775999,
			use_goods = {"prop_yd_jyb",},
			goods_type = 1,
			email_id = 14,
			award_id = 14,
			enable = 1,
		},
		[15]=
		{
			id = 15,
			name = "欢乐庆典",
			start_time = 1609804800,
			end_time = 1610380799,
			use_goods = {"prop_hlqd_xx",},
			goods_type = 1,
			email_id = 15,
			award_id = 15,
			enable = 1,
		},
		[16]=
		{
			id = 16,
			name = "欢乐庆典-cjj",
			start_time = 1609804800,
			end_time = 1610380799,
			use_goods = {"prop_hlqd_xx",},
			goods_type = 1,
			email_id = 16,
			award_id = 16,
			enable = 1,
		},
		[17]=
		{
			id = 17,
			name = "兑换奖励",
			start_time = 1610409600,
			end_time = 1610985599,
			use_goods = {"prop_fish_drop_act_0",},
			goods_type = 1,
			email_id = 17,
			award_id = 17,
			enable = 1,
		},
		[18]=
		{
			id = 18,
			name = "兑换奖励-cjj",
			start_time = 1610409600,
			end_time = 1610985599,
			use_goods = {"prop_fish_drop_act_0",},
			goods_type = 1,
			email_id = 18,
			award_id = 18,
			enable = 1,
		},
		[19]=
		{
			id = 19,
			name = "狂欢庆典",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fish_drop_act_0",},
			goods_type = 1,
			email_id = 19,
			award_id = 19,
			enable = 1,
		},
		[20]=
		{
			id = 20,
			name = "狂欢庆典-cjj",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fish_drop_act_0",},
			goods_type = 1,
			email_id = 20,
			award_id = 20,
			enable = 1,
		},
		[21]=
		{
			id = 21,
			name = "发财礼包--免费--恭喜",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi",},
			goods_type = 1,
			award_id = 21,
			enable = 1,
		},
		[22]=
		{
			id = 22,
			name = "发财礼包--免费--发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 22,
			enable = 1,
		},
		[23]=
		{
			id = 23,
			name = "发财礼包--免费--恭喜发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 23,
			enable = 1,
		},
		[24]=
		{
			id = 24,
			name = "发财礼包--V1V7--恭喜",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi",},
			goods_type = 1,
			award_id = 24,
			enable = 1,
		},
		[25]=
		{
			id = 25,
			name = "发财礼包--V1V7--发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 25,
			enable = 1,
		},
		[26]=
		{
			id = 26,
			name = "发财礼包--V1V7--恭喜发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 26,
			enable = 1,
		},
		[27]=
		{
			id = 27,
			name = "发财礼包--V8V12--恭喜",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi",},
			goods_type = 1,
			award_id = 27,
			enable = 1,
		},
		[28]=
		{
			id = 28,
			name = "发财礼包--V8V12--发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 28,
			enable = 1,
		},
		[29]=
		{
			id = 29,
			name = "发财礼包--V8V12--恭喜发财",
			start_time = 1611014400,
			end_time = 1611590399,
			use_goods = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai",},
			goods_type = 1,
			award_id = 29,
			enable = 1,
		},
	},
	email=
	{
		[1]=
		{
			id = 1,
			title = "小龙虾狂欢",
			content = "恭喜您在龙虾兑换活动中获得了%s，请在活动结束后7个工作日内联系%s领取奖励，否则视为自动放弃！",
		},
		[2]=
		{
			id = 2,
			title = "粽情端午",
			content = "恭喜您在香粽换好礼活动中获得了%s，请在活动结束后7个工作日内联系%s领取奖励，否则视为自动放弃！",
		},
		[3]=
		{
			id = 3,
			title = "龙虾啤酒节",
			content = "恭喜您在龙虾兑换活动中获得了%s，请在活动结束后7个工作日内请关注公众号《畅游新世界》联系%s领取奖励，否则视为自动放弃！",
		},
		[4]=
		{
			id = 4,
			title = "国庆狂欢",
			content = "恭喜您在五星换好礼活动中获得了%s，请在活动结束后7个工作日内联系公众号《畅游新世界》客服领取，逾期视为自动放弃！",
		},
		[5]=
		{
			id = 5,
			title = "火鸡换好礼",
			content = "恭喜您在火鸡换好礼活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[6]=
		{
			id = 6,
			title = "火鸡换好礼",
			content = "恭喜您在火鸡换好礼活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[7]=
		{
			id = 7,
			title = "双十二狂欢节",
			content = "恭喜您在双十二换狂欢节活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[8]=
		{
			id = 8,
			title = "双十二狂欢节",
			content = "恭喜您在双十二换狂欢节活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[9]=
		{
			id = 9,
			title = "欢乐冬至",
			content = "恭喜您在欢乐冬至活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[10]=
		{
			id = 10,
			title = "欢乐冬至",
			content = "恭喜您在欢乐冬至活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[11]=
		{
			id = 11,
			title = "圣诞福利",
			content = "恭喜您在圣诞福利活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[12]=
		{
			id = 12,
			title = "圣诞福利",
			content = "恭喜您在圣诞福利活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[13]=
		{
			id = 13,
			title = "元旦好礼",
			content = "恭喜您在元旦好礼活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[14]=
		{
			id = 14,
			title = "元旦好礼",
			content = "恭喜您在元旦好礼活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[15]=
		{
			id = 15,
			title = "欢乐庆典",
			content = "恭喜您在欢乐庆典活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[16]=
		{
			id = 16,
			title = "欢乐庆典",
			content = "恭喜您在欢乐庆典活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[17]=
		{
			id = 17,
			title = "兑换奖励",
			content = "恭喜您在欢乐庆典活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[18]=
		{
			id = 18,
			title = "兑换奖励",
			content = "恭喜您在欢乐庆典活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
		[19]=
		{
			id = 19,
			title = "狂欢庆典",
			content = "恭喜您在狂欢盛典活动中获得了%s，请在活动结束后7个工作日内联系公众号《鲸鱼初纪元》客服领取，逾期视为自动放弃！",
		},
		[20]=
		{
			id = 20,
			title = "狂欢庆典",
			content = "恭喜您在狂欢盛典活动中获得了%s，请在活动结束后7个工作日内联系公众号《彩云新世界》客服领取，逾期视为自动放弃！",
		},
	},
	award=
	{
		[1]=
		{
			no = 1,
			award_cfg_id = 1,
			award_id = 1,
			permission_key = "actp_own_task_longxiaduihuan",
			award_name = "麻辣龙虾尾",
			use_num = {18000,},
			me_limit_day_num = 1,
		},
		[2]=
		{
			no = 2,
			award_cfg_id = 1,
			award_id = 2,
			permission_key = "actp_own_task_longxiaduihuan",
			award_name = "麻辣小龙虾",
			use_num = {12000,},
			me_limit_day_num = 1,
		},
		[3]=
		{
			no = 3,
			award_cfg_id = 1,
			award_id = 3,
			permission_key = "actp_own_task_longxiaduihuan",
			award_name = "香辣龙虾尾",
			use_num = {6000,},
			me_limit_day_num = 1,
		},
		[4]=
		{
			no = 4,
			award_cfg_id = 1,
			award_id = 4,
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {12000,},
		},
		[5]=
		{
			no = 5,
			award_cfg_id = 1,
			award_id = 5,
			asset_type = {"jing_bi",},
			asset_count = {500000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[6]=
		{
			no = 6,
			award_cfg_id = 1,
			award_id = 6,
			asset_type = {"jing_bi",},
			asset_count = {200000,},
			use_num = {2300,},
			me_limit_day_num = 1,
		},
		[7]=
		{
			no = 7,
			award_cfg_id = 1,
			award_id = 7,
			asset_type = {"prop_web_chip_huafei",},
			asset_count = {1000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[8]=
		{
			no = 8,
			award_cfg_id = 2,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_zongzi_convert",
			asset_type = {"jing_bi",},
			asset_count = {5000,},
			use_num = {10,},
			me_limit_day_num = 1,
		},
		[9]=
		{
			no = 9,
			award_cfg_id = 2,
			award_id = 2,
			permission_key = "actp_buy_gift_bag_class_zongzi_convert",
			award_name = "艾草中药香包",
			use_num = {888,},
			me_limit_day_num = 1,
		},
		[10]=
		{
			no = 10,
			award_cfg_id = 3,
			award_id = 1,
			asset_type = {"prop_web_chip_huafei",},
			asset_count = {1000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[11]=
		{
			no = 11,
			award_cfg_id = 3,
			award_id = 2,
			permission_key = "lxdh_025_notnew",
			award_name = "麻辣龙虾尾4罐",
			use_num = {13500,},
			me_limit_day_num = 1,
		},
		[12]=
		{
			no = 12,
			award_cfg_id = 3,
			award_id = 3,
			permission_key = "lxdh_025_notnew",
			award_name = "十三香龙虾3.6斤",
			use_num = {9000,},
			me_limit_day_num = 1,
		},
		[13]=
		{
			no = 13,
			award_cfg_id = 3,
			award_id = 4,
			permission_key = "lxdh_025_notnew",
			award_name = "雪花啤酒12罐",
			use_num = {3500,},
			me_limit_day_num = 1,
		},
		[14]=
		{
			no = 14,
			award_cfg_id = 3,
			award_id = 5,
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[15]=
		{
			no = 15,
			award_cfg_id = 3,
			award_id = 6,
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[16]=
		{
			no = 16,
			award_cfg_id = 3,
			award_id = 7,
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2300,},
			me_limit_day_num = 1,
		},
		[17]=
		{
			no = 17,
			award_cfg_id = 4,
			award_id = 1,
			permission_key = "actp_gqkl_031_aster_exchange",
			award_name = "双肩背包",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[18]=
		{
			no = 18,
			award_cfg_id = 4,
			award_id = 2,
			permission_key = "actp_gqkl_031_aster_exchange",
			award_name = "U型颈枕",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[19]=
		{
			no = 19,
			award_cfg_id = 4,
			award_id = 3,
			permission_key = "actp_gqkl_031_aster_exchange",
			award_name = "早餐饼干",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[20]=
		{
			no = 20,
			award_cfg_id = 4,
			award_id = 4,
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[21]=
		{
			no = 21,
			award_cfg_id = 4,
			award_id = 5,
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[22]=
		{
			no = 22,
			award_cfg_id = 4,
			award_id = 6,
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[23]=
		{
			no = 23,
			award_cfg_id = 4,
			award_id = 7,
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[24]=
		{
			no = 24,
			award_cfg_id = 4,
			award_id = 8,
			permission_key = "actp_gqkl_031_aster_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[25]=
		{
			no = 25,
			award_cfg_id = 5,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼玉米油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[26]=
		{
			no = 26,
			award_cfg_id = 5,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "仓鼠抱枕",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[27]=
		{
			no = 27,
			award_cfg_id = 5,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[28]=
		{
			no = 28,
			award_cfg_id = 5,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[29]=
		{
			no = 29,
			award_cfg_id = 5,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[30]=
		{
			no = 30,
			award_cfg_id = 5,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[31]=
		{
			no = 31,
			award_cfg_id = 5,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[32]=
		{
			no = 32,
			award_cfg_id = 5,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[33]=
		{
			no = 33,
			award_cfg_id = 6,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼玉米油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[34]=
		{
			no = 34,
			award_cfg_id = 6,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "仓鼠抱枕",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[35]=
		{
			no = 35,
			award_cfg_id = 6,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[36]=
		{
			no = 36,
			award_cfg_id = 6,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[37]=
		{
			no = 37,
			award_cfg_id = 6,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[38]=
		{
			no = 38,
			award_cfg_id = 6,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[39]=
		{
			no = 39,
			award_cfg_id = 6,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[40]=
		{
			no = 40,
			award_cfg_id = 6,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[41]=
		{
			no = 41,
			award_cfg_id = 7,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼玉米油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[42]=
		{
			no = 42,
			award_cfg_id = 7,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "奥克斯煮蛋器",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[43]=
		{
			no = 43,
			award_cfg_id = 7,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "灯影牛肉",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[44]=
		{
			no = 44,
			award_cfg_id = 7,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[45]=
		{
			no = 45,
			award_cfg_id = 7,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[46]=
		{
			no = 46,
			award_cfg_id = 7,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[47]=
		{
			no = 47,
			award_cfg_id = 7,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[48]=
		{
			no = 48,
			award_cfg_id = 7,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[49]=
		{
			no = 49,
			award_cfg_id = 8,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼玉米油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[50]=
		{
			no = 50,
			award_cfg_id = 8,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "奥克斯煮蛋器",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[51]=
		{
			no = 51,
			award_cfg_id = 8,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "灯影牛肉",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[52]=
		{
			no = 52,
			award_cfg_id = 8,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[53]=
		{
			no = 53,
			award_cfg_id = 8,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[54]=
		{
			no = 54,
			award_cfg_id = 8,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[55]=
		{
			no = 55,
			award_cfg_id = 8,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[56]=
		{
			no = 56,
			award_cfg_id = 8,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[57]=
		{
			no = 57,
			award_cfg_id = 9,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "澳洲进口奶粉",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[58]=
		{
			no = 58,
			award_cfg_id = 9,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "泰清香大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[59]=
		{
			no = 59,
			award_cfg_id = 9,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "俄罗斯巧克力",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[60]=
		{
			no = 60,
			award_cfg_id = 9,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[61]=
		{
			no = 61,
			award_cfg_id = 9,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[62]=
		{
			no = 62,
			award_cfg_id = 9,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[63]=
		{
			no = 63,
			award_cfg_id = 9,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[64]=
		{
			no = 64,
			award_cfg_id = 9,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[65]=
		{
			no = 65,
			award_cfg_id = 10,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "澳洲进口奶粉",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[66]=
		{
			no = 66,
			award_cfg_id = 10,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "泰清香大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[67]=
		{
			no = 67,
			award_cfg_id = 10,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "俄罗斯巧克力",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[68]=
		{
			no = 68,
			award_cfg_id = 10,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[69]=
		{
			no = 69,
			award_cfg_id = 10,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[70]=
		{
			no = 70,
			award_cfg_id = 10,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[71]=
		{
			no = 71,
			award_cfg_id = 10,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[72]=
		{
			no = 72,
			award_cfg_id = 10,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[73]=
		{
			no = 73,
			award_cfg_id = 11,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "家用电烤炉",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[74]=
		{
			no = 74,
			award_cfg_id = 11,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "蓝山咖啡",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[75]=
		{
			no = 75,
			award_cfg_id = 11,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼油",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[76]=
		{
			no = 76,
			award_cfg_id = 11,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[77]=
		{
			no = 77,
			award_cfg_id = 11,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[78]=
		{
			no = 78,
			award_cfg_id = 11,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[79]=
		{
			no = 79,
			award_cfg_id = 11,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[80]=
		{
			no = 80,
			award_cfg_id = 11,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[81]=
		{
			no = 81,
			award_cfg_id = 12,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "家用电烤炉",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[82]=
		{
			no = 82,
			award_cfg_id = 12,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "蓝山咖啡",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[83]=
		{
			no = 83,
			award_cfg_id = 12,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼油",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[84]=
		{
			no = 84,
			award_cfg_id = 12,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[85]=
		{
			no = 85,
			award_cfg_id = 12,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[86]=
		{
			no = 86,
			award_cfg_id = 12,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[87]=
		{
			no = 87,
			award_cfg_id = 12,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[88]=
		{
			no = 88,
			award_cfg_id = 12,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[89]=
		{
			no = 89,
			award_cfg_id = 13,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "豪华坚果礼盒",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[90]=
		{
			no = 90,
			award_cfg_id = 13,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[91]=
		{
			no = 91,
			award_cfg_id = 13,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "新年日历",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[92]=
		{
			no = 92,
			award_cfg_id = 13,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[93]=
		{
			no = 93,
			award_cfg_id = 13,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[94]=
		{
			no = 94,
			award_cfg_id = 13,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[95]=
		{
			no = 95,
			award_cfg_id = 13,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[96]=
		{
			no = 96,
			award_cfg_id = 13,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[97]=
		{
			no = 97,
			award_cfg_id = 14,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "豪华坚果礼盒",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[98]=
		{
			no = 98,
			award_cfg_id = 14,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[99]=
		{
			no = 99,
			award_cfg_id = 14,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "新年日历",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[100]=
		{
			no = 100,
			award_cfg_id = 14,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[101]=
		{
			no = 101,
			award_cfg_id = 14,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[102]=
		{
			no = 102,
			award_cfg_id = 14,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {5000000,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[103]=
		{
			no = 103,
			award_cfg_id = 14,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[104]=
		{
			no = 104,
			award_cfg_id = 14,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[105]=
		{
			no = 105,
			award_cfg_id = 15,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "小太阳取暖器",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[106]=
		{
			no = 106,
			award_cfg_id = 15,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "泰清香大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[107]=
		{
			no = 107,
			award_cfg_id = 15,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "纯棉毛巾1条",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[108]=
		{
			no = 108,
			award_cfg_id = 15,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[109]=
		{
			no = 109,
			award_cfg_id = 15,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_3",},
			asset_count = {1,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[110]=
		{
			no = 110,
			award_cfg_id = 15,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_2",},
			asset_count = {1,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[111]=
		{
			no = 111,
			award_cfg_id = 15,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[112]=
		{
			no = 112,
			award_cfg_id = 15,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_1",},
			asset_count = {1,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[113]=
		{
			no = 113,
			award_cfg_id = 16,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "小太阳取暖器",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[114]=
		{
			no = 114,
			award_cfg_id = 16,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "泰清香大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[115]=
		{
			no = 115,
			award_cfg_id = 16,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "纯棉毛巾1条",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[116]=
		{
			no = 116,
			award_cfg_id = 16,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[117]=
		{
			no = 117,
			award_cfg_id = 16,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[118]=
		{
			no = 118,
			award_cfg_id = 16,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_4",},
			asset_count = {5,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[119]=
		{
			no = 119,
			award_cfg_id = 16,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[120]=
		{
			no = 120,
			award_cfg_id = 16,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_3",},
			asset_count = {1,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[121]=
		{
			no = 121,
			award_cfg_id = 17,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[122]=
		{
			no = 122,
			award_cfg_id = 17,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[123]=
		{
			no = 123,
			award_cfg_id = 17,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "椰子汁6瓶",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[124]=
		{
			no = 124,
			award_cfg_id = 17,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[125]=
		{
			no = 125,
			award_cfg_id = 17,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_3",},
			asset_count = {1,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[126]=
		{
			no = 126,
			award_cfg_id = 17,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_2",},
			asset_count = {1,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[127]=
		{
			no = 127,
			award_cfg_id = 17,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[128]=
		{
			no = 128,
			award_cfg_id = 17,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_1",},
			asset_count = {1,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[129]=
		{
			no = 129,
			award_cfg_id = 18,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼油4L",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[130]=
		{
			no = 130,
			award_cfg_id = 18,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "金龙鱼大米",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[131]=
		{
			no = 131,
			award_cfg_id = 18,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "椰子汁6瓶",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[132]=
		{
			no = 132,
			award_cfg_id = 18,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[133]=
		{
			no = 133,
			award_cfg_id = 18,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[134]=
		{
			no = 134,
			award_cfg_id = 18,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_4",},
			asset_count = {5,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[135]=
		{
			no = 135,
			award_cfg_id = 18,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[136]=
		{
			no = 136,
			award_cfg_id = 18,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_3",},
			asset_count = {1,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[137]=
		{
			no = 137,
			award_cfg_id = 19,
			award_id = 1,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "坚果大礼包",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[138]=
		{
			no = 138,
			award_cfg_id = 19,
			award_id = 2,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "高档电热水袋",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[139]=
		{
			no = 139,
			award_cfg_id = 19,
			award_id = 3,
			permission_key = "actp_no_cjj_gej_exchange",
			award_name = "花生酥1斤",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[140]=
		{
			no = 140,
			award_cfg_id = 19,
			award_id = 4,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[141]=
		{
			no = 141,
			award_cfg_id = 19,
			award_id = 5,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_3",},
			asset_count = {1,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[142]=
		{
			no = 142,
			award_cfg_id = 19,
			award_id = 6,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_2",},
			asset_count = {1,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[143]=
		{
			no = 143,
			award_cfg_id = 19,
			award_id = 7,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[144]=
		{
			no = 144,
			award_cfg_id = 19,
			award_id = 8,
			permission_key = "actp_no_cjj_gej_exchange",
			asset_type = {"prop_3d_fish_nuclear_bomb_1",},
			asset_count = {1,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[145]=
		{
			no = 145,
			award_cfg_id = 20,
			award_id = 1,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "坚果大礼包",
			use_num = {15000,},
			me_limit_day_num = 1,
		},
		[146]=
		{
			no = 146,
			award_cfg_id = 20,
			award_id = 2,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "高档电热水袋",
			use_num = {8000,},
			me_limit_day_num = 1,
		},
		[147]=
		{
			no = 147,
			award_cfg_id = 20,
			award_id = 3,
			permission_key = "actp_cjj_gej_exchange",
			award_name = "花生酥1斤",
			use_num = {5000,},
			me_limit_day_num = 1,
		},
		[148]=
		{
			no = 148,
			award_cfg_id = 20,
			award_id = 4,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {20000000,},
			use_num = {24000,},
		},
		[149]=
		{
			no = 149,
			award_cfg_id = 20,
			award_id = 5,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {10000000,},
			use_num = {12000,},
			me_limit_day_num = 3,
		},
		[150]=
		{
			no = 150,
			award_cfg_id = 20,
			award_id = 6,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_4",},
			asset_count = {5,},
			use_num = {6000,},
			me_limit_day_num = 2,
		},
		[151]=
		{
			no = 151,
			award_cfg_id = 20,
			award_id = 7,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"jing_bi",},
			asset_count = {2000000,},
			use_num = {2400,},
			me_limit_day_num = 1,
		},
		[152]=
		{
			no = 152,
			award_cfg_id = 20,
			award_id = 8,
			permission_key = "actp_cjj_gej_exchange",
			asset_type = {"prop_hammer_3",},
			asset_count = {10,},
			use_num = {1200,},
			me_limit_day_num = 1,
		},
		[153]=
		{
			no = 153,
			award_cfg_id = 21,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_free_001",
			asset_type = {"jing_bi",},
			asset_count = {100000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[154]=
		{
			no = 154,
			award_cfg_id = 22,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_free_001",
			asset_type = {"jing_bi",},
			asset_count = {300000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[155]=
		{
			no = 155,
			award_cfg_id = 23,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_free_001",
			asset_type = {"jing_bi",},
			asset_count = {500000,},
			use_num = {1,1,1,1,},
			me_limit_day_num = 9999,
		},
		[156]=
		{
			no = 156,
			award_cfg_id = 24,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v1v7_001",
			asset_type = {"jing_bi",},
			asset_count = {300000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[157]=
		{
			no = 157,
			award_cfg_id = 25,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v1v7_001",
			asset_type = {"jing_bi",},
			asset_count = {1000000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[158]=
		{
			no = 158,
			award_cfg_id = 26,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v1v7_001",
			asset_type = {"jing_bi",},
			asset_count = {1500000,},
			use_num = {1,1,1,1,},
			me_limit_day_num = 9999,
		},
		[159]=
		{
			no = 159,
			award_cfg_id = 27,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v8v12_001",
			asset_type = {"jing_bi",},
			asset_count = {600000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[160]=
		{
			no = 160,
			award_cfg_id = 28,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v8v12_001",
			asset_type = {"jing_bi",},
			asset_count = {2500000,},
			use_num = {1,1,},
			me_limit_day_num = 9999,
		},
		[161]=
		{
			no = 161,
			award_cfg_id = 29,
			award_id = 1,
			permission_key = "actp_buy_gift_bag_class_fclb_v8v12_001",
			asset_type = {"jing_bi",},
			asset_count = {3500000,},
			use_num = {1,1,1,1,},
			me_limit_day_num = 9999,
		},
	},
}