return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			title = "积分抽大奖",
			noCloseUI = 0,
			order = 1,
			key = "act_024_jfcdj",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_jfcdj","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "summer_gift",
		},
		[2]=
		{
			id = 2,
			ID = 2,
			title = "我要赚积分",
			noCloseUI = 0,
			order = 2,
			key = "act_024_wyzjf",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_wyzjf","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "summer_gift",
		},
		[3]=
		{
			id = 3,
			ID = 3,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl1_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl1_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl2",
		},
		[4]=
		{
			id = 4,
			ID = 4,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl2_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl2_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl1",
		},
	},
}