return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			title = "积分抽大奖",
			noCloseUI = 0,
			order = 1,
			key = "act_024_jfcdj",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_jfcdj","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "Sign_in_popup_old",
		},
		[2]=
		{
			id = 2,
			ID = 2,
			title = "我要赚积分",
			noCloseUI = 0,
			order = 2,
			key = "act_024_wyzjf",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_wyzjf","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "Sign_in_popup_old",
		},
		[3]=
		{
			id = 3,
			ID = 3,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl1_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl1_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl2",
		},
		[4]=
		{
			id = 4,
			ID = 4,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl2_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl2_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl1",
		},
		[5]=
		{
			id = 5,
			ID = 5,
			title = "小龙虾榜",
			noCloseUI = 0,
			order = 1,
			key = "act_025_xlxphb",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_025_xlxphb","panel"},
			tag = "hot",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "actp_rank_xiaolongxiaquan_025_rank",
		},
		[6]=
		{
			id = 6,
			ID = 6,
			title = "龙虾兑换",
			noCloseUI = 0,
			order = 2,
			key = "act_025_lxdh",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_025_lxdh","panel"},
			tag = "normal",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "lxdh_025_notnew",
		},
		[7]=
		{
			id = 7,
			ID = 7,
			title = "捕虾福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_025_bxfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_025_bxfl_config"},
			tag = "hot",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "actp_own_task_p_0818_bxfl",
		},
		[8]=
		{
			id = 8,
			ID = 8,
			title = "表白礼包",
			noCloseUI = 0,
			order = 1,
			key = "act_026_bblb",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_bblb","panel"},
			tag = "hot",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_own_task_p_026_dove_gift",
		},
		[9]=
		{
			id = 9,
			ID = 9,
			title = "真爱榜单",
			noCloseUI = 0,
			order = 2,
			key = "act_026_zabd",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_zabd","panel"},
			tag = "normal",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_rank_true_love_026_rank",
		},
		[10]=
		{
			id = 10,
			ID = 10,
			title = "浪漫礼盒",
			noCloseUI = 0,
			order = 3,
			key = "act_026_lmlh",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_lmlh","panel"},
			tag = "normal",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_own_task_p_026_lmqx_lmlh",
		},
	},
}