return {
	base=
	{
		[1]=
		{
			index = 1,
			name = "累计消10个苹果",
			task_id = 11001,
			need_process = 20,
			award_type = "jing_bi",
			award_count = 1000,
			xc_id = 1,
			icon = "xxl_icon_1",
		},
		[2]=
		{
			index = 2,
			name = "累计消10个铃铛",
			task_id = 11002,
			need_process = 20,
			award_type = "jing_bi",
			award_count = 2000,
			xc_id = 2,
			icon = "xxl_icon_2",
		},
		[3]=
		{
			index = 3,
			name = "累计消10个西瓜",
			task_id = 11003,
			need_process = 20,
			award_type = "jing_bi",
			award_count = 3000,
			xc_id = 3,
			icon = "xxl_icon_3",
		},
		[4]=
		{
			index = 4,
			name = "累计消10个7",
			task_id = 11004,
			need_process = 20,
			award_type = "jing_bi",
			award_count = 4000,
			xc_id = 4,
			icon = "xxl_icon_4",
		},
		[5]=
		{
			index = 5,
			name = "累计消10个BAR",
			task_id = 11005,
			need_process = 20,
			award_type = "jing_bi",
			award_count = 5000,
			xc_id = 5,
			icon = "xxl_icon_5",
		},
		[6]=
		{
			index = 6,
			name = "累计消30个苹果",
			task_id = 11006,
			need_process = 50,
			award_type = "jing_bi",
			award_count = 2500,
			xc_id = 1,
			icon = "xxl_icon_1",
		},
		[7]=
		{
			index = 7,
			name = "累计消30个铃铛",
			task_id = 11007,
			need_process = 50,
			award_type = "jing_bi",
			award_count = 5000,
			xc_id = 2,
			icon = "xxl_icon_2",
		},
		[8]=
		{
			index = 8,
			name = "累计消30个西瓜",
			task_id = 11008,
			need_process = 50,
			award_type = "jing_bi",
			award_count = 7500,
			xc_id = 3,
			icon = "xxl_icon_3",
		},
		[9]=
		{
			index = 9,
			name = "累计消30个7",
			task_id = 11009,
			need_process = 50,
			award_type = "jing_bi",
			award_count = 10000,
			xc_id = 4,
			icon = "xxl_icon_4",
		},
		[10]=
		{
			index = 10,
			name = "累计消30个BAR",
			task_id = 11010,
			need_process = 50,
			award_type = "jing_bi",
			award_count = 12500,
			xc_id = 5,
			icon = "xxl_icon_5",
		},
		[11]=
		{
			index = 11,
			name = "累计消60个苹果",
			task_id = 11011,
			need_process = 100,
			award_type = "jing_bi",
			award_count = 5000,
			xc_id = 1,
			icon = "xxl_icon_1",
		},
		[12]=
		{
			index = 12,
			name = "累计消60个铃铛",
			task_id = 11012,
			need_process = 100,
			award_type = "jing_bi",
			award_count = 10000,
			xc_id = 2,
			icon = "xxl_icon_2",
		},
		[13]=
		{
			index = 13,
			name = "累计消60个西瓜",
			task_id = 11013,
			need_process = 100,
			award_type = "jing_bi",
			award_count = 15000,
			xc_id = 3,
			icon = "xxl_icon_3",
		},
		[14]=
		{
			index = 14,
			name = "累计消60个7",
			task_id = 11014,
			need_process = 100,
			award_type = "jing_bi",
			award_count = 20000,
			xc_id = 4,
			icon = "xxl_icon_4",
		},
		[15]=
		{
			index = 15,
			name = "累计消60个BAR",
			task_id = 11015,
			need_process = 100,
			award_type = "jing_bi",
			award_count = 25000,
			xc_id = 5,
			icon = "xxl_icon_5",
		},
		[16]=
		{
			index = 16,
			name = "累计消60个苹果（福利券）",
			task_id = 11016,
			need_process = 100,
			award_type = "shop_gold_sum",
			award_count = 5,
			xc_id = 1,
			icon = "xxl_icon_1",
		},
		[17]=
		{
			index = 17,
			name = "累计消60个铃铛（福利券）",
			task_id = 11017,
			need_process = 100,
			award_type = "shop_gold_sum",
			award_count = 10,
			xc_id = 2,
			icon = "xxl_icon_2",
		},
		[18]=
		{
			index = 18,
			name = "累计消60个西瓜（福利券）",
			task_id = 11018,
			need_process = 100,
			award_type = "shop_gold_sum",
			award_count = 15,
			xc_id = 3,
			icon = "xxl_icon_3",
		},
		[19]=
		{
			index = 19,
			name = "累计消60个7（福利券）",
			task_id = 11019,
			need_process = 100,
			award_type = "shop_gold_sum",
			award_count = 20,
			xc_id = 4,
			icon = "xxl_icon_4",
		},
		[20]=
		{
			index = 20,
			name = "累计消60个BAR（福利券）",
			task_id = 11020,
			need_process = 100,
			award_type = "shop_gold_sum",
			award_count = 25,
			xc_id = 5,
			icon = "xxl_icon_5",
		},
	},
}