return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			title = "打比赛赢红包！",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1554912000,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_1",
			is_local_icon = 1,
			gotoUI = {"match_hall",},
		},
		[2]=
		{
			id = 2,
			ID = 2,
			title = "双11礼物独宠一人！",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_7",
			is_local_icon = 1,
			tag = "new",
		},
		[3]=
		{
			id = 3,
			ID = 3,
			title = "内测公告",
			order = 1,
			key = "bshncgg",
			isOnOff = 1,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n欢乐天天捕鱼将于2020年6月9日（周二）上午9点开启删档不付费测试，安卓手机可参与游戏，测试期间每天可领1000万游戏币，参与游戏排行榜更可领取丰厚奖励。\n测试期间如遇到任务问题或有更好的建议请加客服QQ：4008882620进行反馈。\n\n                                                                      官方运营团队\n                                                                      2019年6月3日",
			tag = "normal",
		},
		[4]=
		{
			id = 4,
			ID = 4,
			title = "鲸鱼杯大奖赛",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_5",
			is_local_icon = 1,
			gotoUI = {"citymatch_hall",},
			tag = "hot",
		},
		[5]=
		{
			id = 5,
			ID = 5,
			title = "2元超值礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_4",
			is_local_icon = 1,
			gotoUI = {"2_gift_bag",},
			tag = "hot",
		},
		[6]=
		{
			id = 6,
			ID = 6,
			title = "官方微信群",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "notice",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n游戏官方微信群正式上线啦，请添加客服QQ：4008882620，由客服拉您进群，群里不定时红包雨，还有漂亮的小姐姐小哥哥可以聊天哦，期待您的加入！\n感谢您对本游戏的热爱和支持！\n\n                                                             《鲸鱼家园》运营团队敬上\n                                                                          2018年10月12日",
			tag = "normal",
		},
		[7]=
		{
			id = 7,
			ID = 7,
			title = "现金奖池来袭！",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			is_local_icon = 1,
			gotoUI = {"free_hall",},
			tag = "normal",
		},
		[8]=
		{
			id = 8,
			ID = 8,
			title = "房卡场免费啦！",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_8",
			is_local_icon = 1,
			gotoUI = {"roomcard_hall",},
			tag = "hot",
		},
		[9]=
		{
			id = 9,
			ID = 9,
			title = "合伙人礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_9",
			is_local_icon = 1,
			gotoUI = {"hall_tgr",},
			tag = "hot",
		},
		[10]=
		{
			id = 10,
			ID = 10,
			title = "兑奖公告",
			order = 3,
			key = "djgg",
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "notice",
			parmData = "兑换商城温馨提示：\n\n1.红包劵是平台回馈给玩家的一种免费获得的累积型兑换券，可以在兑换商城中兑换话费或者实物；红包券可以通过完成牌局任务，参加公益锦标赛赢取，不能通过充值、玩家之间的转让获得；\n\n2.利用BUG等不正当手段获取的红包券，一经查实，红包券将清零及禁止兑换处理；\n\n3.为了更好的向玩家提供服务，兑换商城将会对不同的玩家ID推送不同的礼品内容；\n\n4.为了进行合理的风险控制以及客观情况的要求，兑换存在库存、区域、以及每日兑换频率等限制；\n\n5.根据运营以及供货方的货源情况，我们将不定期上架或者下架礼品内容；\n\n6.官方保留最终解释权。",
			tag = "normal",
		},
		[11]=
		{
			id = 11,
			ID = 11,
			title = "重要公告",
			order = 2,
			isOnOff = 1,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的鲸币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的鲸币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的鲸币交易，鲸币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			tag = "normal",
		},
		[12]=
		{
			id = 12,
			ID = 12,
			title = "双旦礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_10",
			is_local_icon = 1,
			gotoUI = {"hall_sd",},
			tag = "hot",
		},
		[13]=
		{
			id = 13,
			ID = 13,
			title = "千元赛礼包",
			order = 5,
			key = 8,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_12",
			is_local_icon = 1,
			shop_id = 13,
			gotoUI = {"hall_gift",13},
			tag = "normal",
		},
		[14]=
		{
			id = 14,
			ID = 14,
			title = "金猪礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_13",
			is_local_icon = 1,
			gotoUI = {"hall_golden_pig",},
			tag = "hot",
		},
		[15]=
		{
			id = 15,
			ID = 15,
			title = "敲敲乐",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_14",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
		},
		[16]=
		{
			id = 16,
			ID = 16,
			title = "春节礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_20",
			is_local_icon = 1,
			shop_id = 21,
			gotoUI = {"hall_gift_21",},
			tag = "new",
		},
		[17]=
		{
			id = 17,
			ID = 17,
			title = "天降财神",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_17",
			is_local_icon = 1,
			gotoUI = {hall_gift,10},
			tag = "normal",
		},
		[18]=
		{
			id = 18,
			ID = 18,
			title = "五子棋来了！",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_23",
			is_local_icon = 1,
			gotoUI = {"free_hall",},
			tag = "new",
		},
		[19]=
		{
			id = 19,
			ID = 19,
			title = "女神礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_21",
			is_local_icon = 1,
			shop_id = 28,
			gotoUI = {"hall_gift_28",},
			tag = "new",
		},
		[20]=
		{
			id = 20,
			ID = 20,
			title = "敲爱女神节",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_22",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
		},
		[21]=
		{
			id = 21,
			ID = 21,
			title = "回馈礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1554912000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_24",
			is_local_icon = 1,
			shop_id = 29,
			gotoUI = {"hall_gift_29",},
			tag = "new",
		},
		[22]=
		{
			id = 22,
			ID = 22,
			title = "敲敲乐",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_25",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
		},
		[23]=
		{
			id = 23,
			ID = 23,
			title = "踏春礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1554912000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_26",
			is_local_icon = 1,
			shop_id = 35,
			gotoUI = {"hall_gift_35",},
			tag = "new",
		},
		[24]=
		{
			id = 24,
			ID = 24,
			title = "敲敲乐",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1554912000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_25",
			is_local_icon = 0,
			gotoUI = {"hall_egg",},
			tag = "hot",
		},
		[25]=
		{
			id = 25,
			ID = 25,
			title = "关注公众号",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_27",
			is_local_icon = 1,
			tag = "normal",
		},
		[26]=
		{
			id = 26,
			ID = 26,
			title = "打高倍领鲸币",
			order = 0,
			isOnOff = 0,
			beginTime = 1555030800,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_28",
			is_local_icon = 1,
			tag = "hot",
		},
		[27]=
		{
			id = 27,
			ID = 27,
			title = "招募推广员",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_29",
			is_local_icon = 1,
			gotoUI = {"copy_gzh_sw",},
			tag = "hot",
		},
		[28]=
		{
			id = 28,
			ID = 28,
			title = "捕鱼预约",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_30",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","jyddz03",},
			tag = "new",
		},
		[29]=
		{
			id = 29,
			ID = 29,
			title = "鲸币周卡",
			order = 4,
			key = "jyzk",
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_34",
			is_local_icon = 1,
			gotoUI = {"jyzk","panel",},
			tag = "hot",
		},
		[30]=
		{
			id = 30,
			ID = 30,
			title = "财神模式",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_35",
			is_local_icon = 1,
			gotoUI = {"hall_egg","mode_cs",},
			tag = "hot",
		},
		[31]=
		{
			id = 31,
			ID = 31,
			title = "捕鱼累计赢金",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_32",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall","add_glod",},
			tag = "new",
		},
		[32]=
		{
			id = 32,
			ID = 32,
			title = "夏日回馈",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_31",
			is_local_icon = 1,
			shop_id = 38,
			gotoUI = {"hall_gift_38",},
			tag = "hot",
		},
		[33]=
		{
			id = 33,
			ID = 33,
			title = "回归奖励",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_36",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","jyddz03",},
			tag = "hot",
		},
		[34]=
		{
			id = 34,
			ID = 34,
			title = "VIP礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_37",
			is_local_icon = 1,
			gotoUI = {"vip_gift",},
			tag = "hot",
		},
		[35]=
		{
			id = 35,
			ID = 35,
			title = "万元赛",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_38",
			is_local_icon = 1,
			gotoUI = {"wys_discount",},
			tag = "hot",
		},
		[36]=
		{
			id = 36,
			ID = 36,
			title = "三元礼包",
			order = 4,
			key = "yylb",
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_41",
			is_local_icon = 1,
			gotoUI = {"hall_gift",10},
			tag = "hot",
		},
		[37]=
		{
			id = 37,
			ID = 37,
			title = "端午礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_40",
			is_local_icon = 1,
			gotoUI = {"hall_gift_73",},
			tag = "new",
		},
		[38]=
		{
			id = 38,
			ID = 38,
			title = "端午集粽子",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_42",
			is_local_icon = 0,
			gotoUI = {"act_zongzi",},
			tag = "new",
		},
		[39]=
		{
			id = 39,
			ID = 39,
			title = "商城特惠",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_618",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop",},
			tag = "hot",
		},
		[40]=
		{
			id = 40,
			ID = 40,
			title = "新游消消乐",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_998",
			is_local_icon = 1,
			gotoUI = {"game_MiniGame",},
			tag = "hot",
		},
		[41]=
		{
			id = 41,
			ID = 41,
			title = "父亲节礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_43",
			is_local_icon = 1,
			gotoUI = {"hall_gift",75},
			tag = "normal",
		},
		[42]=
		{
			id = 42,
			ID = 42,
			title = "一起抽大奖",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_44",
			is_local_icon = 1,
			gotoUI = {"activity_father",},
			tag = "new",
		},
		[43]=
		{
			id = 43,
			ID = 43,
			title = "宝箱鱼出没",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_bxy",
			is_local_icon = 0,
			tag = "new",
		},
		[44]=
		{
			id = 44,
			ID = 44,
			title = "月末福利",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity1",
			is_local_icon = 1,
			tag = "hot",
		},
		[45]=
		{
			id = 45,
			ID = 45,
			title = "月末礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_47",
			is_local_icon = 1,
			gotoUI = {"hall_gift",101},
			tag = "new",
		},
		[46]=
		{
			id = 46,
			ID = 46,
			title = "月末狂欢",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_46",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
		},
		[47]=
		{
			id = 47,
			ID = 47,
			title = "关注有礼",
			order = 7,
			key = "gzyl",
			isOnOff = 0,
			condi_key = "shield_huawei",
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_48",
			is_local_icon = 1,
			gotoUI = {"share_link","{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/webpages/shareHome.html\",\"isCircleOfFriends\": \"false\"}"},
			tag = "normal",
		},
		[48]=
		{
			id = 48,
			ID = 48,
			title = "清凉一夏",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1562601599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_50",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "hot",
		},
		[49]=
		{
			id = 49,
			ID = 49,
			title = "西瓜礼包",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1562601599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_51",
			is_local_icon = 1,
			gotoUI = {"hall_gift",102},
			tag = "hot",
		},
		[50]=
		{
			id = 50,
			ID = 50,
			title = "新人专属",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity2",
			is_local_icon = 1,
			tag = "hot",
		},
		[51]=
		{
			id = 51,
			ID = 51,
			title = "全民分享",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1564588799,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_49",
			is_local_icon = 1,
			gotoUI = {"share_activity",},
			tag = "new",
		},
		[52]=
		{
			id = 52,
			ID = 52,
			title = "全服赚钱",
			order = 3,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_52",
			is_local_icon = 1,
			gotoUI = {"money_center",},
			tag = "hot",
		},
		[53]=
		{
			id = 53,
			ID = 53,
			title = "环保家居",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_55",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=444625",},
			tag = "new",
		},
		[54]=
		{
			id = 54,
			ID = 54,
			title = "礼包兑换",
			order = 8,
			key = "lbdh",
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_57",
			is_local_icon = 1,
			gotoUI = {"exchange_gift",},
			tag = "normal",
		},
		[55]=
		{
			id = 55,
			ID = 55,
			title = "短视频大赛",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_58",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","jyddz03",},
			tag = "new",
		},
		[56]=
		{
			id = 56,
			ID = 56,
			title = "捕鱼达人榜",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_56",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
		},
		[57]=
		{
			id = 57,
			ID = 57,
			title = "暑期大放送",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity3",
			is_local_icon = 1,
			tag = "new",
		},
		[58]=
		{
			id = 58,
			ID = 58,
			title = "红包商城",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_60",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=444625",},
			tag = "new",
		},
		[59]=
		{
			id = 59,
			ID = 59,
			title = "赢暑期乐一夏",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_61",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=278268",},
			tag = "new",
		},
		[60]=
		{
			id = 60,
			ID = 60,
			title = "疯狂捕鱼",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_62",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
		},
		[61]=
		{
			id = 61,
			ID = 61,
			title = "七夕活动",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1565625597,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_63",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
		},
		[62]=
		{
			id = 62,
			ID = 62,
			title = "累充好礼",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_recharge_award_config",
			activity_id = {109,},
			task_count = {8,},
			is_local_icon = 1,
			tag = "new",
		},
		[63]=
		{
			id = 63,
			ID = 63,
			title = "捕鱼总动员",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_num_by_config",
			activity_id = {121,122,123,124,125},
			task_count = {2,2,2,2,2,2},
			is_local_icon = 1,
			tag = "new",
		},
		[64]=
		{
			id = 64,
			ID = 64,
			title = "vip上线",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_64",
			is_local_icon = 1,
			gotoUI = {"VIP2",},
			tag = "new",
		},
		[65]=
		{
			id = 65,
			ID = 65,
			title = "民族美学",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_65",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			tag = "hot",
		},
		[66]=
		{
			id = 66,
			ID = 66,
			title = "感恩公益赛",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_67",
			is_local_icon = 1,
			gotoUI = {"match_hall","ges"},
			tag = "hot",
		},
		[67]=
		{
			id = 67,
			ID = 67,
			title = "财神到",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1566662399,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_num_qql_config",
			activity_id = {127,128,129},
			task_count = {2,2,2},
			is_local_icon = 1,
			tag = "new",
		},
		[68]=
		{
			id = 68,
			ID = 68,
			title = "周年预约有礼",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = 1567439999,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity7",
			is_local_icon = 1,
			tag = "new",
		},
		[69]=
		{
			id = 69,
			ID = 69,
			title = "开心消消乐",
			order = 0,
			isOnOff = 0,
			beginTime = 1566862200,
			endTime = 1567267199,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_gold_xxl_config",
			activity_id = {133,},
			task_count = {5,},
			is_local_icon = 1,
			tag = "new",
		},
		[70]=
		{
			id = 70,
			ID = 70,
			title = "周年庆万元赛",
			order = 0,
			isOnOff = 0,
			beginTime = 1566862200,
			endTime = 1567602000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_68",
			is_local_icon = 1,
			gotoUI = {"zhounian_share",},
			tag = "hot",
		},
		[71]=
		{
			id = 71,
			ID = 71,
			title = "金秋拾惠",
			order = 0,
			isOnOff = 0,
			beginTime = 1566862200,
			endTime = 1567467000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_69",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			tag = "hot",
		},
		[72]=
		{
			id = 72,
			ID = 10000,
			title = "苹果用户必看",
			order = 7,
			isOnOff = 0,
			condi_key = "shield_huawei",
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_70",
			is_local_icon = 1,
			gotoUI = {"share_link","{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/shareHome/index.html\",\"isCircleOfFriends\": \"true\"}"},
			tag = "normal",
		},
		[73]=
		{
			id = 73,
			ID = 73,
			title = "捕鱼大奖赛礼包",
			order = 6,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_77",
			is_local_icon = 1,
			gotoUI = {"buy_gift",10025},
			tag = "normal",
		},
		[74]=
		{
			id = 74,
			ID = 74,
			title = "推广员排行榜",
			order = 1,
			isOnOff = 0,
			beginTime = 1568649600,
			endTime = 1569254400,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_78",
			is_local_icon = 1,
			gotoUI = {"money_center","tgphb",},
			tag = "hot",
		},
		[75]=
		{
			id = 75,
			ID = 75,
			title = "国庆放价",
			order = 4,
			isOnOff = 0,
			beginTime = 1569283200,
			endTime = 1570463999,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_83",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1184455",},
			tag = "new",
		},
		[76]=
		{
			id = 76,
			ID = 76,
			title = "今日必抢",
			order = 2,
			isOnOff = 0,
			beginTime = 1571095800,
			endTime = 1571673599,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_84",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[77]=
		{
			id = 77,
			ID = 77,
			title = "推广成就福利",
			order = 0,
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_85",
			is_local_icon = 1,
			gotoUI = {"achievement_tg",},
			tag = "new",
		},
		[78]=
		{
			id = 78,
			ID = 78,
			title = "万圣节福利",
			order = 0,
			isOnOff = 0,
			beginTime = 1572305400,
			endTime = 1572883199,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_recharge_award_config",
			activity_id = {21020,},
			task_count = {7,},
			is_local_icon = 1,
			tag = "new",
		},
		[79]=
		{
			id = 79,
			ID = 79,
			title = "万圣狂欢",
			order = 0,
			isOnOff = 0,
			beginTime = 1572305400,
			endTime = 1572883199,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_87",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1500291",},
			tag = "new",
		},
		[80]=
		{
			id = 80,
			ID = 80,
			title = "决战双11",
			order = 0,
			isOnOff = 0,
			beginTime = 1572910200,
			endTime = 1573487999,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_88",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501239",},
			tag = "new",
		},
		[81]=
		{
			id = 81,
			ID = 81,
			title = "季末特惠",
			order = 0,
			isOnOff = 0,
			beginTime = 1573515000,
			endTime = 1574092799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_90",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501244",},
			tag = "new",
		},
		[82]=
		{
			id = 82,
			ID = 82,
			title = "推广员排行榜",
			order = 0,
			isOnOff = 0,
			beginTime = 1572910200,
			endTime = 1573487999,
			noCloseUI = 0,
			type = "activity",
			showType = "image",
			parmData = "ad_078",
			is_local_icon = 1,
			gotoUI = {"money_center","tgphb",},
			tag = "new",
		},
		[83]=
		{
			id = 83,
			ID = 83,
			title = "鲸选优品",
			order = 3,
			isOnOff = 0,
			beginTime = 1574119800,
			endTime = 1574697599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_081",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=652574",},
			tag = "new",
		},
		[84]=
		{
			id = 84,
			ID = 84,
			title = "感恩在心",
			order = 3,
			isOnOff = 0,
			beginTime = 1574724600,
			endTime = 1575302399,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_082",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[85]=
		{
			id = 85,
			ID = 85,
			title = "感恩公益赛",
			order = 0,
			key = "gegys_yy",
			isOnOff = 0,
			beginTime = 1574638200,
			endTime = 1574946000,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "gegys_yy",
			is_local_icon = 1,
			gotoUI = {"gegys_yy","panel",},
			tag = "new",
		},
		[86]=
		{
			id = 86,
			ID = 86,
			title = "约惠冬季",
			order = 3,
			isOnOff = 0,
			beginTime = 1575329400,
			endTime = 1575907199,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_083",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1500291",},
			tag = "new",
		},
		[87]=
		{
			id = 87,
			ID = 87,
			title = "跑得快预热",
			order = 1,
			isOnOff = 0,
			beginTime = 1574724600,
			endTime = 1575302399,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_084",
			is_local_icon = 1,
			tag = "new",
		},
		[88]=
		{
			id = 88,
			ID = 88,
			title = "系统升级奖励",
			order = 1,
			key = "act_sjjl",
			isOnOff = 0,
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_sjjl",
			is_local_icon = 1,
			gotoUI = {"act_sjjl","panel",},
			tag = "new",
		},
		[89]=
		{
			id = 89,
			ID = 100,
			title = "跑得快新游福利",
			order = 0,
			isOnOff = 0,
			beginTime = 1575329400,
			endTime = 1575907199,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_task_gold_pdk",
			activity_id = {21030,},
			task_count = {5,},
			is_local_icon = 1,
			gotoUI = {"pdk_activity","enter"},
			tag = "new",
		},
		[90]=
		{
			id = 90,
			ID = 101,
			title = "决战双12",
			order = 3,
			isOnOff = 0,
			beginTime = 1575934200,
			endTime = 1576511999,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_085",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1184455",},
			tag = "new",
		},
		[91]=
		{
			id = 91,
			ID = 102,
			title = "浪漫平安夜",
			order = 3,
			isOnOff = 0,
			beginTime = 1576539000,
			endTime = 1577116799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_086",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=998615",},
			tag = "new",
		},
		[92]=
		{
			id = 92,
			ID = 103,
			title = "圣诞狂欢",
			order = 3,
			isOnOff = 0,
			beginTime = 1577143800,
			endTime = 1577721599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_087",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501239",},
			tag = "new",
		},
		[93]=
		{
			id = 93,
			ID = 104,
			title = "推广赚钱",
			order = 1,
			isOnOff = 0,
			beginTime = 1576539000,
			endTime = 1577116799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_91",
			is_local_icon = 1,
			gotoUI = {"money_center",},
			tag = "new",
		},
		[94]=
		{
			id = 94,
			ID = 105,
			title = "元旦欢乐购",
			order = 3,
			isOnOff = 0,
			beginTime = 1577748600,
			endTime = 1578326400,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_92",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			tag = "new",
		},
		[95]=
		{
			id = 95,
			ID = 106,
			title = "金鼠贺岁",
			order = 3,
			isOnOff = 0,
			beginTime = 1578326400,
			endTime = 1578931200,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_93",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[96]=
		{
			id = 96,
			ID = 107,
			title = "新春钜惠",
			order = 3,
			isOnOff = 0,
			beginTime = 1578931200,
			endTime = 1579536000,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_94",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[97]=
		{
			id = 97,
			ID = 108,
			title = "鲸鱼年货节",
			order = 3,
			isOnOff = 0,
			beginTime = 1579536000,
			endTime = 1580745600,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_95",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=652574",},
			tag = "new",
		},
		[98]=
		{
			id = 98,
			ID = 109,
			title = "喜乐元宵",
			order = 3,
			isOnOff = 0,
			beginTime = 1580745600,
			endTime = 1581350400,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_96",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=89115",},
			tag = "new",
		},
		[99]=
		{
			id = 99,
			ID = 110,
			title = "完美情人节",
			order = 3,
			isOnOff = 0,
			beginTime = 1581350400,
			endTime = 1581955200,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_97",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=135277",},
			tag = "new",
		},
		[100]=
		{
			id = 100,
			ID = 111,
			title = "开工大吉赛",
			order = 0,
			key = "act_ycs_bsyy",
			isOnOff = 0,
			beginTime = 1580167800,
			endTime = 1580745599,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_ycs_bsyy",
			is_local_icon = 1,
			gotoUI = {"act_ycs_bsyy","panel",},
			tag = "new",
		},
		[101]=
		{
			id = 101,
			ID = 112,
			title = "邀朋友",
			order = 0,
			isOnOff = 0,
			beginTime = 1580378400,
			endTime = 1581328800,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_101",
			is_local_icon = 1,
			tag = "new",
		},
		[102]=
		{
			id = 102,
			ID = 113,
			title = "月末福利赛",
			order = -2,
			key = "act_001_bsyy",
			isOnOff = 0,
			beginTime = 1582587000,
			endTime = 1582981200,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_001_bsyy",
			is_local_icon = 1,
			gotoUI = {"act_001_bsyy","panel",},
			tag = "new",
		},
		[103]=
		{
			id = 103,
			ID = 114,
			title = "有奖问答",
			order = -1,
			key = "act_001_yjwd",
			isOnOff = 0,
			beginTime = 1582587000,
			endTime = 1583164799,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_001_yjwd",
			is_local_icon = 1,
			gotoUI = {"act_001_yjwd","panel",},
			tag = "new",
		},
		[104]=
		{
			id = 104,
			ID = 115,
			title = "爱心助农",
			order = 3,
			isOnOff = 0,
			beginTime = 1582587000,
			endTime = 1583164799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_102",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501244",},
			tag = "new",
		},
		[105]=
		{
			id = 105,
			ID = 116,
			title = "约惠女神节",
			order = 3,
			isOnOff = 0,
			beginTime = 1583191800,
			endTime = 1583769599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_103",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=89115",},
			tag = "new",
		},
		[106]=
		{
			id = 106,
			ID = 117,
			title = "放心购",
			order = 3,
			isOnOff = 0,
			beginTime = 1583796600,
			endTime = 1584460799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_104",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=998615",},
			tag = "new",
		},
		[107]=
		{
			id = 107,
			ID = 118,
			title = "兑换话费",
			order = 2,
			isOnOff = 0,
			beginTime = 1583796600,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_105",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1500291",},
			tag = "new",
		},
		[108]=
		{
			id = 108,
			ID = 119,
			title = "全民焕新节",
			order = 3,
			isOnOff = 0,
			beginTime = 1584401400,
			endTime = 1584979199,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_106",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			tag = "new",
		},
		[109]=
		{
			id = 109,
			ID = 120,
			title = "春夏新风尚",
			order = 3,
			isOnOff = 0,
			beginTime = 1585006200,
			endTime = 1585583999,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_107",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501239",},
			tag = "new",
		},
		[110]=
		{
			id = 110,
			ID = 121,
			title = "愈购愚乐",
			order = 4,
			isOnOff = 0,
			beginTime = 1585611000,
			endTime = 1586188799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_108",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[111]=
		{
			id = 111,
			ID = 122,
			title = "比赛预约",
			order = -2,
			key = "act_005_bsyy",
			isOnOff = 0,
			beginTime = 1585006200,
			endTime = 1585583999,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_001_bsyy",
			is_local_icon = 1,
			gotoUI = {"act_001_bsyy","panel",},
			tag = "new",
		},
		[112]=
		{
			id = 112,
			ID = 123,
			title = "vip3直通礼包",
			order = 1,
			key = "sys_vip2_up",
			isOnOff = 0,
			condi_key = "vip2_buygift",
			beginTime = 1585611000,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "sys_vip2_up",
			is_local_icon = 1,
			gotoUI = {"sys_vip2_up","panel"},
			tag = "hot",
		},
		[113]=
		{
			id = 113,
			ID = 124,
			title = "领取红包",
			order = 2,
			key = "sys_vip3_guide",
			isOnOff = 0,
			condi_key = "vip3_show",
			beginTime = 1585611000,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "sys_vip3_guide",
			is_local_icon = 1,
			gotoUI = {"sys_vip3_guide","panel"},
			tag = "hot",
		},
		[114]=
		{
			id = 114,
			ID = 125,
			title = "趣味复活节",
			order = 4,
			isOnOff = 0,
			beginTime = 1586302200,
			endTime = 1586793599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_109",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501244",},
			tag = "new",
		},
		[115]=
		{
			id = 115,
			ID = 126,
			title = "鲸鱼亲子节",
			order = 4,
			isOnOff = 0,
			beginTime = 1586820600,
			endTime = 1587398399,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_110",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=445439",},
			tag = "new",
		},
		[116]=
		{
			id = 116,
			ID = 127,
			title = "环保生活节",
			order = 4,
			isOnOff = 0,
			beginTime = 1587425400,
			endTime = 1588003199,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_111",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=89115",},
			tag = "new",
		},
		[117]=
		{
			id = 117,
			ID = 128,
			title = "弹弹乐上线",
			order = 0,
			isOnOff = 0,
			beginTime = 1586302200,
			endTime = 1586793599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_112",
			is_local_icon = 1,
			gotoUI = {"game_MiniGame",},
			tag = "new",
		},
		[118]=
		{
			id = 118,
			ID = 129,
			title = "苹果大战上线",
			order = 0,
			isOnOff = 0,
			beginTime = 1586820600,
			endTime = 1587398399,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_113",
			is_local_icon = 1,
			gotoUI = {"game_MiniGame",},
			tag = "new",
		},
		[119]=
		{
			id = 119,
			ID = 130,
			title = "捕鱼奖池",
			order = 0,
			isOnOff = 0,
			condi_key = "fish_caijin_hongbao",
			beginTime = 1587425400,
			endTime = 1588003199,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_114",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
		},
		[120]=
		{
			id = 120,
			ID = 131,
			title = "全返礼包I",
			order = 0,
			key = "act_006_qflb1",
			isOnOff = 0,
			beginTime = 1588030200,
			endTime = 1588607999,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_006_qflb1",
			is_local_icon = 1,
			gotoUI = {"act_006_qflb1","panel",},
			tag = "new",
		},
		[121]=
		{
			id = 121,
			ID = 132,
			title = "贵族月卡",
			order = 5,
			key = "act_009_yk_gz",
			isOnOff = 0,
			beginTime = 1588030200,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_009_yk_gz",
			is_local_icon = 1,
			gotoUI = {"act_009_yk_gz","panel",},
			tag = "hot",
		},
		[122]=
		{
			id = 122,
			ID = 133,
			title = "五一礼包",
			order = 3,
			key = "ty_gift",
			isOnOff = 0,
			condi_key = "labor_day_gift",
			beginTime = 1588030200,
			endTime = 1588607999,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "ty_gift",
			is_local_icon = 1,
			gotoUI = {"ty_gift","gift_cglb_mini",},
			tag = "new",
		},
		[123]=
		{
			id = 123,
			ID = 134,
			title = "五一狂欢周",
			order = 6,
			isOnOff = 0,
			beginTime = 1588030200,
			endTime = 1588607999,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_115",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			tag = "new",
		},
		[124]=
		{
			id = 124,
			ID = 135,
			title = "母亲节特惠",
			order = 6,
			isOnOff = 0,
			beginTime = 1588635000,
			endTime = 1589212799,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_116",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1501239",},
			tag = "new",
		},
		[125]=
		{
			id = 125,
			ID = 136,
			title = "鲸鱼旅游节",
			order = 6,
			isOnOff = 0,
			beginTime = 1589239800,
			endTime = 1589817599,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_117",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=1264722",},
			tag = "new",
		},
		[126]=
		{
			id = 126,
			ID = 137,
			title = "五一福利赛",
			order = -1,
			key = "act_010_51flsyy",
			isOnOff = 0,
			beginTime = 1588028400,
			endTime = 1588424400,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "act_010_51flsyy",
			is_local_icon = 1,
			gotoUI = {"act_010_51flsyy","panel"},
			tag = "new",
		},
		[127]=
		{
			id = 127,
			ID = 138,
			title = "16元红包",
			order = 8,
			isOnOff = 0,
			condi_key = "jyddz_type_plat",
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_118",
			is_local_icon = 1,
			gotoUI = {"sys_011_CplZh","download"},
			tag = "new",
		},
		[128]=
		{
			id = 128,
			ID = 139,
			title = "16元红包",
			order = 8,
			isOnOff = 0,
			condi_key = "wqp_type_plat",
			beginTime = -1,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "image",
			parmData = "ad_119",
			is_local_icon = 1,
			gotoUI = {"sys_011_CplZh","download"},
			tag = "new",
		},
		[129]=
		{
			id = 129,
			ID = 140,
			title = "超值月卡",
			order = 3,
			key = "sys_011_yueka_new",
			isOnOff = 0,
			beginTime = 1589239800,
			endTime = -1,
			noCloseUI = 1,
			type = "activity",
			showType = "prefab",
			parmData = "sys_011_yueka_new",
			is_local_icon = 1,
			gotoUI = {"sys_011_yueka_new","panel"},
			tag = "new",
		},
	},
}