return {
	config=
	{
		[1]=
		{
			line = 1,
			gift_key = "gift_kllb",
			temp = "T3",
			gift_id = {10081,10082,10083},
			bg_img = "sdlb_bg",
			enter_icon = "sdlb_btn_lb",
			icon_img = {"sdlb_btn_1","sdlb_btn_2","sdlb_btn_3"},
			btn_img = {"sdlb_btn_1_2","sdlb_btn_2_2","sdlb_btn_3_2"},
			btn_img_no = {"sdlb_btn_1_1","sdlb_btn_2_1","sdlb_btn_3_1"},
			isOnOff = 1,
		},
		[2]=
		{
			line = 2,
			gift_key = "gift_bybs",
			temp = "T1",
			gift_id = {10025,},
			bg_img = "gy_57",
			enter_icon = "by_match_btn_thmp",
			isOnOff = 1,
		},
		[3]=
		{
			line = 3,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10239,10240,10241,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"60万金币","10万金币","锁定*5","500万金币","20万金币","锁定*10","980万金币","30万金币","锁定*20",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[4]=
		{
			line = 4,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10087,10088,10089,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"10万金币","10万金币","锁定*1","30万金币","20万金币","锁定*2","60万金币","30万金币","锁定*3",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[5]=
		{
			line = 5,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10090,10091,10092,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"60万金币","20万金币","锁定*3","120万金币","20万金币","锁定*10","180万金币","20万金币","锁定*20",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[6]=
		{
			line = 6,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10093,10094,10095,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"180万金币","10万金币","锁定*10","500万金币","20万金币","锁定*10","980万金币","30万金币","锁定*20",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[7]=
		{
			line = 7,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10096,10097,10098,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"500万金币","20万金币","锁定*10","980万金币","30万金币","锁定*20","1980万金币","80万金币","锁定*30",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[8]=
		{
			line = 8,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10099,10100,10101,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"980万金币","30万金币","锁定*20","1980万金币","80万金币","锁定*30","4880万金币","150万金币","锁定*50",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","ty_btn_sd","pay_icon_gold8","pay_icon_gold11","ty_btn_sd","pay_icon_gold10","pay_icon_gold4","ty_btn_sd",},
			isOnOff = 1,
		},
		[9]=
		{
			line = 9,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10103,10104,10105,},
			bg_img = "cjslb_bg_1",
			db_img = "cjslb_dk_1",
			enter_icon = "cjslb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"1万鲸币","1万鲸币","记牌器*1","3万鲸币","2万鲸币","记牌器*2","6万鲸币","3万鲸币","记牌器*3",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","bag_icon_jipaiqi","pay_icon_gold10","pay_icon_gold4","bag_icon_jipaiqi",},
			isOnOff = 0,
		},
		[10]=
		{
			line = 10,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10106,10107,10108,},
			bg_img = "cjslb_bg_1",
			db_img = "cjslb_dk_1",
			enter_icon = "cjslb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"6万鲸币","2万鲸币","记牌器*3","18万鲸币","2万鲸币","2万鱼币","48万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[11]=
		{
			line = 11,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10109,10110,10111,},
			bg_img = "cjslb_bg_1",
			db_img = "cjslb_dk_1",
			enter_icon = "cjslb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"18万鲸币","1万鲸币","1万鱼币","48万鲸币","3万鲸币","2万鱼币","98万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[12]=
		{
			line = 12,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10112,10113,10114,},
			bg_img = "cjslb_bg_1",
			db_img = "cjslb_dk_1",
			enter_icon = "cjslb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"48万鲸币","2万鲸币","1万鱼币","98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[13]=
		{
			line = 13,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10115,10116,10117,},
			bg_img = "cjslb_bg_1",
			db_img = "cjslb_dk_1",
			enter_icon = "cjslb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币","498万鲸币","15万鲸币","5万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[14]=
		{
			line = 14,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10118,10119,10120,},
			bg_img = "gdnlb_bg_1",
			db_img = "gdnlb_dk_1",
			enter_icon = "gdnlb_icon_1",
			name_img = {"gdnlb_imgf_1", "gdnlb_imgf_3", "gdnlb_imgf_6"},
			font_c = "FFEABFFF",
			outline_c = "7F250DFF",
			gift_c = "FFEABFFF",
			pay_name = {"1万鲸币","1万鲸币","记牌器*1","3万鲸币","2万鲸币","记牌器*2","6万鲸币","3万鲸币","记牌器*3",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","bag_icon_jipaiqi","pay_icon_gold10","pay_icon_gold4","bag_icon_jipaiqi",},
			isOnOff = 0,
		},
		[15]=
		{
			line = 15,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10121,10122,10123,},
			bg_img = "gdnlb_bg_1",
			db_img = "gdnlb_dk_1",
			enter_icon = "gdnlb_icon_1",
			name_img = {"gdnlb_imgf_6", "gdnlb_imgf_12", "gdnlb_imgf_18"},
			font_c = "FFEABFFF",
			outline_c = "7F251DFF",
			gift_c = "FFEABFFF",
			pay_name = {"6万鲸币","2万鲸币","记牌器*3","18万鲸币","2万鲸币","2万鱼币","48万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[16]=
		{
			line = 16,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10124,10125,10126,},
			bg_img = "gdnlb_bg_1",
			db_img = "gdnlb_dk_1",
			enter_icon = "gdnlb_icon_1",
			name_img = {"gdnlb_imgf_18", "gdnlb_imgf_30", "gdnlb_imgf_48"},
			font_c = "FFEABFFF",
			outline_c = "7F252DFF",
			gift_c = "FFEABFFF",
			pay_name = {"18万鲸币","1万鲸币","1万鱼币","48万鲸币","3万鲸币","2万鱼币","98万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[17]=
		{
			line = 17,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10127,10128,10129,},
			bg_img = "gdnlb_bg_1",
			db_img = "gdnlb_dk_1",
			enter_icon = "gdnlb_icon_1",
			name_img = {"gdnlb_imgf_48", "gdnlb_imgf_98", "gdnlb_imgf_198"},
			font_c = "FFEABFFF",
			outline_c = "7F253DFF",
			gift_c = "FFEABFFF",
			pay_name = {"48万鲸币","2万鲸币","1万鱼币","98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[18]=
		{
			line = 18,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10130,10131,10132,},
			bg_img = "gdnlb_bg_1",
			db_img = "gdnlb_dk_1",
			enter_icon = "gdnlb_icon_1",
			name_img = {"gdnlb_imgf_98", "gdnlb_imgf_198", "gdnlb_imgf_498"},
			font_c = "FFEABFFF",
			outline_c = "7F254DFF",
			gift_c = "FFEABFFF",
			pay_name = {"98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币","498万鲸币","15万鲸币","5万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[19]=
		{
			line = 19,
			gift_key = "gift_cglb_mini",
			temp = "T4",
			gift_id = {10210,10211,10212,},
			bg_img = "wylb_bg_wylb",
			db_img = "wylb_bg_2",
			name_c = "FFF9A5FF",
			name_outline = "9A201FFF",
			font_c = "A7501AFF",
			outline_c = "FFF8D9FF",
			gift_c = "8E3A01FF",
			pay_name = {"1万鲸币","记牌器*1","铲子*1","3万鲸币","记牌器*2","铲子*2","6万鲸币","记牌器*3","铲子*3",},
			icon_img = {"pay_icon_gold7","bag_icon_jipaiqi","com_award_icon_chanz1","pay_icon_gold8","bag_icon_jipaiqi","com_award_icon_chanz2","pay_icon_gold10","bag_icon_jipaiqi","com_award_icon_chanz3",},
			isOnOff = 0,
		},
		[20]=
		{
			line = 20,
			gift_key = "gift_cglb_mini",
			temp = "T4",
			gift_id = {10213,10214,10215,},
			bg_img = "wylb_bg_wylb",
			db_img = "wylb_bg_2",
			name_c = "FFF9A5FF",
			name_outline = "9A201FFF",
			font_c = "A7501AFF",
			outline_c = "FFF8D9FF",
			gift_c = "8E3A01FF",
			pay_name = {"6万鲸币","记牌器*3","铲子*2","12万鲸币","1万鱼币","铲子*2","18万鲸币","2万鱼币","铲子*2",},
			icon_img = {"pay_icon_gold7","bag_icon_jipaiqi","com_award_icon_chanz1","pay_icon_gold8","com_award_icon_yb1","com_award_icon_chanz2","pay_icon_gold10","com_award_icon_yb2","com_award_icon_chanz3",},
			isOnOff = 0,
		},
		[21]=
		{
			line = 21,
			gift_key = "gift_cglb_mini",
			temp = "T4",
			gift_id = {10216,10217,10218,},
			bg_img = "wylb_bg_wylb",
			db_img = "wylb_bg_2",
			name_c = "FFF9A5FF",
			name_outline = "9A201FFF",
			font_c = "A7501AFF",
			outline_c = "FFF8D9FF",
			gift_c = "8E3A01FF",
			pay_name = {"18万鲸币","1万鱼币","铲子*1","30万鲸币","2万鱼币","铲子*2","48万鲸币","2万鱼币","铲子*3",},
			icon_img = {"pay_icon_gold7","com_icon_yb","com_award_icon_chanz1","pay_icon_gold8","com_award_icon_yb1","com_award_icon_chanz2","pay_icon_gold10","com_award_icon_yb2","com_award_icon_chanz3",},
			isOnOff = 0,
		},
		[22]=
		{
			line = 22,
			gift_key = "gift_cglb_mini",
			temp = "T4",
			gift_id = {10219,10220,10221,},
			bg_img = "wylb_bg_wylb",
			db_img = "wylb_bg_2",
			name_c = "FFF9A5FF",
			name_outline = "9A201FFF",
			font_c = "A7501AFF",
			outline_c = "FFF8D9FF",
			gift_c = "8E3A01FF",
			pay_name = {"48万鲸币","1万鱼币","铲子*2","98万鲸币","2万鱼币","铲子*3","198万鲸币","3万鱼币","铲子*8",},
			icon_img = {"pay_icon_gold7","com_icon_yb","com_award_icon_chanz1","pay_icon_gold8","com_award_icon_yb1","com_award_icon_chanz2","pay_icon_gold10","com_award_icon_yb2","com_award_icon_chanz3",},
			isOnOff = 0,
		},
		[23]=
		{
			line = 23,
			gift_key = "gift_cglb_mini",
			temp = "T4",
			gift_id = {10222,10223,10224,},
			bg_img = "wylb_bg_wylb",
			db_img = "wylb_bg_2",
			name_c = "FFF9A5FF",
			name_outline = "9A201FFF",
			font_c = "A7501AFF",
			outline_c = "FFF8D9FF",
			gift_c = "8E3A01FF",
			pay_name = {"98万鲸币","2万鱼币","铲子*3","198万鲸币","3万鱼币","铲子*8","498万鲸币","5万鱼币","铲子*15",},
			icon_img = {"pay_icon_gold7","com_icon_yb","com_award_icon_chanz1","pay_icon_gold8","com_award_icon_yb1","com_award_icon_chanz2","pay_icon_gold10","com_award_icon_yb2","com_award_icon_chanz3",},
			isOnOff = 0,
		},
		[24]=
		{
			line = 24,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10148,10149,10150,},
			bg_img = "nxxlb_bg_1",
			db_img = "nyxlb_dk_1",
			enter_icon = "nyxlb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"1万鲸币","1万鲸币","记牌器*1","3万鲸币","2万鲸币","记牌器*2","6万鲸币","3万鲸币","记牌器*3",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","bag_icon_jipaiqi","pay_icon_gold10","pay_icon_gold4","bag_icon_jipaiqi",},
			isOnOff = 0,
		},
		[25]=
		{
			line = 25,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10151,10152,10153,},
			bg_img = "nxxlb_bg_1",
			db_img = "nyxlb_dk_1",
			enter_icon = "nyxlb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"6万鲸币","2万鲸币","记牌器*3","18万鲸币","2万鲸币","2万鱼币","48万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","bag_icon_jipaiqi","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[26]=
		{
			line = 26,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10154,10155,10156,},
			bg_img = "nxxlb_bg_1",
			db_img = "nyxlb_dk_1",
			enter_icon = "nyxlb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"18万鲸币","1万鲸币","1万鱼币","48万鲸币","3万鲸币","2万鱼币","98万鲸币","3万鲸币","2万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[27]=
		{
			line = 27,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10157,10158,10159,},
			bg_img = "nxxlb_bg_1",
			db_img = "nyxlb_dk_1",
			enter_icon = "nyxlb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"48万鲸币","2万鲸币","1万鱼币","98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
		[28]=
		{
			line = 28,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10160,10161,10162,},
			bg_img = "nxxlb_bg_1",
			db_img = "nyxlb_dk_1",
			enter_icon = "nyxlb_icon_1",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "8E3A01FF",
			pay_name = {"98万鲸币","3万鲸币","2万鱼币","198万鲸币","8万鲸币","3万鱼币","498万鲸币","15万鲸币","5万鱼币",},
			icon_img = {"pay_icon_gold7","pay_icon_gold3","com_icon_yb","pay_icon_gold8","pay_icon_gold11","com_award_icon_yb1","pay_icon_gold10","pay_icon_gold4","com_award_icon_yb2",},
			isOnOff = 0,
		},
	},
	Sheet1=
	{
	},
	Sheet2=
	{
	},
}