return {
	hallconfig=
	{
		[1]=
		{
			id = 1,
			bannerID = 1,
			isOnOff = 0,
			order = 1,
			gotoUI = {"match_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_1",
			is_local_icon = 1,
		},
		[2]=
		{
			id = 2,
			bannerID = 2,
			isOnOff = 0,
			order = 2,
			gotoUI = {"hall_gzh",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_9",
			is_local_icon = 1,
		},
		[3]=
		{
			id = 3,
			bannerID = 3,
			isOnOff = 0,
			order = 3,
			gotoUI = {"hall_gzh",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_9",
			is_local_icon = 1,
		},
		[4]=
		{
			id = 4,
			bannerID = 4,
			isOnOff = 0,
			order = 4,
			gotoUI = {"citymatch_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_2",
			is_local_icon = 1,
		},
		[5]=
		{
			id = 5,
			bannerID = 5,
			isOnOff = 0,
			order = 5,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_7",
			is_local_icon = 1,
		},
		[6]=
		{
			id = 6,
			bannerID = 6,
			isOnOff = 0,
			order = 6,
			gotoUI = {"free_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_8",
			is_local_icon = 1,
		},
		[7]=
		{
			id = 7,
			bannerID = 7,
			isOnOff = 0,
			order = 7,
			gotoUI = {"roomcard_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_3",
			is_local_icon = 1,
		},
		[8]=
		{
			id = 8,
			bannerID = 8,
			isOnOff = 0,
			order = 0,
			gotoUI = {"hall_tgr",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_11",
			is_local_icon = 1,
		},
		[9]=
		{
			id = 9,
			bannerID = 9,
			isOnOff = 0,
			order = 0,
			gotoUI = {"hall_sd",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_12",
			is_local_icon = 1,
		},
		[10]=
		{
			id = 10,
			bannerID = 10,
			isOnOff = 0,
			order = -1,
			gotoUI = {"hall_gift_13",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_14",
			is_local_icon = 1,
		},
		[11]=
		{
			id = 11,
			bannerID = 11,
			isOnOff = 0,
			order = -2,
			gotoUI = {"hall_golden_pig",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_15",
			is_local_icon = 1,
		},
		[12]=
		{
			id = 12,
			bannerID = 12,
			isOnOff = 0,
			order = 0,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_16",
			is_local_icon = 1,
		},
		[13]=
		{
			id = 13,
			bannerID = 13,
			isOnOff = 0,
			order = -3,
			gotoUI = {"hall_gift_21",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_21",
			is_local_icon = 1,
		},
		[14]=
		{
			id = 14,
			bannerID = 14,
			isOnOff = 0,
			order = -4,
			gotoUI = {"free_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_18",
			is_local_icon = 1,
		},
		[15]=
		{
			id = 15,
			bannerID = 15,
			isOnOff = 0,
			order = -5,
			gotoUI = {"free_hall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_24",
			is_local_icon = 1,
		},
		[16]=
		{
			id = 16,
			bannerID = 16,
			isOnOff = 0,
			order = -6,
			gotoUI = {"hall_gift_28",},
			shop_id = 28,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_22",
			is_local_icon = 1,
		},
		[17]=
		{
			id = 17,
			bannerID = 17,
			isOnOff = 0,
			order = -7,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_23",
			is_local_icon = 1,
		},
		[18]=
		{
			id = 18,
			bannerID = 18,
			isOnOff = 0,
			order = -8,
			gotoUI = {"hall_gift_29",},
			shop_id = 29,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_25",
			is_local_icon = 1,
		},
		[19]=
		{
			id = 19,
			bannerID = 19,
			isOnOff = 0,
			order = -9,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_26",
			is_local_icon = 1,
		},
		[20]=
		{
			id = 20,
			bannerID = 20,
			isOnOff = 0,
			order = -10,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_27",
			is_local_icon = 1,
		},
		[21]=
		{
			id = 21,
			bannerID = 21,
			isOnOff = 0,
			order = -10,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_28",
			is_local_icon = 1,
		},
		[22]=
		{
			id = 22,
			bannerID = 22,
			isOnOff = 0,
			order = -10,
			gotoUI = {"hall_gift_35",},
			shop_id = 35,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_29",
			is_local_icon = 1,
		},
		[23]=
		{
			id = 23,
			bannerID = 23,
			isOnOff = 0,
			order = -11,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_26",
			is_local_icon = 0,
		},
		[24]=
		{
			id = 24,
			bannerID = 24,
			isOnOff = 0,
			order = -12,
			srartTime = 1555030800,
			endTime = -1,
			imageName = "hall_banner_30",
			is_local_icon = 1,
		},
		[25]=
		{
			id = 25,
			bannerID = 25,
			isOnOff = 0,
			order = -14,
			gotoUI = {"copy_gzh_sw",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_46",
			is_local_icon = 1,
		},
		[26]=
		{
			id = 26,
			bannerID = 26,
			isOnOff = 0,
			order = -14,
			gotoUI = {"copy_qq","4008882620",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_32",
			is_local_icon = 1,
		},
		[27]=
		{
			id = 27,
			bannerID = 27,
			isOnOff = 0,
			order = -15,
			gotoUI = {"weekly_card",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_36",
			is_local_icon = 1,
		},
		[28]=
		{
			id = 28,
			bannerID = 28,
			isOnOff = 0,
			order = -15,
			gotoUI = {"hall_egg","mode_cs",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_37",
			is_local_icon = 1,
		},
		[29]=
		{
			id = 29,
			bannerID = 29,
			isOnOff = 0,
			order = -16,
			gotoUI = {"game_FishingHall","add_glod",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_34",
			is_local_icon = 1,
		},
		[30]=
		{
			id = 30,
			bannerID = 30,
			isOnOff = 0,
			order = -13,
			gotoUI = {"hall_gift_38",},
			shop_id = 38,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_33",
			is_local_icon = 1,
		},
		[31]=
		{
			id = 31,
			bannerID = 31,
			isOnOff = 0,
			order = -12,
			gotoUI = {"copy_qq","4008882620",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_38",
			is_local_icon = 1,
		},
		[32]=
		{
			id = 32,
			bannerID = 32,
			isOnOff = 0,
			order = -17,
			gotoUI = {"vip_gift",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_40",
			is_local_icon = 1,
		},
		[33]=
		{
			id = 33,
			bannerID = 33,
			isOnOff = 0,
			order = -19,
			gotoUI = {"share_link", "{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/service/service.html\",\"isCircleOfFriends\": \"true\"}",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_39",
			is_local_icon = 1,
		},
		[34]=
		{
			id = 34,
			bannerID = 34,
			isOnOff = 0,
			order = -18,
			gotoUI = {"wys_discount",},
			srartTime = 32515960956,
			endTime = -1,
			imageName = "hall_banner_41",
			is_local_icon = 1,
		},
		[35]=
		{
			id = 35,
			bannerID = 35,
			isOnOff = 0,
			order = 0,
			gotoUI = {"share_link", "{\"type\": 3,\"title\": \"【点我】马上领取免费门票继续>>\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/kefuWX/index.html\",\"isCircleOfFriends\": \"true\"}",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_29",
			is_local_icon = 1,
		},
		[36]=
		{
			id = 36,
			bannerID = 36,
			isOnOff = 0,
			order = -20,
			gotoUI = {"hall_gift_10",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_44.jpg",
			is_local_icon = 1,
		},
		[37]=
		{
			id = 37,
			bannerID = 37,
			isOnOff = 0,
			order = -21,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_999",
			is_local_icon = 0,
		},
		[38]=
		{
			id = 38,
			bannerID = 38,
			isOnOff = 0,
			order = -23,
			gotoUI = {"act_zongzi",},
			srartTime = 1559610000,
			endTime = -1,
			imageName = "hall_banner_45.jpg",
			is_local_icon = 1,
		},
		[39]=
		{
			id = 39,
			bannerID = 39,
			isOnOff = 0,
			order = -25,
			gotoUI = {"game_MiniGame",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_998",
			is_local_icon = 1,
		},
		[40]=
		{
			id = 40,
			bannerID = 40,
			isOnOff = 0,
			order = -24,
			gotoUI = {"hall_gift_73",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_43.jpg",
			is_local_icon = 1,
		},
		[41]=
		{
			id = 41,
			bannerID = 41,
			isOnOff = 0,
			order = -13,
			gotoUI = {"duihuan_shop",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_618",
			is_local_icon = 1,
		},
		[42]=
		{
			id = 42,
			bannerID = 42,
			isOnOff = 0,
			order = -26,
			gotoUI = {"hall_gift",75},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_47",
			is_local_icon = 1,
		},
		[43]=
		{
			id = 43,
			bannerID = 43,
			isOnOff = 0,
			order = -27,
			gotoUI = {"activity_father",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_48",
			is_local_icon = 1,
		},
		[44]=
		{
			id = 44,
			bannerID = 44,
			isOnOff = 0,
			order = -28,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_bxy",
			is_local_icon = 0,
		},
		[45]=
		{
			id = 45,
			bannerID = 45,
			isOnOff = 0,
			order = -29,
			gotoUI = {"hall_gift",101},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_51",
			is_local_icon = 1,
		},
		[46]=
		{
			id = 46,
			bannerID = 46,
			isOnOff = 0,
			order = -30,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_50",
			is_local_icon = 1,
		},
		[47]=
		{
			id = 47,
			bannerID = 47,
			isOnOff = 0,
			condi_key = "shield_huawei",
			order = 1,
			gotoUI = {"share_link","{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/webpages/shareHome.html\",\"isCircleOfFriends\": \"true\"}"},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_52",
			is_local_icon = 1,
		},
		[48]=
		{
			id = 48,
			bannerID = 48,
			isOnOff = 0,
			order = -32,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_54",
			is_local_icon = 1,
		},
		[49]=
		{
			id = 49,
			bannerID = 49,
			isOnOff = 0,
			order = 0,
			gotoUI = {"new_player_activity",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_57",
			is_local_icon = 1,
		},
		[50]=
		{
			id = 50,
			bannerID = 50,
			isOnOff = 0,
			order = -33,
			gotoUI = {"share_activity",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_53",
			is_local_icon = 1,
		},
		[51]=
		{
			id = 51,
			bannerID = 51,
			isOnOff = 0,
			order = -35,
			gotoUI = {"money_center",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_56",
			is_local_icon = 1,
		},
		[52]=
		{
			id = 52,
			bannerID = 52,
			isOnOff = 0,
			order = 0,
			gotoUI = {"duihuan_shop","&444625",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_58",
			is_local_icon = 1,
		},
		[53]=
		{
			id = 53,
			bannerID = 53,
			isOnOff = 0,
			order = -34,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_59",
			is_local_icon = 1,
		},
		[54]=
		{
			id = 54,
			bannerID = 54,
			isOnOff = 0,
			order = -35,
			gotoUI = {"summer_activity",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_60",
			is_local_icon = 1,
		},
		[55]=
		{
			id = 55,
			bannerID = 55,
			isOnOff = 0,
			order = 1,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_64",
			is_local_icon = 1,
		},
		[56]=
		{
			id = 56,
			bannerID = 56,
			isOnOff = 0,
			condi_key = "shield_phone_realname",
			order = 2,
			gotoUI = {"binding_phone",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_61",
			is_local_icon = 1,
		},
		[57]=
		{
			id = 57,
			bannerID = 57,
			isOnOff = 0,
			order = 1,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			endTime = 1565625597,
			imageName = "hall_banner_65",
			is_local_icon = 1,
		},
		[58]=
		{
			id = 58,
			bannerID = 58,
			isOnOff = 0,
			order = 2,
			gotoUI = {"VIP2",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_66",
			is_local_icon = 1,
		},
		[59]=
		{
			id = 59,
			bannerID = 59,
			isOnOff = 0,
			order = 1,
			gotoUI = {"duihuan_shop","&id=785818",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_67",
			is_local_icon = 1,
		},
		[60]=
		{
			id = 60,
			bannerID = 60,
			isOnOff = 0,
			order = 2,
			gotoUI = {"YuYue_activity",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_69",
			is_local_icon = 1,
		},
		[61]=
		{
			id = 61,
			bannerID = 61,
			isOnOff = 0,
			order = -37,
			gotoUI = {"zhounian_share",},
			srartTime = 1566862200,
			endTime = 1567602000,
			imageName = "hall_banner_68",
			is_local_icon = 1,
		},
		[62]=
		{
			id = 62,
			bannerID = 62,
			isOnOff = 0,
			order = -38,
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_72",
			is_local_icon = 1,
		},
		[63]=
		{
			id = 63,
			bannerID = 63,
			isOnOff = 0,
			order = -39,
			gotoUI = {"game_MiniGame",},
			srartTime = 1569283200,
			endTime = 1569859199,
			imageName = "hall_banner_73",
			is_local_icon = 1,
		},
		[64]=
		{
			id = 64,
			bannerID = 64,
			isOnOff = 0,
			order = -40,
			gotoUI = {"game_FishingHall",},
			srartTime = 1571095800,
			endTime = 1571673599,
			imageName = "hall_banner_75",
			is_local_icon = 1,
		},
		[65]=
		{
			id = 65,
			bannerID = 65,
			isOnOff = 0,
			order = -35,
			gotoUI = {"achievement_tg",},
			srartTime = -1,
			endTime = -1,
			imageName = "hall_banner_74",
			is_local_icon = 1,
		},
		[66]=
		{
			id = 66,
			bannerID = 66,
			isOnOff = 0,
			order = -40,
			srartTime = 1572305400,
			endTime = 1572883199,
			imageName = "hall_banner_76",
			is_local_icon = 1,
		},
		[67]=
		{
			id = 67,
			bannerID = 67,
			isOnOff = 0,
			order = 3,
			gotoUI = {"ge_yuyue",},
			srartTime = 1574724600,
			endTime = 1574946000,
			imageName = "banner_077",
			is_local_icon = 1,
		},
		[68]=
		{
			id = 68,
			bannerID = 68,
			isOnOff = 0,
			order = 4,
			srartTime = 1574724600,
			endTime = 1575302399,
			imageName = "banner_079",
			is_local_icon = 1,
		},
		[69]=
		{
			id = 69,
			bannerID = 69,
			isOnOff = 0,
			order = -40,
			gotoUI = {"hall_activity","panel"},
			srartTime = 1575329400,
			endTime = 1575907199,
			imageName = "banner_078",
			is_local_icon = 1,
		},
		[70]=
		{
			id = 70,
			bannerID = 70,
			isOnOff = 0,
			order = 0,
			gotoUI = {"money_center",},
			srartTime = 1576539000,
			endTime = 1577116799,
			imageName = "banner_80",
			is_local_icon = 1,
		},
		[71]=
		{
			id = 71,
			bannerID = 71,
			isOnOff = 0,
			order = 0,
			srartTime = 1579563000,
			endTime = 1580140799,
			imageName = "banner_81",
			is_local_icon = 1,
		},
		[72]=
		{
			id = 72,
			bannerID = 72,
			isOnOff = 0,
			order = -10,
			gotoUI = {"qhb_hall","panel"},
			srartTime = 1579563000,
			endTime = 1580140799,
			imageName = "banner_82",
			is_local_icon = 1,
		},
		[73]=
		{
			id = 73,
			bannerID = 73,
			isOnOff = 0,
			order = 0,
			gotoUI = {"hall_activity","panel"},
			srartTime = 1580167800,
			endTime = 1580572799,
			imageName = "banner_83",
			is_local_icon = 1,
		},
		[74]=
		{
			id = 74,
			bannerID = 74,
			isOnOff = 0,
			order = 0,
			srartTime = 1580270000,
			endTime = 1588328800,
			imageName = "banner_84",
			is_local_icon = 1,
		},
		[75]=
		{
			id = 75,
			bannerID = 75,
			isOnOff = 0,
			order = 0,
			gotoUI = {"hall_activity","panel"},
			srartTime = 1580378400,
			endTime = 1581328800,
			imageName = "banner_85",
			is_local_icon = 1,
		},
		[76]=
		{
			id = 76,
			bannerID = 76,
			isOnOff = 0,
			order = 0,
			gotoUI = {"game_MiniGame",},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_86",
			is_local_icon = 1,
		},
		[77]=
		{
			id = 77,
			bannerID = 77,
			isOnOff = 0,
			condi_key = "water_margin",
			order = -39,
			gotoUI = {"game_MiniGame",},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_87",
			is_local_icon = 1,
		},
		[78]=
		{
			id = 78,
			bannerID = 78,
			isOnOff = 0,
			condi_key = "return_gift",
			order = -39,
			gotoUI = {"sys_cfzx_qflb","panel"},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_89",
			is_local_icon = 1,
		},
		[79]=
		{
			id = 79,
			bannerID = 79,
			isOnOff = 0,
			condi_key = "exchange_one",
			order = -39,
			gotoUI = {"duihuan_shop","&id=46826",},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_91",
			is_local_icon = 1,
		},
		[80]=
		{
			id = 80,
			bannerID = 80,
			isOnOff = 0,
			order = -40,
			gotoUI = {"game_MiniGame",},
			srartTime = 1584401400,
			endTime = 1584979199,
			imageName = "banner_90",
			is_local_icon = 1,
		},
		[81]=
		{
			id = 81,
			bannerID = 81,
			isOnOff = 0,
			order = -41,
			gotoUI = {"act_004_jika","panel"},
			srartTime = 1584401400,
			endTime = 1584979199,
			imageName = "banner_92",
			is_local_icon = 1,
		},
		[82]=
		{
			id = 82,
			bannerID = 82,
			isOnOff = 0,
			condi_key = "npca_challenge",
			order = -41,
			gotoUI = {"act_002_hbfx","banner"},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_93",
			is_local_icon = 1,
		},
		[83]=
		{
			id = 83,
			bannerID = 83,
			isOnOff = 0,
			order = 10,
			gotoUI = {"act_fxlx","panel"},
			srartTime = 1585611000,
			endTime = 1586188799,
			imageName = "banner_94",
			is_local_icon = 1,
		},
		[84]=
		{
			id = 84,
			bannerID = 84,
			isOnOff = 0,
			order = 10,
			gotoUI = {"game_MiniGame",},
			srartTime = 1586302200,
			endTime = 1586793599,
			imageName = "banner_95",
			is_local_icon = 1,
		},
		[85]=
		{
			id = 85,
			bannerID = 85,
			isOnOff = 0,
			order = 10,
			gotoUI = {"game_MiniGame",},
			srartTime = 1586820600,
			endTime = 1587398399,
			imageName = "banner_96",
			is_local_icon = 1,
		},
		[86]=
		{
			id = 86,
			bannerID = 86,
			isOnOff = 0,
			condi_key = "fish_caijin_hongbao",
			order = 10,
			gotoUI = {"game_FishingHall",},
			srartTime = 1587425400,
			endTime = 1588003199,
			imageName = "banner_97",
			is_local_icon = 1,
		},
		[87]=
		{
			id = 87,
			bannerID = 87,
			isOnOff = 0,
			condi_key = "jyddz_type_plat",
			order = 11,
			gotoUI = {"sys_011_CplZh","download"},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_98",
			is_local_icon = 1,
		},
		[88]=
		{
			id = 88,
			bannerID = 88,
			isOnOff = 0,
			order = 10,
			gotoUI = {"money_center",},
			srartTime = -1,
			endTime = -1,
			imageName = "banner_99",
			is_local_icon = 1,
		},
		[89]=
		{
			id = 89,
			bannerID = 89,
			isOnOff = 0,
			order = 10,
			gotoUI = {"act_013_bsyy","panel"},
			srartTime = 1590449400,
			endTime = 1590843599,
			imageName = "banner_100",
			is_local_icon = 1,
		},
		[90]=
		{
			id = 90,
			bannerID = 90,
			isOnOff = 0,
			order = -70,
			gotoUI = {"act_013_dlfl","panel"},
			srartTime = 1590449400,
			endTime = 1590843599,
			imageName = "banner_101",
			is_local_icon = 1,
		},
	},
	upconfig=
	{
		[1]=
		{
			id = 1,
			bannerID = 1,
			isOnOff = 0,
			order = 2,
			gotoUI = "match_hall",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "gy_2",
		},
		[2]=
		{
			id = 2,
			bannerID = 2,
			isOnOff = 0,
			order = 3,
			gotoUI = "citymatch_hall",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "ad_1",
		},
		[3]=
		{
			id = 3,
			bannerID = 3,
			isOnOff = 0,
			order = 4,
			gotoUI = "match_hall",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "gy_3",
		},
		[4]=
		{
			id = 4,
			bannerID = 4,
			isOnOff = 0,
			order = 5,
			gotoUI = "citymatch_hall",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "gy_4",
		},
		[5]=
		{
			id = 5,
			bannerID = 5,
			isOnOff = 0,
			order = 6,
			gotoUI = "free_hall",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "gy_5",
		},
		[6]=
		{
			id = 6,
			bannerID = 6,
			isOnOff = 0,
			order = 1,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			image = "gy_6",
		},
		[7]=
		{
			id = 7,
			bannerID = 7,
			isOnOff = 0,
			order = 0,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
			ct_id = 21,
		},
		[8]=
		{
			id = 8,
			bannerID = 8,
			isOnOff = 0,
			order = -1,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[9]=
		{
			id = 9,
			bannerID = 9,
			isOnOff = 0,
			order = -2,
			gotoUI = "hall_sd",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[10]=
		{
			id = 10,
			bannerID = 10,
			isOnOff = 0,
			order = -3,
			gotoUI = "hall_gift_13",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[11]=
		{
			id = 11,
			bannerID = 11,
			isOnOff = 0,
			order = -4,
			gotoUI = "hall_golden_pig",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[12]=
		{
			id = 12,
			bannerID = 12,
			key = "xrhb",
			isOnOff = 0,
			order = -3,
			gotoUI = {"xrhb","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[13]=
		{
			id = 13,
			bannerID = 13,
			isOnOff = 0,
			order = -5,
			gotoUI = "hall_gift_20",
			shop_id = 20,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[14]=
		{
			id = 14,
			bannerID = 14,
			isOnOff = 0,
			order = -6,
			gotoUI = "hall_gift_21",
			shop_id = 21,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[15]=
		{
			id = 15,
			bannerID = 15,
			isOnOff = 0,
			order = -7,
			gotoUI = "hall_gift_29",
			shop_id = 29,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[16]=
		{
			id = 16,
			bannerID = 16,
			isOnOff = 0,
			order = -7,
			gotoUI = "hall_gift_35",
			shop_id = 35,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[17]=
		{
			id = 17,
			bannerID = 17,
			key = "hall_activity",
			isOnOff = 0,
			order = 4,
			condi_key = "Sign_in_popup_old",
			gotoUI = {"hall_activity","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[18]=
		{
			id = 18,
			bannerID = 20,
			isOnOff = 0,
			order = 0,
			gotoUI = "weekly_card",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[19]=
		{
			id = 19,
			bannerID = 21,
			isOnOff = 0,
			order = -8,
			gotoUI = "hall_gift_10",
			shop_id = 10,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[20]=
		{
			id = 20,
			bannerID = 22,
			isOnOff = 0,
			order = 0,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[21]=
		{
			id = 21,
			bannerID = 23,
			isOnOff = 0,
			order = -8,
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[22]=
		{
			id = 22,
			bannerID = 24,
			isOnOff = 0,
			order = -9,
			gotoUI = "vow_panel",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[23]=
		{
			id = 23,
			bannerID = 25,
			isOnOff = 0,
			order = 0,
			gotoUI = "game_activity_year",
			model = "LoginUp",
			srartTime = 1572305400,
			endTime = 1573487999,
		},
		[24]=
		{
			id = 24,
			bannerID = 26,
			isOnOff = 0,
			order = -101,
			gotoUI = "look_back_1",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[25]=
		{
			id = 25,
			bannerID = 27,
			isOnOff = 0,
			order = -101,
			gotoUI = "welcome_shxxl",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[26]=
		{
			id = 26,
			bannerID = 28,
			key = "jyfl",
			isOnOff = 1,
			order = 0,
			gotoUI = {"jyfl","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[27]=
		{
			id = 27,
			bannerID = 29,
			isOnOff = 0,
			order = 0,
			model = "LoginUp",
			srartTime = 1571095800,
			endTime = 1571673599,
		},
		[28]=
		{
			id = 28,
			bannerID = 30,
			isOnOff = 0,
			order = -103,
			gotoUI = "welcome_tgcj",
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[29]=
		{
			id = 29,
			bannerID = 31,
			isOnOff = 0,
			order = 0,
			model = "LoginUp",
			srartTime = 1571700600,
			endTime = 1572278399,
		},
		[30]=
		{
			id = 30,
			bannerID = 32,
			isOnOff = 0,
			order = -100,
			gotoUI = {"sys_xyjl","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[31]=
		{
			id = 31,
			bannerID = 33,
			isOnOff = 0,
			order = 0,
			model = "LoginUp",
			srartTime = 1574119800,
			endTime = 1574697599,
		},
		[32]=
		{
			id = 32,
			bannerID = 34,
			isOnOff = 1,
			order = -10,
			gotoUI = {"sys_xtsjyd","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[33]=
		{
			id = 33,
			bannerID = 35,
			isOnOff = 0,
			order = 0,
			gotoUI = {"sys_geyl","panel"},
			model = "LoginUp",
			srartTime = 1574724600,
			endTime = 1575302399,
		},
		[34]=
		{
			id = 34,
			bannerID = 36,
			isOnOff = 0,
			order = 0,
			gotoUI = {"sys_xqdzz","panel"},
			model = "LoginUp",
			srartTime = 1575329400,
			endTime = 1575907199,
		},
		[35]=
		{
			id = 35,
			bannerID = 37,
			isOnOff = 0,
			order = 1,
			gotoUI = {"sys_xbyylb","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[36]=
		{
			id = 36,
			bannerID = 38,
			isOnOff = 1,
			order = 1,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"xrhb1","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[37]=
		{
			id = 37,
			bannerID = 39,
			isOnOff = 0,
			order = 100,
			gotoUI = {"act_sdqql","panel"},
			model = "LoginUp",
			srartTime = 1576539000,
			endTime = 1577289599,
		},
		[38]=
		{
			id = 38,
			bannerID = 40,
			isOnOff = 0,
			order = 101,
			gotoUI = {"vip","vip_task_match"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[39]=
		{
			id = 39,
			bannerID = 41,
			isOnOff = 0,
			order = 100,
			gotoUI = {"act_hqyd","panel"},
			model = "LoginUp",
			srartTime = 1577835000,
			endTime = 1578326399,
		},
		[40]=
		{
			id = 40,
			bannerID = 42,
			isOnOff = 0,
			order = 100,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1578353400,
			endTime = 1578931199,
		},
		[41]=
		{
			id = 41,
			bannerID = 43,
			isOnOff = 0,
			order = 100,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1578958200,
			endTime = 1581350399,
		},
		[42]=
		{
			id = 42,
			bannerID = 44,
			isOnOff = 0,
			order = 101,
			gotoUI = {"act_fxlx","panel"},
			model = "LoginUp",
			srartTime = 1585611000,
			endTime = 1586188799,
		},
		[43]=
		{
			id = 43,
			bannerID = 45,
			isOnOff = 1,
			order = 3,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"act_xrqtl","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[44]=
		{
			id = 44,
			bannerID = 46,
			isOnOff = 0,
			order = 101,
			gotoUI = {"act_ltqf","panel"},
			model = "LoginUp",
			srartTime = 1581982200,
			endTime = 1582559999,
		},
		[45]=
		{
			id = 45,
			bannerID = 47,
			isOnOff = 0,
			order = 101,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1582587000,
			endTime = 1583164799,
		},
		[46]=
		{
			id = 46,
			bannerID = 48,
			isOnOff = 0,
			order = 101,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1583191800,
			endTime = 1583769599,
		},
		[47]=
		{
			id = 47,
			bannerID = 49,
			isOnOff = 0,
			order = 101,
			gotoUI = {"act_003_zslw","panel"},
			model = "LoginUp",
			srartTime = 1583796600,
			endTime = 1584374399,
		},
		[48]=
		{
			id = 48,
			bannerID = 50,
			isOnOff = 0,
			order = 101,
			gotoUI = {"act_003_zshm","panel"},
			model = "LoginUp",
			srartTime = 1583796600,
			endTime = 1584374399,
		},
		[49]=
		{
			id = 49,
			bannerID = 51,
			isOnOff = 0,
			order = 5,
			condi_key = "Sign_in_popup_old",
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1584401400,
			endTime = 1584979199,
		},
		[50]=
		{
			id = 50,
			bannerID = 52,
			isOnOff = 0,
			order = 10,
			gotoUI = {"act_004_lylb","panel"},
			model = "LoginUp",
			srartTime = 1587425400,
			endTime = 1588003199,
		},
		[51]=
		{
			id = 51,
			bannerID = 53,
			isOnOff = 0,
			order = 100,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1585006200,
			endTime = 1585583999,
		},
		[52]=
		{
			id = 52,
			bannerID = 54,
			isOnOff = 0,
			order = 10,
			gotoUI = {"act_005_hgjx","panel"},
			model = "LoginUp",
			srartTime = 1585006200,
			endTime = -1,
		},
		[53]=
		{
			id = 53,
			bannerID = 55,
			isOnOff = 0,
			order = 101,
			gotoUI = {"act_002_hbfx","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[54]=
		{
			id = 54,
			bannerID = 56,
			isOnOff = 0,
			order = 100,
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1585611000,
			endTime = 1586188799,
		},
		[55]=
		{
			id = 55,
			bannerID = 57,
			isOnOff = 0,
			order = 100,
			condi_key = "box_exchange_ckt",
			gotoUI = {"act_007_ckt","panel"},
			model = "LoginUp",
			srartTime = 1586215800,
			endTime = 1586793599,
		},
		[56]=
		{
			id = 56,
			bannerID = 58,
			isOnOff = 0,
			order = 100,
			condi_key = "crazy_rebate_fkfl",
			gotoUI = {"act_007_fkfl","panel"},
			model = "LoginUp",
			srartTime = 1586215800,
			endTime = 1586793599,
		},
		[57]=
		{
			id = 57,
			bannerID = 59,
			isOnOff = 0,
			order = 100,
			condi_key = "Act_008LGFLManager",
			gotoUI = {"act_008_lgfl","panel"},
			model = "LoginUp",
			srartTime = 1586820600,
			endTime = 1587398399,
		},
		[58]=
		{
			id = 58,
			bannerID = 60,
			isOnOff = 0,
			order = 110,
			condi_key = "actp_buy_gift_bag_10190",
			gotoUI = {"act_008_mflb","panel"},
			model = "LoginUp",
			srartTime = 1589844600,
			endTime = 1590422399,
		},
		[59]=
		{
			id = 59,
			bannerID = 61,
			isOnOff = 0,
			order = 100,
			condi_key = "lucky_egg_popup",
			gotoUI = {"act_014_xycd","panel"},
			model = "LoginUp",
			srartTime = 1591054200,
			endTime = 1591631999,
		},
		[60]=
		{
			id = 60,
			bannerID = 62,
			isOnOff = 0,
			order = 100,
			gotoUI = {"vip","notice"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[61]=
		{
			id = 61,
			bannerID = 63,
			isOnOff = 0,
			order = 99,
			gotoUI = {"act_002_hbfx","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
		[62]=
		{
			id = 62,
			bannerID = 64,
			isOnOff = 0,
			order = 100,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1588030200,
			endTime = 1588607999,
		},
		[63]=
		{
			id = 63,
			bannerID = 65,
			isOnOff = 0,
			order = 100,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"act_010_mqjth","panel"},
			model = "LoginUp",
			srartTime = 1588608000,
			endTime = 1589212799,
		},
		[64]=
		{
			id = 64,
			bannerID = 66,
			isOnOff = 0,
			order = 100,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1589239800,
			endTime = 1589817599,
		},
		[65]=
		{
			id = 65,
			bannerID = 67,
			isOnOff = 0,
			order = 100,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1589844600,
			endTime = 1590422399,
		},
		[66]=
		{
			id = 66,
			bannerID = 68,
			isOnOff = 0,
			order = 100,
			condi_key = "Sign_in_popup_new",
			gotoUI = {"sys_act_base","panel"},
			model = "LoginUp",
			srartTime = 1590449400,
			endTime = 1591027199,
		},
		[67]=
		{
			id = 67,
			bannerID = 69,
			isOnOff = 0,
			order = 100,
			condi_key = "actp_buy_gift_bag_class_crazy_calculate",
			gotoUI = {"act_014_jhs","panel"},
			model = "LoginUp",
			srartTime = 1591054200,
			endTime = 1591631999,
		},
		[68]=
		{
			id = 68,
			bannerID = 70,
			isOnOff = 0,
			order = -100,
			gotoUI = {"sys_binding_phone_award","panel"},
			model = "LoginUp",
			srartTime = -1,
			endTime = -1,
		},
	},
}