return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "gun_barrel_1",
			type_colour = 1,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p0",
			order = 1,
			name = "小钢炮",
			desc = "激光炮：直线方向释放激光，有几率捕获激光所发射范围内的任意鱼类",
			desc_get = "系统赠送",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "gun_barrel_2",
			type_colour = 1,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p1",
			order = 2,
			name = "雷霆幻影",
			desc = "激光炮：直线方向释放激光，有几率捕获激光所发射范围内的任意鱼类",
			desc_get = "1万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费1万福利券购买【雷霆幻影】3天使用权",
			buy_anniu_hint = "1万福利券购买",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "gun_barrel_3",
			type_colour = 1,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p2",
			order = 3,
			name = "闪耀风暴",
			desc = "激光炮：直线方向释放激光，有几率捕获激光所发射范围内的任意鱼类",
			desc_get = "2万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费2万福利券购买【闪耀风暴】3天使用权",
			buy_anniu_hint = "2万福利券购买",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "gun_barrel_4",
			type_colour = 2,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p3",
			order = 4,
			name = "金币使者",
			desc = "穿透弹：发射一发穿透弹，可捕获同移动线上的任意鱼类",
			desc_get = "5万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费5万福利券购买【金币使者】3天使用权",
			buy_anniu_hint = "5万福利券购买",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "gun_barrel_5",
			type_colour = 2,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p4",
			order = 5,
			name = "核能风暴",
			desc = "核能炮：在屏幕中间释放一颗小型原子弹，随机捕获炸弹范围内的任意鱼类",
			desc_get = "10万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费10万福利券购买【核能风暴】3天使用权",
			buy_anniu_hint = "10万福利券购买",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "gun_barrel_6",
			type_colour = 3,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p5",
			order = 6,
			name = "死灵之光",
			desc = "死灵之光：攻击指定点，死光随机捕获周围其鱼类\n被动效果：提高捕获奖金鱼后获得高倍的几率",
			desc_get = "15万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费15万福利券购买【死灵之光】3天使用权",
			buy_anniu_hint = "15万福利券购买",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "gun_barrel_7",
			type_colour = 3,
			type = 1,
			is_local_icon = 1,
			image = "3dby_icon_p6",
			order = 7,
			name = "神龙之力",
			desc = "神龙杀：瞬间提高子弹250%的杀伤力\n被动效果：提高击杀龙王的概率",
			desc_get = "30万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费30万福利券购买【神龙之力】3天使用权",
			buy_anniu_hint = "30万福利券购买",
		},
		[8]=
		{
			id = 8,
			item_id = 1,
			item_key = "gun_bed_1",
			type_colour = 1,
			type = 2,
			is_local_icon = 1,
			image = "3dby_icon_pt_1",
			order = 1,
			name = "青柠",
			desc = "系统赠送基础炮座",
			desc_get = "系统赠送",
		},
		[9]=
		{
			id = 9,
			item_id = 2,
			item_key = "gun_bed_2",
			type_colour = 1,
			type = 2,
			is_local_icon = 1,
			image = "3dby_icon_xy_1",
			order = 2,
			name = "绿芒",
			desc = "限制：稀有品质以上炮台可用",
			desc_get = "2万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费2万福利券购买【绿芒】3天使用权",
			buy_anniu_hint = "2万福利券购买",
		},
		[10]=
		{
			id = 10,
			item_id = 3,
			item_key = "gun_bed_3",
			type_colour = 2,
			type = 2,
			is_local_icon = 1,
			image = "3dby_icon_ss_1",
			order = 3,
			name = "寒霜",
			desc = "装备后效果：捕鱼命中率提升千分之二\n限制：史诗品质以上炮台可用",
			desc_get = "5万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费5万福利券购买【寒霜】3天使用权",
			buy_anniu_hint = "5万福利券购买",
		},
		[11]=
		{
			id = 11,
			item_id = 4,
			item_key = "gun_bed_4",
			type_colour = 3,
			type = 2,
			is_local_icon = 1,
			image = "3dby_icon_cs_1",
			order = 4,
			name = "金焰",
			desc = "装备后效果：捕鱼子弹威力提高千分之五\n限制：传说品质以上炮台可用",
			desc_get = "10万福利券购买",
			use_parm = {"shop_bay","item",},
			buy_hint = "是否花费10万福利券购买【金焰】3天使用权",
			buy_anniu_hint = "10万福利券购买",
		},
	},
}