return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "cash",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_xj",
			name = "奖金",
			desc = "微信红包奖金",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "jipaiqi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			is_show_bag = 1,
			order = 2,
			name = "记牌器",
			desc = "记牌器",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "diamond",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_zs_30y",
			name = "钻石",
			desc = "钻石",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "jing_bi",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_jb_15y",
			name = "金币",
			desc = "金币",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "vip",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			name = "VIP",
			desc = "vip",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "shop_gold_sum",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_flq2",
			name = "福利券",
			desc = "福利券",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "shop_gold_sum_limit",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_flq1",
			name = "福利额度",
			desc = "每日福利券额度",
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			item_key = "room_card",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_rc",
			is_show_bag = 1,
			order = 21,
			name = "房卡",
			desc = "创建房卡游戏时使用",
			use_parm = {"roomcard_hall",},
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			item_key = "frame1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz1",
			name = "Lv.10",
			desc = "等级头像框",
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			item_key = "frame2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz2",
			name = "Lv.20",
			desc = "等级头像框",
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			item_key = "frame3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz3",
			name = "Lv.30",
			desc = "等级头像框",
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			item_key = "frame4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz4",
			name = "Lv.40",
			desc = "等级头像框",
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			item_key = "frame5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz5",
			name = "Lv.50",
			desc = "等级头像框",
		},
		[14]=
		{
			id = 14,
			item_id = 14,
			item_key = "frame6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz6",
			name = "Lv.60",
			desc = "等级头像框",
		},
		[15]=
		{
			id = 15,
			item_id = 15,
			item_key = "frame7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz7",
			name = "Lv.70",
			desc = "等级头像框",
		},
		[16]=
		{
			id = 16,
			item_id = 16,
			item_key = "frame8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz8",
			name = "Lv.80",
			desc = "等级头像框",
		},
		[17]=
		{
			id = 17,
			item_id = 17,
			item_key = "frame9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz9",
			name = "Lv.90",
			desc = "等级头像框",
		},
		[18]=
		{
			id = 18,
			item_id = 18,
			item_key = "emoticon1",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_water",
			name = "泼水表情",
			desc = "高级互动表情",
		},
		[19]=
		{
			id = 19,
			item_id = 19,
			item_key = "emoticon2",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_guo",
			name = "平底锅表情",
			desc = "高级互动表情",
		},
		[20]=
		{
			id = 20,
			item_id = 20,
			item_key = "emoticon3",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_th",
			name = "戴墨镜表情",
			desc = "高级互动表情",
		},
		[21]=
		{
			id = 21,
			item_id = 21,
			item_key = "emoticon4",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_pig",
			name = "变猪表情",
			desc = "高级互动表情",
		},
		[22]=
		{
			id = 22,
			item_id = 22,
			item_key = "chat",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhk",
			name = "方言特色短语",
			desc = "高级快捷短语",
		},
		[23]=
		{
			id = 23,
			item_id = 23,
			item_key = "broadcast",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gb",
			name = "登录全服广播",
			desc = "登录时全服播放欢迎广播",
		},
		[24]=
		{
			id = 24,
			item_id = 24,
			item_key = "jipaiqi_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			name = "免费记牌器",
			desc = "免费使用记牌器",
		},
		[25]=
		{
			id = 25,
			item_id = 101,
			item_key = "match_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_hxs",
			is_show_bag = 0,
			order = -1,
			name = "比赛券",
			desc = "用于参加比赛场的比赛",
		},
		[26]=
		{
			id = 26,
			item_id = 25,
			item_key = "frame10",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz10",
			name = "Lv.100",
			desc = "等级头像框",
		},
		[27]=
		{
			id = 27,
			item_id = 26,
			item_key = "prop_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "比赛场门票",
			desc = "可用于参加所有锦标赛",
			use_parm = {"match_hall","hbs",},
		},
		[28]=
		{
			id = 28,
			item_id = 27,
			item_key = "prop_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 4,
			name = "千元赛门票",
			desc = "用于报名千元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[29]=
		{
			id = 29,
			item_id = 28,
			item_key = "real_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "黑锅",
			desc = "黑锅",
			real_object = 1,
		},
		[30]=
		{
			id = 30,
			item_id = 29,
			item_key = "prop_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz1",
			is_show_bag = 1,
			order = 17,
			name = "玩具锤",
			desc = "内部充气的玩具锤，小朋友们的最爱",
			use_parm = {"hall_egg","prop_hammer_1"},
		},
		[31]=
		{
			id = 31,
			item_id = 30,
			item_key = "prop_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 1,
			order = 18,
			name = "木锤",
			desc = "看起来似乎不太经用的木头锤子",
			use_parm = {"hall_egg","prop_hammer_2"},
		},
		[32]=
		{
			id = 32,
			item_id = 31,
			item_key = "prop_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 1,
			order = 19,
			name = "银锤",
			desc = "虽然看起来挺像，不过这可不是那把能放电的锤子",
			use_parm = {"hall_egg","prop_hammer_3"},
		},
		[33]=
		{
			id = 33,
			item_id = 32,
			item_key = "prop_hammer_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 1,
			order = 20,
			name = "金锤",
			desc = "听说下雨天金锤和金蛋更配哦！",
			use_parm = {"hall_egg","prop_hammer_4"},
		},
		[34]=
		{
			id = 34,
			item_id = 33,
			item_key = "expression_54",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			name = "666表情",
			desc = "666表情",
		},
		[35]=
		{
			id = 35,
			item_id = 34,
			item_key = "prop_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_wys",
			is_show_bag = 1,
			order = 3,
			name = "万元赛门票",
			desc = "用于报名万元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[36]=
		{
			id = 36,
			item_id = 35,
			item_key = "prop_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jyhd",
			is_show_bag = 1,
			order = 5,
			name = "企业赛门票",
			desc = "用于报名企业赛",
			use_parm = {"match_hall","gms",},
		},
		[37]=
		{
			id = 37,
			item_id = 36,
			item_key = "prop_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_yys",
			is_show_bag = 1,
			order = 10,
			name = "一元赛门票",
			desc = "用于报名一元赛",
			use_parm = {"match_hall","hbs",},
		},
		[38]=
		{
			id = 38,
			item_id = 37,
			item_key = "fake1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyywy",
			is_show_bag = 0,
			name = "千元第一",
			desc = "第一",
		},
		[39]=
		{
			id = 39,
			item_id = 38,
			item_key = "fake2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money300",
			is_show_bag = 0,
			name = "千元第二",
			desc = "第二",
		},
		[40]=
		{
			id = 40,
			item_id = 39,
			item_key = "fake3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money10000",
			is_show_bag = 0,
			name = "千元第三",
			desc = "第三",
		},
		[41]=
		{
			id = 41,
			item_id = 40,
			item_key = "obj_qianyuansai_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 1,
			name = "千元赛门票",
			desc = "千元赛限时门票，限7天内使用！",
			desc_extra = "<size=40><color=#FF0000FF>限时</color><color=#FFF06E>门票，有效时间</color><color=#FF0000FF>7天</color></size>",
			use_parm = {"match_hall","gms",},
		},
		[42]=
		{
			id = 42,
			item_id = 41,
			item_key = "prop_5y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_5ys",
			is_show_bag = 1,
			order = 9,
			name = "五元赛门票",
			desc = "用于报名五元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[43]=
		{
			id = 43,
			item_id = 42,
			item_key = "prop_20y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_20ys",
			is_show_bag = 1,
			order = 8,
			name = "二十元赛门票",
			desc = "用于报名二十元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[44]=
		{
			id = 44,
			item_id = 43,
			item_key = "prop_100y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 6,
			name = "百元赛门票",
			desc = "用于报名一百元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[45]=
		{
			id = 45,
			item_id = 44,
			item_key = "prop_50y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 7,
			name = "五十元赛门票",
			desc = "用于报名五十元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[46]=
		{
			id = 46,
			item_id = 45,
			item_key = "fish_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_yb",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼币",
			desc = "用于捕鱼消耗",
		},
		[47]=
		{
			id = 47,
			item_id = 46,
			item_key = "prop_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_bd",
			is_show_bag = 0,
			order = 16,
			name = "冰冻",
			desc = "冰冻全场鱼",
		},
		[48]=
		{
			id = 48,
			item_id = 47,
			item_key = "prop_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 0,
			order = 15,
			name = "锁定",
			desc = "锁定攻击鱼",
		},
		[49]=
		{
			id = 49,
			item_id = 48,
			item_key = "expression_57",
			lose_time = -1,
			is_local_icon = 1,
			image = "pay_icon_pig",
			name = "猪头表情",
			desc = "猪头表情",
		},
		[50]=
		{
			id = 50,
			item_id = 49,
			item_key = "prop_50hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 11,
			name = "五十话费赛门票",
			desc = "用于报名50元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[51]=
		{
			id = 51,
			item_id = 50,
			item_key = "prop_100hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 10,
			name = "一百话费赛门票",
			desc = "用于报名100元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[52]=
		{
			id = 52,
			item_id = 51,
			item_key = "prop_zongzi",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			is_show_bag = 0,
			order = 1,
			name = "粽子",
			desc = "捕鱼收集粽子赢大奖",
		},
		[53]=
		{
			id = 53,
			item_id = 52,
			item_key = "obj_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_danmf2",
			is_show_bag = 1,
			order = 12,
			name = "免费时刻",
			desc = "触发免费时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[54]=
		{
			id = 54,
			item_id = 53,
			item_key = "obj_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_sbsk",
			is_show_bag = 1,
			order = 14,
			name = "双倍时刻",
			desc = "触发双倍时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[55]=
		{
			id = 55,
			item_id = 54,
			item_key = "obj_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 13,
			name = "超级火力",
			desc = "触发超级火力",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[56]=
		{
			id = 56,
			item_id = 55,
			item_key = "prop_6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_mxyqh",
			is_show_bag = 1,
			order = 6,
			name = "明星大奖赛门票",
			desc = "明星大奖赛门票",
			use_parm = {"match_hall","mxb",},
		},
		[57]=
		{
			id = 57,
			item_id = 56,
			item_key = "obj_fish_super_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 0,
			name = "超级全屏炸弹",
			desc = "毁天灭地，却无辐射残留",
			tag = 6,
		},
		[58]=
		{
			id = 58,
			item_id = 57,
			item_key = "obj_fish_secondary_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 2,
			name = "全屏炸弹",
			desc = "再也不用担心炸弹范围太小了",
			tag = 6,
		},
		[59]=
		{
			id = 59,
			item_id = 58,
			item_key = "obj_fish_super_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dsd",
			is_show_bag = 1,
			order = 1,
			name = "超级全屏闪电",
			desc = "电闪雷鸣，鱼儿无所遁形",
			tag = 6,
		},
		[60]=
		{
			id = 60,
			item_id = 59,
			item_key = "obj_fish_secondary_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xsd",
			is_show_bag = 1,
			order = 3,
			name = "全屏闪电",
			desc = "让我看看是谁在电鱼！",
			tag = 6,
		},
		[61]=
		{
			id = 61,
			item_id = 60,
			item_key = "obj_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 15,
			name = "锁定（比赛专用）",
			desc = "锁定攻击鱼",
			tag = 6,
		},
		[62]=
		{
			id = 62,
			item_id = 61,
			item_key = "prop_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼比赛券",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[63]=
		{
			id = 63,
			item_id = 62,
			item_key = "obj_qys_match_revive_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_fh2",
			is_show_bag = 1,
			order = 21,
			name = "千元赛复活门票",
			desc = "用于千元赛复活",
		},
		[64]=
		{
			id = 64,
			item_id = 63,
			item_key = "prop_7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_znq",
			is_show_bag = 1,
			order = 22,
			name = "周年感恩赛门票",
			desc = "该门票可用于2019年9月15日20点30分参加周年感恩赛",
			use_parm = {"match_hall","ges"},
		},
		[65]=
		{
			id = 65,
			item_id = 64,
			item_key = "fake4",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp1",
			is_show_bag = 0,
			order = 23,
			name = "10斤长谷子大米",
			desc = "感恩赛奖励",
		},
		[66]=
		{
			id = 66,
			item_id = 65,
			item_key = "fake5",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp4",
			is_show_bag = 0,
			order = 24,
			name = "金条*5g",
			desc = "感恩赛第一名奖励",
		},
		[67]=
		{
			id = 67,
			item_id = 66,
			item_key = "fake6",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp3",
			is_show_bag = 0,
			order = 25,
			name = "金条*2g",
			desc = "感恩赛第二名奖励",
		},
		[68]=
		{
			id = 68,
			item_id = 67,
			item_key = "fake7",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp2",
			is_show_bag = 0,
			order = 26,
			name = "金条*1g",
			desc = "感恩赛第三名奖励",
		},
		[69]=
		{
			id = 69,
			item_id = 68,
			item_key = "obj_fish_match",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼比赛券（限时）",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[70]=
		{
			id = 70,
			item_id = 69,
			item_key = "prop_jinianbi",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_jnb",
			is_show_bag = 1,
			order = 1,
			name = "纪念币",
			desc = "周年活动纪念币",
		},
		[71]=
		{
			id = 71,
			item_id = 70,
			item_key = "prop_znq_dhq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 1,
			order = 1,
			name = "抽奖券",
			desc = "周年庆活动专用",
		},
		[72]=
		{
			id = 72,
			item_id = 71,
			item_key = "obj_fish_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bytx_zt",
			is_show_bag = 1,
			order = 1,
			name = "钻头弹",
			desc = "威力强大的钻头弹，一发惊天动地。可在捕鱼场中使用。",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[73]=
		{
			id = 73,
			item_id = 72,
			item_key = "obj_fish_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_ctgd",
			is_show_bag = 1,
			order = 1,
			name = "穿透钢弹",
			desc = "可以穿透目标鱼的子弹",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[74]=
		{
			id = 74,
			item_id = 73,
			item_key = "obj_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_shendeng",
			is_show_bag = 1,
			order = 1,
			name = "神灯",
			desc = "擦亮神灯，就会召唤黄金鱼",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[75]=
		{
			id = 75,
			item_id = 74,
			item_key = "sczd_achievement",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cjd",
			is_show_bag = 0,
			order = 1,
			name = "成就点",
			desc = "参与推广活动，获得成就点",
			tag = 2,
		},
		[76]=
		{
			id = 76,
			item_id = 75,
			item_key = "prop_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_jbbx",
			is_show_bag = 1,
			order = -100,
			name = "双11宝箱",
			desc = "宝箱可随机开出1000-15万金币。使用时间：2019年11月5日7:30至2019年11月11日23:59:59",
			use_parm = {"open_box",},
		},
		[77]=
		{
			id = 77,
			item_id = 76,
			item_key = "prop_11_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq2",
			is_show_bag = 1,
			order = 1,
			name = "双11抽奖券",
			desc = "可在双11抽大奖活动中使用此券进行抽奖。",
		},
		[78]=
		{
			id = 78,
			item_id = 78,
			item_key = "fake8",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift67",
			is_show_bag = 0,
			order = 23,
			name = "敦煌有机红枣",
			desc = "感恩赛奖励",
		},
		[79]=
		{
			id = 79,
			item_id = 79,
			item_key = "prop_xycj_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 1,
			order = 23,
			name = "抽奖券",
			desc = "用于红包大转盘的抽奖",
			use_parm = {"sys_flqcj","panel",1},
		},
		[80]=
		{
			id = 80,
			item_id = 80,
			item_key = "prop_box_stxt_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx1",
			is_show_bag = 1,
			order = 24,
			name = "免费激励宝箱",
			desc = "师傅给与徒弟的免费激励宝箱可随机开出1000-15万金币。",
			use_parm = {"open_box","prop_box_stxt_free"},
			box_id = 4,
		},
		[81]=
		{
			id = 81,
			item_id = 81,
			item_key = "prop_box_stxt_small",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx2",
			is_show_bag = 1,
			order = 25,
			name = "激励宝箱",
			desc = "师傅给与徒弟的激励宝箱可随机开出1000-15万金币。",
			use_parm = {"open_box","prop_box_stxt_small"},
			box_id = 5,
		},
		[82]=
		{
			id = 82,
			item_id = 82,
			item_key = "prop_gns_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 1,
			order = 22,
			name = "月末福利赛门票",
			desc = "该门票可用于2020年2月29日21点30分参加月末福利赛",
		},
		[83]=
		{
			id = 83,
			item_id = 83,
			item_key = "fake9",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift91_gm",
			is_show_bag = 0,
			order = 23,
			name = "鹌鹑蛋面条",
			desc = "年末回馈赛奖励",
		},
		[84]=
		{
			id = 84,
			item_id = 84,
			item_key = "prop_new_year_word_kuai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_1",
			is_show_bag = 1,
			order = 24,
			name = "快",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[85]=
		{
			id = 85,
			item_id = 85,
			item_key = "prop_new_year_word_le",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_2",
			is_show_bag = 1,
			order = 25,
			name = "乐",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[86]=
		{
			id = 86,
			item_id = 86,
			item_key = "prop_new_year_word_xin",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_3",
			is_show_bag = 1,
			order = 26,
			name = "新",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[87]=
		{
			id = 87,
			item_id = 87,
			item_key = "prop_new_year_word_shu",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_4",
			is_show_bag = 1,
			order = 27,
			name = "鼠",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[88]=
		{
			id = 88,
			item_id = 88,
			item_key = "prop_new_year_word_cai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_5",
			is_show_bag = 1,
			order = 28,
			name = "财",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[89]=
		{
			id = 89,
			item_id = 89,
			item_key = "prop_new_year_word_nian",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_6",
			is_show_bag = 1,
			order = 29,
			name = "年",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[90]=
		{
			id = 90,
			item_id = 90,
			item_key = "prop_new_year_word_yuan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_7",
			is_show_bag = 1,
			order = 30,
			name = "元",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[91]=
		{
			id = 91,
			item_id = 91,
			item_key = "prop_new_year_word_fa",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_8",
			is_show_bag = 1,
			order = 31,
			name = "發",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[92]=
		{
			id = 92,
			item_id = 92,
			item_key = "prop_new_year_word_dan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_9",
			is_show_bag = 1,
			order = 32,
			name = "旦",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[93]=
		{
			id = 93,
			item_id = 93,
			item_key = "prop_box_click_like",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_dzyl",
			is_show_bag = 1,
			order = -100,
			name = "点赞宝箱",
			desc = "2020年1月24日-2月8日可开启宝箱，最多可获得10万金币。",
			use_parm = {"open_box","prop_box_click_like"},
			box_id = 12,
			beginTime = 1579795200,
			endTime = 1581177599,
		},
		[94]=
		{
			id = 94,
			item_id = 94,
			item_key = "fake10",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift128_xsy",
			is_show_bag = 0,
			order = 33,
			name = "洗手液",
			desc = "月末福利赛预约奖励",
		},
		[95]=
		{
			id = 95,
			item_id = 95,
			item_key = "fake11",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift129_jly",
			is_show_bag = 0,
			order = 34,
			name = "食用油",
			desc = "月末福利赛预约奖励",
		},
		[96]=
		{
			id = 96,
			item_id = 96,
			item_key = "prop_web_chip_huafei",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_hfsp",
			is_show_bag = 1,
			order = 35,
			name = "话费碎片",
			desc = "累计一定数量可以兑换话费",
		},
		[97]=
		{
			id = 97,
			item_id = 97,
			item_key = "obj_fish_3d_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_danmf2",
			is_show_bag = 1,
			order = 36,
			name = "免费子弹",
			desc = "免费子弹",
			tag = 9,
		},
		[98]=
		{
			id = 98,
			item_id = 98,
			item_key = "obj_fish_3d_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 37,
			name = "超级火力",
			desc = "超级火力",
			tag = 9,
		},
		[99]=
		{
			id = 99,
			item_id = 99,
			item_key = "obj_fish_3d_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_sbsk",
			is_show_bag = 1,
			order = 38,
			name = "双倍时刻",
			desc = "双倍时刻",
			tag = 9,
		},
		[100]=
		{
			id = 100,
			item_id = 100,
			item_key = "obj_fish_3d_quick_shoot",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_dan_bs08",
			is_show_bag = 1,
			order = 39,
			name = "超速子弹",
			desc = "超速子弹",
			tag = 9,
		},
		[101]=
		{
			id = 101,
			item_id = 101,
			item_key = "obj_fish_3d_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_zt",
			is_show_bag = 1,
			order = 40,
			name = "钻头弹",
			desc = "钻头弹",
			tag = 9,
		},
		[102]=
		{
			id = 102,
			item_id = 102,
			item_key = "obj_fish_3d_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_ctgd",
			is_show_bag = 1,
			order = 41,
			name = "穿透子弹",
			desc = "穿透子弹",
			tag = 9,
		},
		[103]=
		{
			id = 103,
			item_id = 103,
			item_key = "prop_3d_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_zh",
			is_show_bag = 1,
			order = 42,
			name = "召唤",
			desc = "召唤彩金鱼",
			tag = 9,
		},
		[104]=
		{
			id = 104,
			item_id = 104,
			item_key = "obj_fish_3d_time_free_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 43,
			name = "免费超级火力",
			desc = "免费超级火力",
			tag = 9,
		},
		[105]=
		{
			id = 105,
			item_id = 105,
			item_key = "obj_fish_3d_laser_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_jg_skill",
			is_show_bag = 1,
			order = 44,
			name = "激光炮",
			desc = "激光炮",
			tag = 9,
		},
		[106]=
		{
			id = 106,
			item_id = 106,
			item_key = "prop_3d_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_bd",
			is_show_bag = 1,
			order = 32,
			name = "冰冻",
			desc = "冰冻全场鱼",
			tag = 9,
		},
		[107]=
		{
			id = 107,
			item_id = 107,
			item_key = "prop_3d_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_sd",
			is_show_bag = 1,
			order = 33,
			name = "锁定",
			desc = "锁定攻击鱼",
			tag = 9,
		},
		[108]=
		{
			id = 108,
			item_id = 108,
			item_key = "task_13000",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_hytb",
			is_show_bag = 1,
			order = 33,
			name = "活跃度",
			desc = "日常活跃",
		},
		[109]=
		{
			id = 109,
			item_id = 109,
			item_key = "prop_tiny_game_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_yxb_2",
			is_show_bag = 1,
			order = 34,
			name = "小游戏币",
			desc = "用于小游戏消耗",
			use_parm = {"game_MiniGame",},
		},
		[110]=
		{
			id = 110,
			item_id = 110,
			item_key = "prop_fish_secondary_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-浅水湾",
			desc = "原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[111]=
		{
			id = 111,
			item_id = 111,
			item_key = "prop_fish_super_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-浅水湾",
			desc = "超级原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[112]=
		{
			id = 112,
			item_id = 112,
			item_key = "prop_fish_secondary_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-深海寻宝",
			desc = "原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[113]=
		{
			id = 113,
			item_id = 113,
			item_key = "prop_fish_super_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-深海寻宝",
			desc = "超级原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[114]=
		{
			id = 114,
			item_id = 114,
			item_key = "prop_fish_secondary_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 1,
			name = "原子弹-地底遗迹",
			desc = "原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[115]=
		{
			id = 115,
			item_id = 115,
			item_key = "prop_fish_super_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 1,
			name = "超级原子弹-地底遗迹",
			desc = "超级原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[116]=
		{
			id = 116,
			item_id = 116,
			item_key = "prop_mfcjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 33,
			name = "免费抽奖券",
			desc = "免费抽奖券",
		},
		[117]=
		{
			id = 117,
			item_id = 117,
			item_key = "prop_guess_apple_bet_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_shui",
			is_show_bag = 0,
			order = 36,
			name = "水滴",
			desc = "用于苹果大战种植",
		},
		[118]=
		{
			id = 118,
			item_id = 118,
			item_key = "prop_guess_apple_bet_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_yg",
			is_show_bag = 0,
			order = 37,
			name = "太阳",
			desc = "用于苹果大战种植",
		},
		[119]=
		{
			id = 119,
			item_id = 119,
			item_key = "prop_guess_apple_bet_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_cc",
			is_show_bag = 0,
			order = 38,
			name = "铲子",
			desc = "用于苹果大战种植",
		},
		[120]=
		{
			id = 120,
			item_id = 120,
			item_key = "prop_guess_apple_bet_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_sc",
			is_show_bag = 0,
			order = 39,
			name = "除虫剂",
			desc = "用于苹果大战种植",
		},
		[121]=
		{
			id = 121,
			item_id = 121,
			item_key = "prop_guess_apple_bet_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_fl",
			is_show_bag = 0,
			order = 40,
			name = "肥料",
			desc = "用于苹果大战种植",
		},
		[122]=
		{
			id = 122,
			item_id = 122,
			item_key = "prop_fishbowl_fish_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_yu28",
			is_show_bag = 0,
			order = 38,
			name = "鱼苗",
			desc = "用于水族馆",
		},
		[123]=
		{
			id = 123,
			item_id = 123,
			item_key = "prop_fishbowl_fodder",
			lose_time = -1,
			is_local_icon = 1,
			image = "szg_icon_wy",
			is_show_bag = 1,
			order = 39,
			name = "鱼饲料",
			desc = "用于水族馆",
		},
		[124]=
		{
			id = 124,
			item_id = 124,
			item_key = "prop_fishbowl_glass",
			lose_time = -1,
			is_local_icon = 1,
			image = "szg_icon_sj",
			is_show_bag = 1,
			order = 40,
			name = "鱼缸材料",
			desc = "用于水族馆",
		},
	},
}