return {
	config=
	{
		[1]=
		{
			id = 1,
			game_id = 1,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {2500,},
			award_icon = {"ty_icon_flq1",},
		},
		[2]=
		{
			id = 2,
			game_id = 1,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {1500,},
			award_icon = {"ty_icon_flq1",},
		},
		[3]=
		{
			id = 3,
			game_id = 1,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {1000,},
			award_icon = {"ty_icon_flq1",},
		},
		[4]=
		{
			id = 4,
			game_id = 1,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {700,},
			award_icon = {"ty_icon_flq1",},
		},
		[5]=
		{
			id = 5,
			game_id = 2,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {5000,},
			award_icon = {"ty_icon_flq1",},
		},
		[6]=
		{
			id = 6,
			game_id = 2,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {3000,},
			award_icon = {"ty_icon_flq1",},
		},
		[7]=
		{
			id = 7,
			game_id = 2,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {2000,},
			award_icon = {"ty_icon_flq1",},
		},
		[8]=
		{
			id = 8,
			game_id = 2,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {1400,},
			award_icon = {"ty_icon_flq1",},
		},
		[9]=
		{
			id = 9,
			game_id = 3,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {12500,},
			award_icon = {"ty_icon_flq1",},
		},
		[10]=
		{
			id = 10,
			game_id = 3,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {7500,},
			award_icon = {"ty_icon_flq1",},
		},
		[11]=
		{
			id = 11,
			game_id = 3,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {5000,},
			award_icon = {"ty_icon_flq1",},
		},
		[12]=
		{
			id = 12,
			game_id = 3,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {3500,},
			award_icon = {"ty_icon_flq1",},
		},
		[13]=
		{
			id = 13,
			game_id = 4,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {25000,},
			award_icon = {"ty_icon_flq1",},
		},
		[14]=
		{
			id = 14,
			game_id = 4,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {15000,},
			award_icon = {"ty_icon_flq1",},
		},
		[15]=
		{
			id = 15,
			game_id = 4,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {10000,},
			award_icon = {"ty_icon_flq1",},
		},
		[16]=
		{
			id = 16,
			game_id = 4,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {7000,},
			award_icon = {"ty_icon_flq1",},
		},
	},
	pms_config=
	{
		[1]=
		{
			id = 1,
			game_tag = "pms",
			game_id = 2,
			game_type = "game_Fishing3D",
			game_name = "50福利券赛",
			game_type_name = "龙王宝藏神秘海域场",
			ui_order = 1,
			enter_condi_itemkey = {"jing_bi",},
			enter_condi_item_count = {5000,},
			award_desc = {"50福利券",},
			award_icon = {"ty_icon_flq1",},
			jing_bi_min = 1000,
			jing_bi_max = 2000000,
			match_bullet_num = 1000,
			match_time = 10,
			award = "50福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 76,
			diamond_id = 1,
			award_id = 1,
		},
		[2]=
		{
			id = 2,
			game_tag = "pms",
			game_id = 3,
			game_type = "game_Fishing3D",
			game_name = "200福利券赛",
			game_type_name = "龙王宝藏海底宝藏场",
			ui_order = 2,
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,20000,},
			award_desc = {"200福利券",},
			award_icon = {"ty_icon_flq2",},
			jing_bi_min = 10000,
			jing_bi_max = 20000000,
			match_bullet_num = 1000,
			match_time = 10,
			award = "200福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 77,
			diamond_id = 1,
			award_id = 2,
		},
		[3]=
		{
			id = 3,
			game_tag = "pms",
			game_id = 4,
			game_type = "game_Fishing3D",
			game_name = "500福利券赛",
			game_type_name = "龙王宝藏藏宝海湾场",
			ui_order = 3,
			enter_condi_itemkey = {"jing_bi",},
			enter_condi_item_count = {50000,},
			award_desc = {"500福利券",},
			award_icon = {"ty_icon_flq3",},
			jing_bi_min = 100000,
			jing_bi_max = 99999999999,
			match_bullet_num = 1000,
			match_time = 10,
			award = "500福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 80,
			diamond_id = 1,
			award_id = 3,
		},
		[4]=
		{
			id = 4,
			game_tag = "pms",
			game_id = 5,
			game_type = "game_Fishing3D",
			game_name = "1000福利券赛",
			game_type_name = "龙王宝藏深海沉船场",
			ui_order = 4,
			enter_condi_itemkey = {"jing_bi",},
			enter_condi_item_count = {100000,},
			award_desc = {"1000福利券",},
			award_icon = {"ty_icon_flq3",},
			jing_bi_min = 1000000,
			jing_bi_max = 99999999999,
			match_bullet_num = 1000,
			match_time = 10,
			award = "1000福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 102,
			gift_id = 82,
			diamond_id = 2,
			award_id = 4,
		},
	},
	pms_award=
	{
		[1]=
		{
			id = 1,
			award_id = 1,
			rank_name = "黄金段位",
			icon = "bs_icon_hj",
			is_local_icon = 1,
			min_score = 1500,
			max_score = -1,
			award_desc = {"50福利券",},
			award_icon = {"ty_icon_flq1",},
		},
		[2]=
		{
			id = 2,
			award_id = 1,
			rank_name = "白银段位",
			icon = "bs_icon_by",
			is_local_icon = 1,
			min_score = 1201,
			max_score = 1499,
			award_desc = {"30000金币",},
			award_icon = {"ty_icon_jb_18y",},
		},
		[3]=
		{
			id = 3,
			award_id = 1,
			rank_name = "青铜段位",
			icon = "bs_icon_qt",
			is_local_icon = 1,
			min_score = 1000,
			max_score = 1200,
			award_desc = {"10000金币",},
			award_icon = {"ty_icon_jb_15y",},
		},
		[4]=
		{
			id = 4,
			award_id = 2,
			rank_name = "黄金段位",
			icon = "bs_icon_hj",
			is_local_icon = 1,
			min_score = 1500,
			max_score = -1,
			award_desc = {"200福利券",},
			award_icon = {"ty_icon_flq2",},
		},
		[5]=
		{
			id = 5,
			award_id = 2,
			rank_name = "白银段位",
			icon = "bs_icon_by",
			is_local_icon = 1,
			min_score = 1201,
			max_score = 1499,
			award_desc = {"100000金币",},
			award_icon = {"ty_icon_jb_30y",},
		},
		[6]=
		{
			id = 6,
			award_id = 2,
			rank_name = "青铜段位",
			icon = "bs_icon_qt",
			is_local_icon = 1,
			min_score = 1000,
			max_score = 1200,
			award_desc = {"50000金币",},
			award_icon = {"ty_icon_jb_18y",},
		},
		[7]=
		{
			id = 7,
			award_id = 3,
			rank_name = "黄金段位",
			icon = "bs_icon_hj",
			is_local_icon = 1,
			min_score = 1500,
			max_score = -1,
			award_desc = {"500福利券",},
			award_icon = {"ty_icon_flq3",},
		},
		[8]=
		{
			id = 8,
			award_id = 3,
			rank_name = "白银段位",
			icon = "bs_icon_by",
			is_local_icon = 1,
			min_score = 1201,
			max_score = 1499,
			award_desc = {"300000金币",},
			award_icon = {"ty_icon_jb_98y",},
		},
		[9]=
		{
			id = 9,
			award_id = 3,
			rank_name = "青铜段位",
			icon = "bs_icon_qt",
			is_local_icon = 1,
			min_score = 1000,
			max_score = 1200,
			award_desc = {"100000金币",},
			award_icon = {"ty_icon_jb_30y",},
		},
		[10]=
		{
			id = 10,
			award_id = 4,
			rank_name = "黄金段位",
			icon = "bs_icon_hj",
			is_local_icon = 1,
			min_score = 1500,
			max_score = -1,
			award_desc = {"1000福利券",},
			award_icon = {"ty_icon_flq3",},
		},
		[11]=
		{
			id = 11,
			award_id = 4,
			rank_name = "白银段位",
			icon = "bs_icon_by",
			is_local_icon = 1,
			min_score = 1201,
			max_score = 1499,
			award_desc = {"500000金币",},
			award_icon = {"ty_icon_jb_98y",},
		},
		[12]=
		{
			id = 12,
			award_id = 4,
			rank_name = "青铜段位",
			icon = "bs_icon_qt",
			is_local_icon = 1,
			min_score = 1000,
			max_score = 1200,
			award_desc = {"200000金币",},
			award_icon = {"ty_icon_jb_30y",},
		},
	},
}