return {
	base=
	{
		[1]=
		{
			index = 1,
			exchange_key = "exchange_yghhl",
			exchange_name = "阳光换好礼",
			type = 2,
			start_time = 1611617400,
			end_time = 1612195199,
			item_key = "prop_048_xxlqd_sunshine",
			item_name = "阳光",
			panel_txt_fmt = {"EAF2FF",},
			item_name_fmt = {"F9FFFF","5927CD",},
			item_comsume_fmt = {"5927CD",},
			exchange_ids = {1,2,3,4,5,},
			isOnOff = 0,
		},
		[2]=
		{
			index = 2,
			exchange_key = "exchange_xnhl",
			exchange_name = "新年好礼",
			type = 1,
			exchange_type = 27,
			start_time = 1612827000,
			end_time = 1613404799,
			item_key = "prop_fish_drop_act_0",
			item_name = "压岁钱",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {6,7,8,9,10,11,12,13,14,},
			isOnOff = 0,
			help_info = {"1.活动时间：2月9日7:30~2月15日23:59:59",    "2.活动期间街机捕鱼小游戏中可获得压岁钱道具",    "3.活动结束后所有未使用的压岁钱道具将全部清除，请及时兑换",    "4.实物奖励请联系官方QQ公众号：4008882620领取，春节期间实物奖励延迟发放"},
			gotoUI = "game_FishingHall",
		},
		[3]=
		{
			index = 3,
			exchange_key = "exchange_ybdh",
			exchange_name = "元宝兑换",
			type = 1,
			exchange_type = 28,
			style_key = "act_003_ybdh",
			start_time = 1613431800,
			end_time = 1614009599,
			item_key = "prop_fish_drop_act_1",
			item_name = "银元宝",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {15,16,17,18,19,20,21,22,},
			isOnOff = 0,
			gotoUI = "game_FishingHall",
		},
		[4]=
		{
			index = 4,
			exchange_key = "exchange_thsl",
			exchange_name = "桃花送礼",
			type = 1,
			exchange_type = 31,
			style_key = "act_004_thsl",
			start_time = 1615851000,
			end_time = 1616428799,
			item_key = "prop_fish_drop_act_0",
			item_name = "桃花",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {23,24,25,26,27,28,29,30,},
			isOnOff = 0,
			help_info = {"1.活动时间：3月16日7:30~3月22日23:59:59","2.活动结束后所有未使用的桃花道具将全部清除，请及时使用","3.实物奖励请联系客服QQ公众号4008882620领取","4.实物图片仅供参考，请以实际收到的奖励为准",},
			gotoUI = "game_FishingHall",
		},
		[5]=
		{
			index = 5,
			exchange_key = "exchange_qmjz_hldh",
			exchange_name = "好礼兑换",
			type = 1,
			exchange_type = 32,
			style_key = "act_005_hldh",
			start_time = 1617060600,
			end_time = 1617638399,
			item_key = "prop_fish_drop_act_0",
			item_name = "菊花",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {31,32,33,34,35,36,37,38,},
			isOnOff = 0,
			help_info = {"1.活动时间：3月30日7:30~4月5日23:59:59","2.活动结束后所有未使用的菊花道具将全部清除，请及时使用",},
			gotoUI = "game_FishingHall",
		},
		[6]=
		{
			index = 6,
			exchange_key = "exchange_khqd_hldh",
			exchange_name = "好礼兑换",
			type = 1,
			exchange_type = 33,
			style_key = "act_006_khqd_hldh",
			start_time = 1617665400,
			end_time = 1618243199,
			item_key = "prop_fish_drop_act_0",
			item_name = "气球",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {39,40,41,42,43,44,45,46,},
			isOnOff = 1,
			help_info = {"1.活动时间：4月6日7:30~4月12日23:59:59","2.活动结束后所有未使用的气球道具将全部清除，请及时使用","3.实物奖励请联系客服QQ公众号4008882620领取","4.实物图片仅供参考，请以实际收到的奖励为准",},
			gotoUI = "game_FishingHall",
		},
	},
	exchanges=
	{
		[1]=
		{
			index = 1,
			ID = 1,
			award_name = "1万鲸币",
			price = 0,
			gift_id = 10588,
			award_image = "pay_icon_gold7",
			item_cost_text = 10,
			award_text = "1万",
			is_real = 0,
			limit_num = 1,
		},
		[2]=
		{
			index = 2,
			ID = 2,
			award_name = "28万鲸币",
			price = 18,
			gift_id = 10589,
			award_image = "pay_icon_gold8",
			item_cost_text = 200,
			award_text = "28万",
			is_real = 0,
			limit_num = 1,
		},
		[3]=
		{
			index = 3,
			ID = 3,
			award_name = "70万鲸币",
			price = 48,
			gift_id = 10590,
			award_image = "pay_icon_gold9",
			item_cost_text = 400,
			award_text = "70万",
			is_real = 0,
			limit_num = 3,
		},
		[4]=
		{
			index = 4,
			ID = 4,
			award_name = "145万鲸币",
			price = 98,
			gift_id = 10591,
			award_image = "pay_icon_gold10",
			item_cost_text = 800,
			award_text = "145万",
			is_real = 0,
			limit_num = 5,
		},
		[5]=
		{
			index = 5,
			ID = 5,
			award_name = "268万鲸币",
			price = 198,
			gift_id = 10592,
			award_image = "pay_icon_gold11",
			item_cost_text = 1200,
			award_text = "268万",
			is_real = 0,
			limit_num = 8,
		},
		[6]=
		{
			index = 6,
			ID = 1,
			award_name = "茅台抽奖券*3",
			award_image = "com_award_icon_dhq",
			item_cost_text = 50,
			award_text = 3,
			is_real = 0,
			limit_num = 1,
			tips = {"茅台抽奖券","可参与“新年送茅台”活动"},
		},
		[7]=
		{
			index = 7,
			ID = 2,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 1500,
			award_text = "10万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[8]=
		{
			index = 8,
			ID = 3,
			award_name = "800话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 2000,
			award_text = 800,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[9]=
		{
			index = 9,
			ID = 4,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 2500,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[10]=
		{
			index = 10,
			ID = 5,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 7500,
			award_text = "50万",
			is_real = 0,
			limit_num = 2,
			tips = {"鲸币","游戏基础货币"},
		},
		[11]=
		{
			index = 11,
			ID = 6,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			award_text = 50,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可再兑换商城购买实物"},
		},
		[12]=
		{
			index = 12,
			ID = 7,
			award_name = "食用油",
			award_image = "activity_icon_gift251_jly",
			item_cost_text = 15000,
			award_text = 1,
			is_real = 1,
			limit_num = 1,
			tips = {"食用油","葵花籽食用植物调和油"},
		},
		[13]=
		{
			index = 13,
			ID = 8,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 15000,
			award_text = "100万",
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[14]=
		{
			index = 14,
			ID = 9,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 30000,
			award_text = "200万",
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[15]=
		{
			index = 15,
			ID = 1,
			award_name = "金元宝*10",
			award_image = "cssl_iocn_jyb",
			item_cost_text = 800,
			award_text = 10,
			is_real = 0,
			limit_num = 3,
			tips = {"金元宝","可参与财神送礼抽奖"},
		},
		[16]=
		{
			index = 16,
			ID = 2,
			award_name = "金元宝*40",
			award_image = "cssl_iocn_jyb_1",
			item_cost_text = 4000,
			award_text = 40,
			is_real = 0,
			tips = {"金元宝","可参与财神送礼抽奖"},
		},
		[17]=
		{
			index = 17,
			ID = 3,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 300,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[18]=
		{
			index = 18,
			ID = 4,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 600,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[19]=
		{
			index = 19,
			ID = 5,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 1200,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[20]=
		{
			index = 20,
			ID = 6,
			award_name = "50元充值优惠券",
			award_image = "com_award_icon_czyhq4",
			item_cost_text = 3000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣50元"},
		},
		[21]=
		{
			index = 21,
			ID = 7,
			award_name = "100元充值优惠券",
			award_image = "com_award_icon_czyhq5",
			item_cost_text = 6000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣100元"},
		},
		[22]=
		{
			index = 22,
			ID = 8,
			award_name = "200元充值优惠券",
			award_image = "com_award_icon_czyhq6",
			item_cost_text = 12000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣200元"},
		},
		[23]=
		{
			index = 23,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			award_text = 100,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[24]=
		{
			index = 24,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[25]=
		{
			index = 25,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 1200,
			award_text = "10万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[26]=
		{
			index = 26,
			ID = 4,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 6000,
			award_text = "50万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[27]=
		{
			index = 27,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			award_text = 50,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可再兑换商城购买实物"},
		},
		[28]=
		{
			index = 28,
			ID = 6,
			award_name = "大米",
			award_image = "activity_icon_gift269_jly",
			item_cost_text = 10000,
			award_text = 1,
			is_real = 1,
			limit_num = 1,
			tips = {"大米","金龙鱼大米"},
		},
		[29]=
		{
			index = 29,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 12000,
			award_text = "100万",
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[30]=
		{
			index = 30,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 24000,
			award_text = "200万",
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[31]=
		{
			index = 31,
			ID = 1,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 500,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[32]=
		{
			index = 32,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[33]=
		{
			index = 33,
			ID = 3,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 2000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[34]=
		{
			index = 34,
			ID = 4,
			award_name = "香*100",
			award_image = "com_award_icon_xiang",
			item_cost_text = 3000,
			award_text = 100,
			is_real = 0,
			tips = {"香","用于参加祭祖祈福活动"},
		},
		[35]=
		{
			index = 35,
			ID = 5,
			award_name = "50元充值优惠券",
			award_image = "com_award_icon_czyhq4",
			item_cost_text = 5000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣50元"},
		},
		[36]=
		{
			index = 36,
			ID = 6,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 6000,
			award_text = "50万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[37]=
		{
			index = 37,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 12000,
			award_text = "100万",
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[38]=
		{
			index = 38,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 24000,
			award_text = "200万",
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[39]=
		{
			index = 39,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			award_text = 100,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[40]=
		{
			index = 40,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			award_text = 1,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[41]=
		{
			index = 41,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			award_text = "10万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[42]=
		{
			index = 42,
			ID = 4,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold7",
			item_cost_text = 6000,
			award_text = "50万",
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[43]=
		{
			index = 43,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			award_text = 50,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[44]=
		{
			index = 44,
			ID = 6,
			award_name = "大米",
			award_image = "activity_icon_gift269_jly",
			item_cost_text = 10000,
			award_text = 1,
			is_real = 1,
			limit_num = 1,
			tips = {"大米","金龙鱼大米"},
		},
		[45]=
		{
			index = 45,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			award_text = "100万",
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[46]=
		{
			index = 46,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			award_text = "200万",
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
	},
}