return {
	platform_or_channel_or_level=
	{
		[1]=
		{
			line = 1,
			permission = "actp_buy_gift_bag_class_fclb_free_002",
			gift_config = {1,2,3,4},
			collect_config = {1,2,3},
		},
		[2]=
		{
			line = 2,
			permission = "actp_buy_gift_bag_class_fclb_v1v7_002",
			gift_config = {5,6,7,8},
			collect_config = {4,5,6},
		},
		[3]=
		{
			line = 3,
			permission = "actp_buy_gift_bag_class_fclb_v8v12_002",
			gift_config = {9,10,11,12},
			collect_config = {7,8,9},
		},
	},
	other_data=
	{
		[1]=
		{
			line = 1,
			item_key = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai"},
			item_key_img = {"collect_words_1_1","collect_words_2_1","collect_words_3_1","collect_words_4_1"},
			item_name = "字符",
			sta_t = 1613433600,
			end_t = 1614009599,
			is_sort = 1,
		},
	},
	gift_config=
	{
		[1]=
		{
			line = 1,
			gift_id = 10437,
			gift_page = {"collect_words_xz_1","collect_words_wxz_1"},
			gift_name = "恭字礼包",
			gift_price = 6,
			award_txt = {"60万金币","2万小游戏币","恭字符*1",},
			award_img = {"ty_icon_jb_6y","ty_icon_yxb_2","collect_words_1"},
			award_tip = {"","","恭字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[2]=
		{
			line = 2,
			gift_id = 10438,
			gift_page = {"collect_words_xz_2","collect_words_wxz_2"},
			gift_name = "喜字礼包",
			gift_price = 10,
			award_txt = {"100万金币","3.8万小游戏币","喜字符*1",},
			award_img = {"ty_icon_jb_15y","ty_icon_yxb_2","collect_words_2"},
			award_tip = {"","","喜字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[3]=
		{
			line = 3,
			gift_id = 10439,
			gift_page = {"collect_words_xz_3","collect_words_wxz_3"},
			gift_name = "发字礼包",
			gift_price = 18,
			award_txt = {"180万金币","5万小游戏币","发字符*1",},
			award_img = {"ty_icon_jb_18y","ty_icon_yxb_4","collect_words_3"},
			award_tip = {"","","发字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[4]=
		{
			line = 4,
			gift_id = 10440,
			gift_page = {"collect_words_xz_4","collect_words_wxz_4"},
			gift_name = "财字礼包",
			gift_price = 48,
			award_txt = {"480万金币","10万小游戏币","财字符*1",},
			award_img = {"ty_icon_jb_48y","ty_icon_yxb_4","collect_words_4"},
			award_tip = {"","","财字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[5]=
		{
			line = 5,
			gift_id = 10441,
			gift_page = {"collect_words_xz_1","collect_words_wxz_1"},
			gift_name = "恭字礼包",
			gift_price = 18,
			award_txt = {"180万金币","5万小游戏币","恭字符*1",},
			award_img = {"ty_icon_jb_18y","ty_icon_yxb_2","collect_words_1"},
			award_tip = {"","","恭字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[6]=
		{
			line = 6,
			gift_id = 10442,
			gift_page = {"collect_words_xz_2","collect_words_wxz_2"},
			gift_name = "喜字礼包",
			gift_price = 48,
			award_txt = {"480万金币","10万小游戏币","喜字符*1",},
			award_img = {"ty_icon_jb_50y","ty_icon_yxb_4","collect_words_2"},
			award_tip = {"","","喜字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[7]=
		{
			line = 7,
			gift_id = 10443,
			gift_page = {"collect_words_xz_3","collect_words_wxz_3"},
			gift_name = "发字礼包",
			gift_price = 98,
			award_txt = {"980万金币","20万小游戏币","发字符*1",},
			award_img = {"ty_icon_jb_98y","ty_icon_yxb_5","collect_words_3"},
			award_tip = {"","","发字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[8]=
		{
			line = 8,
			gift_id = 10444,
			gift_page = {"collect_words_xz_4","collect_words_wxz_4"},
			gift_name = "财字礼包",
			gift_price = 198,
			award_txt = {"1980万金币","40万小游戏币","财字符*1",},
			award_img = {"ty_icon_jb_198y","ty_icon_yxb_5","collect_words_4"},
			award_tip = {"","","财字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[9]=
		{
			line = 9,
			gift_id = 10445,
			gift_page = {"collect_words_xz_1","collect_words_wxz_1"},
			gift_name = "恭字礼包",
			gift_price = 48,
			award_txt = {"480万金币","10万小游戏币","恭字符*1",},
			award_img = {"ty_icon_jb_50y","ty_icon_yxb_2","collect_words_1"},
			award_tip = {"","","恭字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[10]=
		{
			line = 10,
			gift_id = 10446,
			gift_page = {"collect_words_xz_2","collect_words_wxz_2"},
			gift_name = "喜字礼包",
			gift_price = 98,
			award_txt = {"980万金币","20万小游戏币","喜字符*1",},
			award_img = {"ty_icon_jb_98y","ty_icon_yxb_4","collect_words_2"},
			award_tip = {"","","喜字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[11]=
		{
			line = 11,
			gift_id = 10447,
			gift_page = {"collect_words_xz_3","collect_words_wxz_3"},
			gift_name = "发字礼包",
			gift_price = 198,
			award_txt = {"1980万金币","40万小游戏币","发字符*1",},
			award_img = {"ty_icon_jb_198y","ty_icon_yxb_5","collect_words_3"},
			award_tip = {"","","发字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
		[12]=
		{
			line = 12,
			gift_id = 10448,
			gift_page = {"collect_words_xz_4","collect_words_wxz_4"},
			gift_name = "财字礼包",
			gift_price = 498,
			award_txt = {"4980万金币","80万小游戏币","财字符*1",},
			award_img = {"ty_icon_jb_498y","ty_icon_yxb_5","collect_words_4"},
			award_tip = {"","","财字符:可兑换奖励"},
			xg_txt = "每日限购3次",
		},
	},
	collect_config=
	{
		[1]=
		{
			line = 1,
			exchange_type = 36,
			exchange_id = 1,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi"},
			need_item_img = {"collect_words_1_1","collect_words_2_1"},
			need_num = {1,1},
			award_txt = {"10万金币",},
			award_img = {"ty_icon_jb_18y",},
			award_tip = {"",},
		},
		[2]=
		{
			line = 2,
			exchange_type = 37,
			exchange_id = 1,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_3_1","collect_words_4_1"},
			need_num = {1,1},
			award_txt = {"30万金币",},
			award_img = {"ty_icon_jb_30y",},
			award_tip = {"",},
		},
		[3]=
		{
			line = 3,
			exchange_type = 38,
			exchange_id = 1,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_1_1","collect_words_2_1","collect_words_3_1","collect_words_4_1"},
			need_num = {1,1,1,1},
			award_txt = {"50万金币",},
			award_img = {"ty_icon_jb_50y",},
			award_tip = {"",},
		},
		[4]=
		{
			line = 4,
			exchange_type = 36,
			exchange_id = 2,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi"},
			need_item_img = {"collect_words_1_1","collect_words_2_1"},
			need_num = {1,1},
			award_txt = {"30万金币",},
			award_img = {"ty_icon_jb_18y",},
			award_tip = {"",},
		},
		[5]=
		{
			line = 5,
			exchange_type = 37,
			exchange_id = 2,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_3_1","collect_words_4_1"},
			need_num = {1,1},
			award_txt = {"100万金币",},
			award_img = {"ty_icon_jb_98y",},
			award_tip = {"",},
		},
		[6]=
		{
			line = 6,
			exchange_type = 38,
			exchange_id = 2,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_1_1","collect_words_2_1","collect_words_3_1","collect_words_4_1"},
			need_num = {1,1,1,1},
			award_txt = {"150万金币",},
			award_img = {"ty_icon_jb_198y",},
			award_tip = {"",},
		},
		[7]=
		{
			line = 7,
			exchange_type = 36,
			exchange_id = 3,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi"},
			need_item_img = {"collect_words_1_1","collect_words_2_1"},
			need_num = {1,1},
			award_txt = {"60万金币",},
			award_img = {"ty_icon_jb_50y",},
			award_tip = {"",},
		},
		[8]=
		{
			line = 8,
			exchange_type = 37,
			exchange_id = 3,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_3_1","collect_words_4_1"},
			need_num = {1,1},
			award_txt = {"250万金币",},
			award_img = {"ty_icon_jb_198y",},
			award_tip = {"",},
		},
		[9]=
		{
			line = 9,
			exchange_type = 38,
			exchange_id = 3,
			collect_title = "发财礼包福利",
			need_item = {"prop_fclb_gong","prop_fclb_xi","prop_fclb_fa","prop_fclb_cai"},
			need_item_img = {"collect_words_1_1","collect_words_2_1","collect_words_3_1","collect_words_4_1"},
			need_num = {1,1,1,1},
			award_txt = {"350万金币",},
			award_img = {"ty_icon_jb_498y",},
			award_tip = {"",},
		},
	},
}