return {
	base=
	{
		[1]=
		{
			index = 1,
			award = "0.3元奖励金",
			cost = 30,
			task_id = 1000664,
			task_txt = "携带金币2万",
			show_permission = "actp_own_task_p_show_not",
			limit = "终身1次",
			unlock_id = 6,
			goto_ui = {"shop_bay","jing_bi",},
			is_on = 1,
		},
		[2]=
		{
			index = 2,
			award = "0.5元奖励金",
			cost = 50,
			task_id = 30045,
			task_txt = "携带金币20万",
			show_permission = "actp_own_task_p_xshb_cjj_xdjb",
			limit = "终身1次",
			unlock_id = 7,
			goto_ui = {"shop_bay","jing_bi",},
			is_on = 1,
		},
		[3]=
		{
			index = 3,
			award = "3元奖励金",
			cost = 300,
			task_id = 1000663,
			task_txt = "单笔充值≥6元",
			limit = "终身3次",
			unlock_id = 5,
			unlock_permission = "xshb_042_deblocking_v0",
			tag = "新人",
			goto_ui = {"shop_bay","jing_bi",},
			is_on = 0,
		},
		[4]=
		{
			index = 4,
			award = "1元奖励金",
			cost = 100,
			task_id = 1000662,
			task_txt = "任意游戏累计消耗20万",
			limit = "每天1次",
			unlock_id = 4,
			unlock_permission = "xshb_042_deblocking_v1",
			tag = "VIP1",
			goto_ui = {"game_MiniGame",},
			is_on = 1,
		},
		[5]=
		{
			index = 5,
			award = "3元奖励金",
			cost = 300,
			task_id = 1000661,
			task_txt = "任意游戏累计消耗30万",
			limit = "每天1次",
			unlock_id = 3,
			unlock_permission = "xshb_042_deblocking_v2",
			tag = "VIP2",
			goto_ui = {"game_MiniGame",},
			is_on = 0,
		},
		[6]=
		{
			index = 6,
			award = "5元奖励金",
			cost = 500,
			task_id = 1000660,
			task_txt = "任意游戏累计消耗80万",
			limit = "每天1次",
			unlock_id = 2,
			unlock_permission = "xshb_042_deblocking_v3",
			tag = "VIP3",
			goto_ui = {"game_MiniGame",},
			is_on = 0,
		},
		[7]=
		{
			index = 7,
			award = "10元奖励金",
			cost = 1000,
			task_id = 1000659,
			task_txt = "任意游戏累计消耗120万",
			limit = "每天1次",
			unlock_id = 1,
			unlock_permission = "xshb_042_deblocking_v4",
			tag = "VIP4",
			goto_ui = {"game_MiniGame",},
			is_on = 0,
		},
	},
}