return {
	config=
	{
		[1]=
		{
			id = 1,
			key = "cpl_notcjj",
			task = "active_task_item",
			award = "active_award_config",
			award_task = 13000,
		},
		[2]=
		{
			id = 2,
			key = "cpl_cjj",
			task = "active_task_item_cjj",
			award = "active_award_config_cjj",
			award_task = 13001,
		},
	},
	active_task_item=
	{
		[1]=
		{
			id = 1,
			task_id = 12512,
			task_name = "进入游戏",
			task_icon = "rw_icon_hd",
			task_instruction = "进入3D捕鱼任意场1次",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x100","x10"},
			gotoui = {"game_Fishing3DHall",},
		},
		[2]=
		{
			id = 2,
			key = "actp_own_task_p_task_fish_daily_1_2",
			task_id = 12520,
			task_name = "使用技能",
			task_icon = "rw_icon_jn",
			task_instruction = "3D捕鱼中使用任意技能3次",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x5000","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[3]=
		{
			id = 3,
			key = "actp_own_task_p_task_fish_daily_1_2",
			task_id = 12521,
			task_name = "累计捕鱼",
			task_icon = "rw_icon_bh",
			task_instruction = "3D捕鱼中捕获任意100条鱼",
			task_award_icon = {"ty_icon_pms_1","ty_icon_hytb",},
			task_award_instruction = {"250福利券赛门票","活跃度"},
			task_award_count = {"x1","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[4]=
		{
			id = 4,
			key = "actp_own_task_p_task_fish_daily_1_2",
			task_id = 12522,
			task_name = "累计开炮",
			task_icon = "rw_icon_ljpd",
			task_instruction = "3D捕鱼中累计开炮1000次",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1万","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[5]=
		{
			id = 5,
			key = "actp_own_task_p_task_fish_daily_no_cps",
			task_id = 12523,
			task_name = "累计在线",
			task_icon = "rw_icon_ljsj",
			task_instruction = "3D捕鱼中累计在线90分钟",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x30000","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[6]=
		{
			id = 6,
			key = "actp_own_task_p_task_fish_daily_1_2",
			task_id = 12516,
			task_name = "捕获彩金",
			task_icon = "rw_icon_js",
			task_instruction = "3D捕鱼中捕获3条彩金鱼",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1万","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[7]=
		{
			id = 7,
			key = "actp_own_task_p_task_fish_daily_1_2_no_cps",
			task_id = 12519,
			task_name = "单笔充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "单笔充值6元及以上",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x30000","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[8]=
		{
			id = 8,
			key = "actp_own_task_p_task_fish_daily_2",
			task_id = 12525,
			task_name = "累计赢金",
			task_icon = "rw_icon_ljyj",
			task_instruction = "3D捕鱼中累计赢金20万",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1万","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[9]=
		{
			id = 9,
			key = "actp_own_task_p_task_fish_daily_3",
			task_id = 12508,
			task_name = "击杀活动鱼",
			task_icon = "rw_icon_jn",
			task_instruction = "3D捕鱼中击杀活动鱼1次",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x10000","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[10]=
		{
			id = 10,
			key = "actp_own_task_p_task_fish_daily_3",
			task_id = 12529,
			task_name = "击杀高倍鱼",
			task_icon = "rw_icon_bh",
			task_instruction = "3D捕鱼中击杀50倍以上鱼5条",
			task_award_icon = {"ty_icon_pms_2","ty_icon_hytb",},
			task_award_instruction = {"2500福利券赛门票","活跃度"},
			task_award_count = {"x1","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[11]=
		{
			id = 11,
			key = "actp_own_task_p_task_fish_daily_3",
			task_id = 12528,
			task_name = "累计赢金",
			task_icon = "rw_icon_ljyj",
			task_instruction = "3D捕鱼中累计赢金50万",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1.5万","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[12]=
		{
			id = 12,
			key = "actp_own_task_p_task_fish_daily_3",
			task_id = 12526,
			task_name = "捕获彩金",
			task_icon = "rw_icon_js",
			task_instruction = "3D捕鱼中捕获5条彩金鱼",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1.5万","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[13]=
		{
			id = 13,
			key = "actp_own_task_p_task_fish_daily_3_no_cps",
			task_id = 12527,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值10元及以上",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x50000","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[14]=
		{
			id = 14,
			key = "actp_own_task_p_task_fish_daily_4_5",
			task_id = 12517,
			task_name = "参与游戏",
			task_icon = "rw_icon_jn",
			task_instruction = "参与任意三种小游戏",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x10000","x30"},
			gotoui = {"game_MiniGame",},
		},
		[15]=
		{
			id = 15,
			key = "actp_own_task_p_task_fish_daily_4",
			task_id = 12532,
			task_name = "击杀高倍鱼",
			task_icon = "rw_icon_bh",
			task_instruction = "3D捕鱼中击杀100倍以上鱼5条",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x50000","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[16]=
		{
			id = 16,
			key = "actp_own_task_p_task_fish_daily_4",
			task_id = 12531,
			task_name = "累计赢金",
			task_icon = "rw_icon_ljyj",
			task_instruction = "游戏中累计赢金100万",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x2万","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[17]=
		{
			id = 17,
			key = "actp_own_task_p_task_fish_daily_4",
			task_id = 12511,
			task_name = "击杀BOSS",
			task_icon = "rw_icon_boss",
			task_instruction = "3D捕鱼中击杀BOSS鱼1条",
			task_award_icon = {"ty_icon_pms_3","ty_icon_hytb",},
			task_award_instruction = {"25000福利券赛门票","活跃度"},
			task_award_count = {"x1","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[18]=
		{
			id = 18,
			key = "actp_own_task_p_task_fish_daily_4_no_cps",
			task_id = 12530,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值30元及以上",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x150000","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[19]=
		{
			id = 19,
			key = "actp_own_task_p_task_fish_daily_5",
			task_id = 12536,
			task_name = "击杀高倍鱼",
			task_icon = "rw_icon_bh",
			task_instruction = "3D捕鱼中击杀100倍以上鱼8条",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x80000","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[20]=
		{
			id = 20,
			key = "actp_own_task_p_task_fish_daily_5",
			task_id = 12535,
			task_name = "累计赢金",
			task_icon = "rw_icon_ljyj",
			task_instruction = "游戏中累计赢金1000万",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x5万","x20"},
			gotoui = {"game_Fishing3DHall",},
		},
		[21]=
		{
			id = 21,
			key = "actp_own_task_p_task_fish_daily_5",
			task_id = 12537,
			task_name = "击杀BOSS",
			task_icon = "rw_icon_boss",
			task_instruction = "3D捕鱼中击杀BOSS鱼1条",
			task_award_icon = {"ty_icon_pms_4","ty_icon_hytb",},
			task_award_instruction = {"250000福利券赛门票","活跃度"},
			task_award_count = {"x1","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[22]=
		{
			id = 22,
			key = "actp_own_task_p_task_fish_daily_5_no_cps",
			task_id = 12534,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值100元及以上",
			task_award_icon = {"ty_icon_jb_50y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x500000","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[23]=
		{
			id = 23,
			key = "actp_own_task_p_task_fish_daily_cps",
			task_id = 12538,
			task_name = "累计在线",
			task_icon = "rw_icon_ljsj",
			task_instruction = "3D捕鱼中累计在线90分钟",
			task_award_icon = {"ty_icon_flq1","ty_icon_hytb",},
			task_award_instruction = {"福利券","活跃度"},
			task_award_count = {"x30","x30"},
			gotoui = {"game_Fishing3DHall",},
		},
		[24]=
		{
			id = 24,
			key = "actp_own_task_p_task_fish_daily_1_2_cps",
			task_id = 12539,
			task_name = "单笔充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "单笔充值6元及以上",
			task_award_icon = {"ty_icon_flq3","ty_icon_hytb",},
			task_award_instruction = {"福利券","活跃度"},
			task_award_count = {"x30","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[25]=
		{
			id = 25,
			key = "actp_own_task_p_task_fish_daily_3_cps",
			task_id = 12540,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值10元及以上",
			task_award_icon = {"ty_icon_flq3","ty_icon_hytb",},
			task_award_instruction = {"福利券","活跃度"},
			task_award_count = {"x50","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[26]=
		{
			id = 26,
			key = "actp_own_task_p_task_fish_daily_4_cps",
			task_id = 12541,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值30元及以上",
			task_award_icon = {"ty_icon_flq3","ty_icon_hytb",},
			task_award_instruction = {"福利券","活跃度"},
			task_award_count = {"x150","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
		[27]=
		{
			id = 27,
			key = "actp_own_task_p_task_fish_daily_5_cps",
			task_id = 12542,
			task_name = "累计充值",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计充值100元及以上",
			task_award_icon = {"ty_icon_flq3","ty_icon_hytb",},
			task_award_instruction = {"福利券","活跃度"},
			task_award_count = {"x500","x50"},
			gotoui = {"shop_bay","jing_bi"},
		},
	},
	active_award_config=
	{
		[1]=
		{
			id = 1,
			active = 30,
			award_tip = "5000鱼币，锁定*2",
		},
		[2]=
		{
			id = 2,
			active = 60,
			award_tip = "1万鱼币，召唤*1",
		},
		[3]=
		{
			id = 3,
			active = 90,
			award_tip = "1万鱼币，1万小游戏币",
		},
		[4]=
		{
			id = 4,
			active = 120,
			award_tip = "1万鱼币，1万金币",
		},
		[5]=
		{
			id = 5,
			active = 150,
			award_tip = "6万金币",
		},
	},
	active_task_item_cjj=
	{
		[1]=
		{
			id = 1,
			task_id = 12600,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "水果消消乐游戏50次",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x500","x5"},
			gotoui = {"game_MiniGame",},
		},
		[2]=
		{
			id = 2,
			task_id = 12601,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "水果消消乐累计消除苹果200个",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1000","x5"},
			gotoui = {"game_MiniGame",},
		},
		[3]=
		{
			id = 3,
			task_id = 12602,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "水果消消乐累计消除铃铛200个",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[4]=
		{
			id = 4,
			task_id = 12603,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "水果消消乐累计消除西瓜200个",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[5]=
		{
			id = 5,
			task_id = 12604,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "水果消消乐累计消除BAR100个",
			task_award_icon = {"ty_icon_jb_198y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[6]=
		{
			id = 6,
			task_id = 12605,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "累计赢金100万(单局至少投入5千)",
			task_award_icon = {"ty_icon_jb_198y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x2000","x20"},
			gotoui = {"game_MiniGame",},
		},
		[7]=
		{
			id = 7,
			task_id = 12606,
			task_name = "水果消消乐",
			task_icon = "rw_icon_mrzz",
			task_instruction = "出现幸运时刻(单局至少投入3万)",
			task_award_icon = {"ty_icon_jb_2498y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x3000","x30"},
			gotoui = {"game_MiniGame",},
		},
		[8]=
		{
			id = 8,
			task_id = 12607,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金1万",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x200","x5"},
			gotoui = {"game_MiniGame",},
		},
		[9]=
		{
			id = 9,
			task_id = 12608,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金5万",
			task_award_icon = {"ty_icon_jb_15y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x1000","x5"},
			gotoui = {"game_MiniGame",},
		},
		[10]=
		{
			id = 10,
			task_id = 12609,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金10万",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x2000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[11]=
		{
			id = 11,
			task_id = 12610,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金50万",
			task_award_icon = {"ty_icon_jb_30y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x2000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[12]=
		{
			id = 12,
			task_id = 12611,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金100万",
			task_award_icon = {"ty_icon_jb_198y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x3000","x10"},
			gotoui = {"game_MiniGame",},
		},
		[13]=
		{
			id = 13,
			task_id = 12612,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金500万",
			task_award_icon = {"ty_icon_jb_198y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x5000","x20"},
			gotoui = {"game_MiniGame",},
		},
		[14]=
		{
			id = 14,
			task_id = 12613,
			task_name = "累计赢金",
			task_icon = "rw_icon_mrzz",
			task_instruction = "红包场累计赢金1000万",
			task_award_icon = {"ty_icon_jb_2498y","ty_icon_hytb",},
			task_award_instruction = {"金币","活跃度"},
			task_award_count = {"x10000","x30"},
			gotoui = {"game_MiniGame",},
		},
	},
	active_award_config_cjj=
	{
		[1]=
		{
			id = 1,
			active = 30,
			award_tip = "2000小游戏币",
		},
		[2]=
		{
			id = 2,
			active = 60,
			award_tip = "3000小游戏币，玩具锤*1",
		},
		[3]=
		{
			id = 3,
			active = 90,
			award_tip = "3000金币，5000小游戏币",
		},
		[4]=
		{
			id = 4,
			active = 120,
			award_tip = "5000金币，5000小游戏币",
		},
		[5]=
		{
			id = 5,
			active = 150,
			award_tip = "1万金币",
		},
	},
}