return {
	tge=
	{
		[1]=
		{
			id = 1,
			type = "goods",
			name = "钻  石",
			icon_image = "pay_icon_diamond",
			is_new_tag = 0,
			order_id = 3,
			is_show = 1,
		},
		[2]=
		{
			id = 2,
			type = "jing_bi",
			name = "鲸  币",
			icon_image = "pay_icon_jb",
			is_new_tag = 0,
			order_id = 1,
			is_show = 1,
		},
		[3]=
		{
			id = 3,
			type = "item",
			name = "道  具",
			icon_image = "pay_icon_dj",
			is_new_tag = 1,
			order_id = 2,
			is_show = 1,
		},
	},
	goods=
	{
		[1]=
		{
			id = 1,
			price = 600,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond6",
			buy_asset_count = {400,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			group_id = 1,
			pay_title = "400钻石",
			type = "goods",
			ui_title = 400,
			ui_describe = "1元=66钻石",
			ui_price = "6元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
			is_show = 1,
			ui_order = 1,
		},
		[2]=
		{
			id = 2,
			price = 3000,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond30",
			buy_asset_count = {2000,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			group_id = 1,
			pay_title = "2000钻石",
			type = "goods",
			ui_title = 2000,
			ui_describe = "1元=66钻石",
			ui_price = "30元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
			is_show = 1,
			ui_order = 2,
		},
		[3]=
		{
			id = 3,
			price = 9800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond98",
			buy_asset_count = {6700,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			group_id = 1,
			pay_title = "6700钻石",
			type = "goods",
			ui_title = 6700,
			ui_describe = "1元=66钻石",
			ui_price = "98元",
			ui_icon = "pay_icon_diamond3",
			ui_icon_bg = "pay_bg_light2",
			is_show = 1,
			ui_order = 3,
		},
		[4]=
		{
			id = 4,
			price = 19800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond198",
			buy_asset_count = {13200,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			group_id = 1,
			pay_title = "1.32万钻石",
			type = "goods",
			ui_title = "1.32万",
			ui_describe = "1元=66钻石",
			ui_price = "198元",
			ui_icon = "pay_icon_diamond4",
			ui_icon_bg = "pay_bg_light2",
			is_show = 1,
			ui_order = 4,
		},
		[5]=
		{
			id = 5,
			price = 29800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond298",
			buy_asset_count = {20400,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			group_id = 1,
			pay_title = "2.04万钻石",
			type = "goods",
			ui_title = "2.04万",
			ui_describe = "1元=66钻石",
			ui_price = "298元",
			ui_icon = "pay_icon_diamond5",
			ui_icon_bg = "pay_bg_light2",
			is_show = 1,
			ui_order = 5,
		},
		[14]=
		{
			id = 14,
			price = 300,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond3",
			buy_asset_count = {200,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "200钻石",
			type = "goods",
			ui_title = 200,
			ui_describe = "1元=66钻石",
			ui_price = "3元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 0,
		},
		[15]=
		{
			id = 15,
			price = 800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond8",
			buy_asset_count = {530,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "530钻石",
			type = "goods",
			ui_title = 530,
			ui_describe = "1元=66钻石",
			ui_price = "8元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 2,
		},
		[16]=
		{
			id = 16,
			price = 1200,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond12",
			buy_asset_count = {800,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "800钻石",
			type = "goods",
			ui_title = 800,
			ui_describe = "1元=66钻石",
			ui_price = "12元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 3,
		},
		[17]=
		{
			id = 17,
			price = 1800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond18",
			buy_asset_count = {1200,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "1200钻石",
			type = "goods",
			ui_title = 1200,
			ui_describe = "1元=66钻石",
			ui_price = "18元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 4,
		},
		[18]=
		{
			id = 18,
			price = 2800,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond28",
			buy_asset_count = {1860,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "1860钻石",
			type = "goods",
			ui_title = 1860,
			ui_describe = "1元=66钻石",
			ui_price = "28元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 5,
		},
		[19]=
		{
			id = 19,
			price = 100,
			buy_asset_type = {"diamond",},
			product_id = "com.jyjjddz.zs.diamond1",
			buy_asset_count = {100,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			group_id = 1,
			pay_title = "100钻石",
			type = "goods",
			ui_title = 100,
			ui_describe = "1元=66钻石",
			ui_price = "1元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
			is_show = 0,
			ui_order = 0,
		},
	},
	gift_bag=
	{
		[1]=
		{
			no = 1,
			id = 7,
			on_off = 0,
			pay_title = "二元礼包",
			gzh_order = 7,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,3},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[2]=
		{
			no = 2,
			id = 8,
			on_off = 0,
			pay_title = "合伙人礼包",
			gzh_order = 8,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,4},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[3]=
		{
			no = 3,
			id = 9,
			on_off = 0,
			pay_title = "圣诞礼包",
			gzh_order = 9,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,5},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[4]=
		{
			no = 4,
			id = 10,
			on_off = 1,
			pay_title = "一元超值礼包",
			gzh_order = -4,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi","shop_gold_sum"},
			buy_asset_count = {10000,100},
			buy_limt = 1,
			count = 99999999,
			valid_time = 0,
		},
		[5]=
		{
			no = 5,
			id = 11,
			on_off = 0,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -5,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi","shop_gold_sum","prop_2"},
			buy_asset_count = {10000,100,1},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[6]=
		{
			no = 6,
			id = 12,
			on_off = 1,
			pay_title = "金猪大礼包",
			gzh_order = -10,
			shop_type = "gift_bag",
			price = 19900,
			buy_asset_type = {"jing_bi","prop_hammer_2","jipaiqi","prop_2","prop_3","expression_54"},
			buy_asset_count = {180000,200,30,10,1,50},
			buy_limt = 0,
			count = 100,
			valid_time = 0,
		},
		[7]=
		{
			no = 7,
			id = 13,
			on_off = 1,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -6,
			shop_type = "gift_bag",
			price = 1000,
			buy_asset_type = {"jing_bi","prop_2"},
			buy_asset_count = {100000,1},
			buy_limt = 0,
			count = 9999999,
			valid_time = 0,
		},
		[8]=
		{
			no = 8,
			id = 20,
			on_off = 1,
			pay_title = "迎新春礼包",
			gzh_order = -7,
			shop_type = "gift_bag",
			price = 2800,
			buy_asset_type = {"jing_bi","jipaiqi","prop_2"},
			buy_asset_count = {320000,3,1},
			buy_limt = 0,
			count = 0,
			valid_time = 1548950400,
		},
		[9]=
		{
			no = 9,
			id = 21,
			on_off = 1,
			pay_title = "春节礼包",
			gzh_order = -7,
			shop_type = "gift_bag",
			price = 1900,
			buy_asset_type = {"jing_bi","jipaiqi","prop_2"},
			buy_asset_count = {270000,3,1},
			buy_limt = 0,
			count = 999999,
			valid_time = 1550592000,
		},
	},
	jing_bi=
	{
		[1]=
		{
			line_id = 1,
			id = 101,
			platform = "ios",
			goods_id = 1,
			use_type = "diamond",
			use_count = 400,
			jing_bi = 40000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "4万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 400,
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 1,
		},
		[2]=
		{
			line_id = 2,
			id = 102,
			platform = "ios",
			goods_id = 2,
			use_type = "diamond",
			use_count = 2000,
			jing_bi = 200000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "20万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 2000,
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 2,
		},
		[3]=
		{
			line_id = 3,
			id = 103,
			platform = "ios",
			goods_id = 3,
			use_type = "diamond",
			use_count = 6700,
			jing_bi = 670000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "67万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 6700,
			ui_icon = "pay_icon_gold3",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 3,
		},
		[4]=
		{
			line_id = 4,
			id = 104,
			platform = "ios",
			goods_id = 4,
			use_type = "diamond",
			use_count = 13200,
			jing_bi = 1320000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "132万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 13200,
			ui_icon = "pay_icon_gold4",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 4,
		},
		[5]=
		{
			line_id = 5,
			id = 105,
			platform = "ios",
			goods_id = 5,
			use_type = "diamond",
			use_count = 20400,
			jing_bi = 2040000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "204万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 20400,
			ui_icon = "pay_icon_gold6",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 5,
		},
		[6]=
		{
			line_id = 6,
			id = 106,
			platform = "ios",
			goods_id = 1,
			use_type = "diamond",
			use_count = 100,
			jing_bi = 10000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			ui_title = "1万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 100,
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 0,
		},
	},
	item=
	{
		[1]=
		{
			line_no = 1,
			id = 1,
			type = "expression",
			use_type = "jing_bi",
			use_count = 60000,
			num = 1,
			group = "expression_666",
			item_id = 54,
			max = 9999,
			ui_title = "666表情",
			ui_givedesc = "有几率中福卡",
			ui_describe = "表情在任意游戏通用",
			ui_price = 60000,
			ui_icon = "pay_icon_666",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 1,
			condition = {22,},
		},
		[2]=
		{
			line_no = 2,
			id = 2,
			type = "expression",
			use_type = "jing_bi",
			use_count = 500000,
			num = 10,
			group = "expression_666",
			item_id = 54,
			max = 9999,
			ui_title = "666表情",
			ui_givedesc = "必中福卡",
			ui_describe = "表情在任意游戏通用",
			ui_price = 500000,
			ui_icon = "pay_icon_666",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 8.300000,
			is_show = 1,
			ui_order = 2,
			condition = {23,},
		},
		[3]=
		{
			line_no = 3,
			id = 3,
			type = "jipaiqi",
			use_type = "diamond",
			use_count = 150,
			jipaiqi_time = 1,
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			ui_title = "记牌器1天",
			ui_describe = "斗地主使用，可累积",
			ui_price = 150,
			ui_icon = "pay_icon_memorycard",
			ui_icon_bg = "pay_bg_light1",
			is_show = 1,
			ui_order = 3,
		},
		[4]=
		{
			line_no = 4,
			id = 1,
			type = "room_card",
			use_type = "diamond",
			use_count = 300,
			num = 15,
			gift_asset_type = {"jing_bi",},
			gift_asset_count = {15000,},
			ui_title = "15房卡",
			ui_givedesc = "额外送1.5万鲸币",
			ui_describe = "原价100钻=1房卡",
			ui_price = 300,
			ui_icon = "pay_icon_rc1",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 2,
			is_show = 1,
			ui_order = 4,
		},
	},
}