return {
	config=
	{
		[1]=
		{
			line = 1,
			order = 52,
			tag = 1,
			icon = "3dby_icon_yu27",
			name = "小牛角",
			game_id = {1,2,3,4,5},
			scale = 8,
			rotation = {66,0,0},
			rate = "2倍",
			prefab = "Fish3D061",
			tips = "身型小巧，自认为很可爱。",
		},
		[2]=
		{
			line = 2,
			order = 50,
			tag = 1,
			icon = "3dby_icon_yu28",
			name = "小气泡",
			game_id = {1,2,3,4,5},
			scale = 8,
			rotation = {66,0,0},
			rate = "2倍",
			prefab = "Fish3D062",
			tips = "天生长者一对大眼睛，一脸无辜的样子让人不忍心捕捉。",
		},
		[3]=
		{
			line = 3,
			order = 48,
			tag = 1,
			icon = "3dby_icon_yu29",
			name = "小丑鱼",
			game_id = {1,2,3,4,5},
			scale = 8,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "3倍",
			prefab = "Fish3D063",
			tips = "常说是海中的小公主。",
		},
		[4]=
		{
			line = 4,
			order = 46,
			tag = 1,
			icon = "3dby_icon_yu36",
			name = "小燕鱼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			pos = {0,-4},
			rate = "4倍",
			prefab = "Fish3D064",
			tips = "机智聪明，调皮好动，加上可爱的外表，一直深受大家喜爱。",
		},
		[5]=
		{
			line = 5,
			order = 44,
			tag = 1,
			icon = "3dby_icon_yu31",
			name = "小黄鳍",
			game_id = {1,2,3,4,5},
			scale = 8,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "5倍",
			prefab = "Fish3D065",
			tips = "优哉游哉，与世无争，但是聪明过人，只是一点脾气都没有。",
		},
		[6]=
		{
			line = 6,
			order = 42,
			tag = 1,
			icon = "3dby_icon_yu30",
			name = "河豚",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "6倍",
			prefab = "Fish3D066",
			tips = "总是成群结队，喜欢躲在草里玩捉迷藏。",
		},
		[7]=
		{
			line = 7,
			order = 40,
			tag = 1,
			icon = "3dby_icon_yu32",
			name = "小灯笼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			pos = {0,-4},
			rate = "7倍",
			prefab = "Fish3D080",
			tips = "外形看起来十分吓人，实际上非常温顺，而且胆子很小。",
		},
		[8]=
		{
			line = 8,
			order = 38,
			tag = 1,
			icon = "3dby_icon_yu48",
			name = "小旗鱼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			rate = "8倍",
			prefab = "Fish3D067",
			tips = "攻击性很强，一旦加起速没有谁能把他拦住。",
		},
		[9]=
		{
			line = 9,
			order = 36,
			tag = 1,
			icon = "3dby_icon_yu34",
			name = "小水母",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {0,0,0},
			pos = {0,-6},
			rate = "10倍",
			prefab = "Fish3D055",
			tips = "擅长跳舞，梦想是成为一名优雅的水上芭蕾舞者。",
		},
		[10]=
		{
			line = 10,
			order = 34,
			tag = 1,
			icon = "3dby_icon_yu33",
			name = "小章鱼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {0,0,0},
			rate = "12倍",
			prefab = "Fish3D060",
			tips = "喜欢在黑暗中惊吓别人，但捉迷藏从来没有赢过。",
		},
		[11]=
		{
			line = 11,
			order = 32,
			tag = 1,
			icon = "3dby_icon_yu35",
			name = "小海龟",
			game_id = {1,2,3,4,5},
			scale = 4,
			rotation = {0,0,0},
			rate = "15倍",
			prefab = "Fish3D068",
			tips = "小海龟一直是海里的广播员，只要他知道的事情大家也会第一时间知道。",
		},
		[12]=
		{
			line = 12,
			order = 30,
			tag = 1,
			icon = "3dby_icon_yu46",
			name = "狮子鱼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "18倍",
			prefab = "Fish3D069",
			tips = "狮子鱼对于任何事物似乎都不感兴趣，当然这只有在他吃饱以后。",
		},
		[13]=
		{
			line = 13,
			order = 28,
			tag = 1,
			icon = "3dby_icon_yu45",
			name = "蝴蝶鱼",
			game_id = {1,2,3,4,5},
			scale = 5,
			rotation = {66,0,0},
			rate = "20倍",
			prefab = "Fish3D070",
			tips = "同样喜欢晒太阳，但聪明的她总会选择隐秘的地方享受。",
		},
		[14]=
		{
			line = 14,
			order = 26,
			tag = 1,
			icon = "3dby_icon_yu29",
			name = "巨大小丑鱼",
			game_id = {1,2,3,4,5},
			scale = 4,
			rotation = {66,0,0},
			pos = {0,-4},
			rate = "25倍",
			prefab = "Fish3D071",
			tips = "常说是海中的小公主。",
		},
		[15]=
		{
			line = 15,
			order = 24,
			tag = 1,
			icon = "3dby_icon_yu32",
			name = "巨大灯笼鱼",
			game_id = {1,2,3,4,5},
			scale = 4,
			rotation = {66,0,0},
			pos = {0,-4},
			rate = "30倍",
			prefab = "Fish3D045",
			tips = "外形看起来十分吓人，实际上非常温顺，而且胆子很小。",
		},
		[16]=
		{
			line = 16,
			order = 22,
			tag = 1,
			icon = "3dby_icon_yu36",
			name = "巨大燕鱼",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			pos = {0,-6},
			rate = "35倍",
			prefab = "Fish3D072",
			tips = "机智聪明，调皮好动，加上可爱的外表，一直深受大家喜爱。",
		},
		[17]=
		{
			line = 17,
			order = 20,
			tag = 1,
			icon = "3dby_icon_yu43",
			name = "魔鬼鱼",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "40倍",
			prefab = "Fish3D073",
			tips = "冰冷的外表，不喜欢接触其他人，是个难以靠近的家伙。",
		},
		[18]=
		{
			line = 18,
			order = 18,
			tag = 1,
			icon = "3dby_icon_yu47",
			name = "虎鲸",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "60倍",
			prefab = "Fish3D074",
			tips = "骄傲自大，总认为自己是海底的霸主，常常自找苦头。",
		},
		[19]=
		{
			line = 19,
			order = 16,
			tag = 1,
			icon = "3dby_icon_yu57",
			name = "炸弹鱼",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D020",
			tips = "出生开始头顶就有一小团火苗，因此也让他无时无刻焦急不安。",
		},
		[20]=
		{
			line = 20,
			order = 14,
			tag = 2,
			icon = "3dby_icon_yu22",
			name = "黄金灯笼鱼",
			game_id = {1,2,3,4,5},
			scale = 2,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "60~80倍",
			prefab = "Fish3D081",
			tips = "外形看起来十分吓人，实际上非常温顺，而且胆子很小。",
		},
		[21]=
		{
			line = 21,
			order = 12,
			tag = 3,
			icon = "3dby_icon_yu50",
			name = "黄金炸弹鱼",
			game_id = {2,3,4,5},
			scale = 2,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D021",
			tips = "脾气暴躁，风风火火，一旦生气不计后果，从来不会顾及身边有谁。",
		},
		[22]=
		{
			line = 22,
			order = 10,
			tag = 2,
			icon = "3dby_icon_yu23",
			name = "黄金狮子鱼",
			game_id = {3,4,5},
			scale = 2,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "60~100倍",
			prefab = "Fish3D079",
			tips = "狮子鱼对于任何事物似乎都不感兴趣，当然这只有在他吃饱以后。",
		},
		[23]=
		{
			line = 23,
			order = 23,
			tag = 2,
			icon = "3dby_icon_yu25",
			name = "黄金海龟",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			rate = "60~120倍",
			prefab = "Fish3D046",
			tips = "个头比较大，口头禅是人生苦短，常模仿金蟾打扮自己",
		},
		[24]=
		{
			line = 24,
			order = 24,
			tag = 2,
			icon = "3dby_icon_yu20",
			name = "黄金河豚",
			game_id = {3,4,5},
			scale = 3,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "多倍奖励",
			prefab = "Fish3D047",
			tips = "比起成群结队的小河豚，黄金河豚更喜欢孤单。",
		},
		[25]=
		{
			line = 25,
			order = 25,
			tag = 2,
			icon = "3dby_icon_yu51",
			name = "金蟾",
			game_id = {3,4,5},
			scale = 3,
			rotation = {66,0,0},
			rate = "80~100倍",
			prefab = "Fish3D027",
			tips = "海底的土豪，从头到脚都有黄金作饰品，以被人围观而感到自豪。",
		},
		[26]=
		{
			line = 26,
			order = 26,
			tag = 2,
			icon = "3dby_icon_yu24",
			name = "大金鲨",
			game_id = {2,3,4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "100~120倍",
			prefab = "Fish3D049",
			tips = "是大白鲨的亲戚，行事却十分高调，喜欢炫耀自己的战绩与收获。",
		},
		[27]=
		{
			line = 27,
			order = 27,
			tag = 2,
			icon = "3dby_icon_yu21",
			name = "黄金锤头鲨",
			game_id = {4,5},
			scale = 2,
			rotation = {66,0,0},
			pos = {0,-2},
			rate = "100~160倍",
			prefab = "Fish3D048",
			tips = "自称素食主义者，喜欢品尝海草和藏在海草里的小鱼。",
		},
		[28]=
		{
			line = 28,
			order = 28,
			tag = 3,
			icon = "3dby_icon_yu14",
			name = "闪电鱼",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			pos = {-1.6,-2.5},
			rate = "特殊奖励",
			prefab = "Fish3D075",
			tips = "有海中雷震子之称，难以捕获。被捕获后，有几率触发闪电连，附近的小鱼就要遭殃了。",
		},
		[29]=
		{
			line = 29,
			order = 29,
			tag = 3,
			icon = "3dby_icon_yu52",
			name = "穿云蟹",
			game_id = {1,2,3,4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D030",
			tips = "深海中神奇的鱼种，难以捕获。被捕获后，可发射“穿云火箭”贯穿全渔场，威力不同凡响。",
		},
		[30]=
		{
			line = 30,
			order = 30,
			tag = 3,
			icon = "3dby_icon_yu53",
			name = "电磁蟹",
			game_id = {2,3,4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D034",
			tips = "深海中横行无忌的物种，难以捕获。别捕获后，他会交出秘密武器“电磁炮”让你当一回深海霸主。",
		},
		[31]=
		{
			line = 31,
			order = 31,
			tag = 3,
			icon = "3dby_icon_yu54",
			name = "强击蟹",
			game_id = {2,3,4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D041",
			tips = "捕获强击蟹，会触发20秒的免费游戏。免费游戏过程还有机会加免费时间，加奖励倍数。",
		},
		[32]=
		{
			line = 32,
			order = 32,
			tag = 3,
			icon = "3dby_icon_yu55",
			name = "宝藏章鱼",
			game_id = {2,3,4,5},
			scale = 3,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D031",
			tips = "手持宝箱，被捕捉后触发“金币大转盘”，可获得高倍金币奖励。",
		},
		[33]=
		{
			line = 33,
			order = 33,
			tag = 3,
			icon = "3dby_icon_yu56",
			name = "美人鱼",
			game_id = {2,3,4,5},
			scale = 2,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D029",
			tips = "体态优美，身型匀称，童话世界中的精灵美人鱼。",
		},
		[34]=
		{
			line = 34,
			order = 34,
			tag = 3,
			icon = "3dby_icon_yu15",
			name = "骰子龟",
			game_id = {3,4,5},
			scale = 3,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D050",
			tips = "猜骰子大小，每次均可翻倍获得奖励！",
		},
		[35]=
		{
			line = 35,
			order = 35,
			tag = 3,
			icon = "3dby_icon_yu18",
			name = "金龙转盘",
			game_id = {4,5},
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D051",
			tips = "神秘的金龙转盘，捕捉后会触发3个“连环转盘”。",
		},
		[36]=
		{
			line = 36,
			order = 36,
			tag = 3,
			icon = "3dby_icon_yu49",
			name = "炽火龙王",
			game_id = {5,},
			scale = 3,
			rotation = {0,0,0},
			pos = {-5,50},
			rate = "特殊奖励",
			prefab = "Fish3D052",
			tips = "沉睡千年的龙王，可将万物化为灰烬。",
		},
		[37]=
		{
			line = 37,
			order = 37,
			tag = 3,
			icon = "3dby_icon_yu17",
			name = "财神",
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D076",
			tips = "财神是掌管金钱与财富的神明，寄托着大吉大利，发大财的美好心愿。",
		},
		[38]=
		{
			line = 38,
			order = 38,
			tag = 2,
			icon = "3dby_icon_yu3",
			name = "黄金巨龙",
			game_id = {2,},
			scale = 0.500000,
			rotation = {0,0,0},
			pos = {0,2.6},
			rate = "最高300倍",
			prefab = "Fish3D036",
			tips = "可上天入海，见首不见尾。行事十分低调，关于他的传奇故事数不胜数。",
		},
		[39]=
		{
			line = 39,
			order = 39,
			tag = 2,
			icon = "3dby_icon_yu38",
			name = "霸王蟹",
			game_id = {1,},
			scale = 3,
			rotation = {0,0,0},
			rate = "最高200倍",
			prefab = "Fish3D053",
			tips = "由真金铸成的稀有蟹种，降服它的人据说都发家致富了。",
		},
		[40]=
		{
			line = 40,
			order = 40,
			tag = 2,
			icon = "3dby_icon_yu58",
			name = "深海鲸",
			game_id = {5,},
			scale = 0.500000,
			rotation = {0,0,0},
			rate = "最高600倍",
			prefab = "Fish3D028",
			tips = "体型巨大，晒太阳时总让人以为是座小岛，小鱼也喜欢躲在他肚子下乘凉。",
		},
		[41]=
		{
			line = 41,
			order = 41,
			tag = 2,
			icon = "3dby_icon_yu40",
			name = "鲨鱼将军",
			game_id = {3,},
			scale = 2,
			rotation = {0,0,0},
			rate = "最高300倍",
			prefab = "Fish3D054",
			tips = "鲨鱼将军傲气逼人，快去体验征服它的快感吧。",
		},
		[42]=
		{
			line = 42,
			order = 42,
			tag = 2,
			icon = "3dby_icon_yu1",
			name = "荧光女皇",
			scale = 3,
			rotation = {0,0,0},
			rate = "最高1000倍",
			prefab = "Fish3D083",
			tips = "称霸深海万年的远古水母，是个可以呼风唤雨的大人物。",
		},
		[43]=
		{
			line = 43,
			order = 43,
			tag = 2,
			icon = "3dby_icon_yu39",
			name = "远古龙龟",
			game_id = {4,},
			scale = 1.500000,
			rotation = {0,0,0},
			rate = "最高500倍",
			prefab = "Fish3D056",
			tips = "熔岩的外表下蕴藏着气动山河的力量",
		},
		[44]=
		{
			line = 44,
			order = 44,
			tag = 2,
			icon = "3dby_icon_yu44",
			name = "麒麟兽",
			scale = 1,
			rotation = {0,0,0},
			rate = "最高1000倍",
			prefab = "Fish3D082",
			tips = "来自远古的麒麟兽，拥有摧毁一切的力量，你能击败它吗",
		},
		[45]=
		{
			line = 45,
			order = 45,
			tag = 2,
			icon = "3dby_icon_yu2",
			name = "海盗船",
			scale = 1,
			rotation = {66,0,0},
			rate = "最高1000倍",
			prefab = "Fish3D057",
			tips = "相传这艘船满载金银珠宝，至今仍未曾谋面。",
		},
		[46]=
		{
			line = 46,
			order = 46,
			tag = 2,
			icon = "3dby_icon_yu4",
			name = "招财宝蟾",
			game_id = {2,},
			scale = 2,
			rotation = {0,0,0},
			rate = "最高400倍",
			prefab = "Fish3D058",
			tips = "传说中的瑞兽，象征着吉祥和尊贵。捕获后最高可获得500倍奖励。",
		},
		[47]=
		{
			line = 47,
			order = 47,
			tag = 2,
			icon = "3dby_icon_yu12",
			name = "深海狂鲨",
			game_id = {3,},
			scale = 1,
			rotation = {0,0,0},
			rate = "最高500倍",
			prefab = "Fish3D077",
			tips = "深海霸主，体形庞大，听说是身价上亿的海中富豪。",
		},
		[48]=
		{
			line = 48,
			order = 48,
			tag = 2,
			icon = "3dby_icon_yu37",
			name = "宝藏鳄鱼",
			game_id = {4,},
			scale = 1,
			rotation = {0,0,0},
			rate = "最高600倍",
			prefab = "Fish3D059",
			tips = "爱收集宝藏的他，浑身都是宝，让世人垂延三尺。",
		},
		[49]=
		{
			line = 49,
			order = 49,
			tag = 2,
			icon = "3dby_icon_yu41",
			name = "八爪海魔",
			game_id = {5,},
			scale = 3,
			rotation = {0,0,0},
			rate = "最高800倍",
			prefab = "Fish3D084",
			tips = "变异的巨型乌贼，触手的拍击可以将万物粉碎。",
		},
		[50]=
		{
			line = 50,
			order = 50,
			tag = 3,
			icon = "3dby_bg_ywdj",
			name = "一网打尽",
			scale = 2,
			rotation = {0,0,0},
			prefab = "turntable_ywdj_3d",
			tips = "一群命运共同体的鱼，不过任意一条标记有“一网打尽”的鱼，其他的将同时被捕获。",
		},
		[51]=
		{
			line = 51,
			order = 51,
			tag = 3,
			icon = "by_iocn_hfy",
			name = "话费鱼",
			game_id = {2,3,4,5,},
			scale = 4,
			rotation = {0,0,0},
			rate = "50-100倍",
			prefab = "Fish3D089",
			tips = "背负话费的特殊鱼类，击杀后有概率获得话费碎片",
		},
		[52]=
		{
			line = 52,
			order = 52,
			tag = 3,
			icon = "by_iocn_hby",
			name = "红包鱼",
			game_id = {2,3,4,5,},
			scale = 4,
			rotation = {0,0,0},
			rate = "100-300倍",
			prefab = "Fish3DHB",
			tips = "每5分钟出现一次，击杀后有极大概率直接获得福利券！",
		},
	},
}