return {
	sw_config=
	{
	},
	sw_award=
	{
	},
	qy_config=
	{
	},
	qy_award=
	{
	},
	award=
	{
		[1]=
		{
			id = 1,
			match_id = 2,
			rank = "第1名",
			award = "100钻石、1元公益基金",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"100钻石","1元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
		[2]=
		{
			id = 2,
			match_id = 2,
			rank = "第2名",
			award = "50钻石、0.5元公益基金",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"50钻石","0.5元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
		[3]=
		{
			id = 3,
			match_id = 2,
			rank = "第3名",
			award = "20钻石、0.2元公益基金",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"20钻石","0.2元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
		[4]=
		{
			id = 4,
			match_id = 3,
			rank = "第1名",
			award = "500钻石、5元公益基金",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"500钻石","5元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
		[5]=
		{
			id = 5,
			match_id = 3,
			rank = "第2名",
			award = "200钻石、2元公益基金",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"200钻石","2元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
		[6]=
		{
			id = 6,
			match_id = 3,
			rank = "第3名",
			award = "100钻石、1元公益基金",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100钻石","1元公益基金",},
			award_icon = {"com_icon_diamond","matchpop_icon_1"},
		},
	},
	config=
	{
		[1]=
		{
			id = 1,
			game_id = 2,
			game_name = "1元公益基金赛",
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			game_type = "game_DdzMatch",
			ui_order = 1,
			enter_condi_count = 2000,
			cup_image = "IOSTS_match_icon_banner1",
			match_time = "约4分钟",
			award = "100钻石、1元公益基金",
			enter_num = "满3人开赛",
			enter_image = "com_award_icon_jingbi",
			pay_id = 0,
			diamond_id = 1,
			round = {3,},
		},
		[2]=
		{
			id = 2,
			game_id = 3,
			game_name = "5元公益基金赛",
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			game_type = "game_DdzMatch",
			ui_order = 2,
			enter_condi_count = 10000,
			cup_image = "IOSTS_match_icon_banner2",
			match_time = "约4分钟",
			award = "500钻石、5元公益基金",
			enter_num = "满3人开赛",
			enter_image = "com_award_icon_jingbi",
			pay_id = 0,
			diamond_id = 1,
			round = {3,},
		},
	},
	gm_config=
	{
		[1]=
		{
			id = 1,
			game_name = "鲸鱼千元赛第 10期",
			game_id = 81,
			game_type = "game_DdzMatchNaming",
			game_type_name = "经典斗地主",
			ui_order = 9,
			is_local_icon = 1,
			game_icon = "com_award_icon_moeny3",
			start_time = 1547724600.000000,
			over_time = 1547726400.000000,
			show_time = 1547294400.000000,
			hide_time = 1547897400.000000,
			match_time = "约40分钟",
			enter_num = "96人以上",
			enter_condi_count = 100000,
			enter_condi_itemkey = {"prop_2","prop_1",},
			enter_condi_item_count = {1,100,},
			rank_num = 96,
			pay_id = 0,
			diamond_id = 1,
			round = {96,96,60,39,21,9,3},
		},
	},
	gm_award=
	{
		[1]=
		{
			id = 1,
			match_id = 81,
			rank = "第1名",
			award = "1000元(联系客服领取)",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000元",},
			award_icon = {"matchpop_icon_1",},
		},
		[2]=
		{
			id = 2,
			match_id = 81,
			rank = "第2名",
			award = "300元(联系客服领取)",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"1000元",},
			award_icon = {"matchpop_icon_1",},
		},
		[3]=
		{
			id = 3,
			match_id = 81,
			rank = "第3名",
			award = "100元(联系客服领取)",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1000元",},
			award_icon = {"matchpop_icon_1",},
		},
	},
}