return {
	tge=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			type = "goods",
			name = "钻  石",
			icon_image = "pay_icon_diamond",
			is_new_tag = 0,
			order_id = 3,
			is_show = 1,
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			type = "jing_bi",
			name = "鲸  币",
			icon_image = "pay_icon_jb",
			is_new_tag = 0,
			order_id = 1,
			is_show = 1,
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			type = "item",
			name = "道  具",
			icon_image = "pay_icon_dj",
			is_new_tag = 1,
			order_id = 2,
			is_show = 1,
		},
	},
	goods=
	{
		[1]=
		{
			line_id = 1,
			id = 101,
			convert_id = 101,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond6",
			shop_type = "shop",
			price = 600,
			buy_asset_type = {"diamond",},
			buy_asset_count = {400,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 1,
			gzh_show = 0,
			ui_order = 1,
			pay_title = "400钻石",
			ui_title = 400,
			ui_describe = "1元=66钻石",
			ui_price = "6元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[2]=
		{
			line_id = 2,
			id = 102,
			convert_id = 102,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond30",
			shop_type = "shop",
			price = 3000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {2000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 1,
			gzh_show = 0,
			ui_order = 6,
			pay_title = "2000钻石",
			ui_title = 2000,
			ui_describe = "1元=66钻石",
			ui_price = "30元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
		[3]=
		{
			line_id = 3,
			id = 103,
			convert_id = 103,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond98",
			shop_type = "shop",
			price = 9800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {6700,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 1,
			gzh_show = 0,
			ui_order = 7,
			pay_title = "6700钻石",
			ui_title = 6700,
			ui_describe = "1元=66钻石",
			ui_price = "98元",
			ui_icon = "pay_icon_diamond3",
			ui_icon_bg = "pay_bg_light2",
		},
		[4]=
		{
			line_id = 4,
			id = 104,
			convert_id = 104,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond198",
			shop_type = "shop",
			price = 19800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {13200,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 1,
			gzh_show = 0,
			ui_order = 8,
			pay_title = "1.32万钻石",
			ui_title = "1.32万",
			ui_describe = "1元=66钻石",
			ui_price = "198元",
			ui_icon = "pay_icon_diamond4",
			ui_icon_bg = "pay_bg_light2",
		},
		[5]=
		{
			line_id = 5,
			id = 105,
			convert_id = 105,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond298",
			shop_type = "shop",
			price = 29800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {20400,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 1,
			gzh_show = 0,
			ui_order = 9,
			pay_title = "2.04万钻石",
			ui_title = "2.04万",
			ui_describe = "1元=66钻石",
			ui_price = "298元",
			ui_icon = "pay_icon_diamond5",
			ui_icon_bg = "pay_bg_light2",
		},
		[6]=
		{
			line_id = 6,
			id = 106,
			convert_id = 106,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond1",
			shop_type = "shop",
			price = 100,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {20000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 0,
			pay_title = "2万鲸币",
			ui_title = "2万",
			ui_describe = "100钻=1万鲸币",
			ui_price = "1元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[7]=
		{
			line_id = 7,
			id = 107,
			convert_id = 107,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond3",
			shop_type = "shop",
			price = 300,
			buy_asset_type = {"diamond",},
			buy_asset_count = {200,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 0,
			pay_title = "200钻石",
			ui_title = 200,
			ui_describe = "1元=66钻石",
			ui_price = "3元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[8]=
		{
			line_id = 8,
			id = 108,
			convert_id = 108,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond8",
			shop_type = "shop",
			price = 800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {530,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 2,
			pay_title = "530钻石",
			ui_title = 530,
			ui_describe = "1元=66钻石",
			ui_price = "8元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[9]=
		{
			line_id = 9,
			id = 109,
			convert_id = 109,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond12",
			shop_type = "shop",
			price = 1200,
			buy_asset_type = {"diamond",},
			buy_asset_count = {800,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 3,
			pay_title = "800钻石",
			ui_title = 800,
			ui_describe = "1元=66钻石",
			ui_price = "12元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[10]=
		{
			line_id = 10,
			id = 110,
			convert_id = 110,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond18",
			shop_type = "shop",
			price = 1800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {1200,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 4,
			pay_title = "1200钻石",
			ui_title = 1200,
			ui_describe = "1元=66钻石",
			ui_price = "18元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
		[11]=
		{
			line_id = 11,
			id = 111,
			convert_id = 111,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond28",
			shop_type = "shop",
			price = 2800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {1860,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			is_show = 0,
			gzh_show = 0,
			ui_order = 5,
			pay_title = "1860钻石",
			ui_title = 1860,
			ui_describe = "1元=66钻石",
			ui_price = "28元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
	},
	gift_bag=
	{
		[1]=
		{
			line_id = 1,
			id = 7,
			on_off = 0,
			pay_title = "二元礼包",
			gzh_order = 7,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,3},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[2]=
		{
			line_id = 2,
			id = 8,
			on_off = 0,
			pay_title = "合伙人礼包",
			gzh_order = 8,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,4},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[3]=
		{
			line_id = 3,
			id = 9,
			on_off = 0,
			pay_title = "圣诞礼包",
			gzh_order = 9,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,5},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[4]=
		{
			line_id = 4,
			id = 10,
			product_id = "com.jyjjddz.zs.diamond1",
			on_off = 1,
			pay_title = "一元超值礼包",
			gzh_order = -4,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {20000,},
			buy_limt = 1,
			count = 99999999,
			valid_time = 0,
		},
		[5]=
		{
			line_id = 5,
			id = 11,
			on_off = 0,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -5,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi","shop_gold_sum","prop_2"},
			buy_asset_count = {10000,100,1},
			buy_limt = 0,
			count = 0,
			valid_time = 1,
		},
		[6]=
		{
			line_id = 6,
			id = 12,
			on_off = 1,
			pay_title = "金猪大礼包",
			gzh_order = -10,
			shop_type = "gift_bag",
			price = 19900,
			buy_asset_type = {"jing_bi","prop_hammer_2","jipaiqi","prop_2","prop_3","expression_54"},
			buy_asset_count = {180000,200,30,10,1,50},
			buy_limt = 0,
			count = 99999999,
			valid_time = 0,
		},
		[7]=
		{
			line_id = 7,
			id = 13,
			on_off = 1,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -6,
			shop_type = "gift_bag",
			price = 1000,
			buy_asset_type = {"jing_bi","prop_2"},
			buy_asset_count = {100000,1},
			buy_limt = 0,
			count = 9999999,
			valid_time = 0,
		},
	},
	jing_bi=
	{
		[1]=
		{
			line_id = 1,
			id = 101,
			platform = "ios",
			goods_id = 101,
			use_type = "diamond",
			use_count = 400,
			jing_bi = 40000,
			num = 40000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 3,
			ui_title = "4万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "6元",
			ui_icon = "pay_icon_gold3",
			ui_icon_bg = "pay_bg_light1",
		},
		[2]=
		{
			line_id = 2,
			id = 102,
			platform = "ios",
			goods_id = 102,
			use_type = "diamond",
			use_count = 2000,
			jing_bi = 200000,
			num = 200000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 4,
			ui_title = "20万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "30元",
			ui_icon = "pay_icon_gold4",
			ui_icon_bg = "pay_bg_light1",
		},
		[3]=
		{
			line_id = 3,
			id = 103,
			platform = "ios",
			goods_id = 103,
			use_type = "diamond",
			use_count = 6700,
			jing_bi = 670000,
			num = 670000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 5,
			ui_title = "67万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "98元",
			ui_icon = "pay_icon_gold5",
			ui_icon_bg = "pay_bg_light1",
		},
		[4]=
		{
			line_id = 4,
			id = 104,
			platform = "ios",
			goods_id = 104,
			use_type = "diamond",
			use_count = 13200,
			jing_bi = 1320000,
			num = 1320000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 6,
			ui_title = "132万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "198元",
			ui_icon = "pay_icon_gold6",
			ui_icon_bg = "pay_bg_light1",
		},
		[5]=
		{
			line_id = 5,
			id = 105,
			platform = "ios",
			goods_id = 105,
			use_type = "diamond",
			use_count = 20400,
			jing_bi = 2040000,
			num = 2040000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 7,
			ui_title = "204万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "298元",
			ui_icon = "pay_icon_gold7",
			ui_icon_bg = "pay_bg_light1",
		},
		[6]=
		{
			line_id = 6,
			id = 106,
			platform = "ios",
			goods_id = 101,
			use_type = "diamond",
			use_count = 100,
			jing_bi = 10000,
			num = 10000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 0,
			ui_order = 0,
			ui_title = "1万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = "1元",
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
		},
	},
	item=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			type = "room_card",
			use_type = "diamond",
			use_count = 300,
			num = 15,
			gift_asset_type = {"jing_bi",},
			gift_asset_count = {15000,},
			is_show = 1,
			ui_order = 4,
			ui_title = "15房卡",
			ui_givedesc = "额外送1.5万鲸币",
			ui_describe = "原价100钻=1房卡",
			ui_price = 300,
			ui_icon = "pay_icon_rc1",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 2,
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			type = "room_card",
			use_type = "diamond",
			use_count = 600,
			num = 30,
			gift_asset_type = {"jing_bi",},
			gift_asset_count = {30000,},
			is_show = 1,
			ui_order = 5,
			ui_title = "30房卡",
			ui_givedesc = "额外送3万鲸币",
			ui_describe = "原价100钻=1房卡",
			ui_price = 600,
			ui_icon = "pay_icon_rc2",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 2,
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			type = "room_card",
			use_type = "diamond",
			use_count = 3000,
			num = 150,
			gift_asset_type = {"jing_bi",},
			gift_asset_count = {150000,},
			is_show = 1,
			ui_order = 6,
			ui_title = "150房卡",
			ui_givedesc = "额外送15万鲸币",
			ui_describe = "原价100钻=1房卡",
			ui_price = 3000,
			ui_icon = "pay_icon_rc3",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 2,
		},
	},
}