return {
	config=
	{
		[1]=
		{
			id = 1,
			game_type = "game_LHD",
			game_name = "金蛋大乱斗-初级场",
			game_id = 1001,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 44,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			isOnOff = 1,
			isLock = 0,
		},
		[2]=
		{
			id = 2,
			game_type = "game_LHD",
			game_name = "金蛋大乱斗-中级场",
			game_id = 1002,
			order = 2,
			imageIndex = 2,
			base = 1000,
			enterMin = 60000,
			enterMax = -1,
			min_coin = 60000,
			max_coin = -1,
			gift_id = 45,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			isOnOff = 1,
			isLock = 0,
		},
		[3]=
		{
			id = 3,
			game_type = "game_LHD",
			game_name = "金蛋大乱斗-高级场",
			game_id = 1003,
			order = 3,
			imageIndex = 3,
			base = 10000,
			enterMin = 600000,
			enterMax = -1,
			min_coin = 600000,
			max_coin = -1,
			gift_id = 59,
			pay_id = 2,
			ios_pay_id = 102,
			diamond_id = 3,
			isOnOff = 1,
			isLock = 0,
		},
		[4]=
		{
			id = 4,
			game_type = "game_LHD",
			game_name = "金蛋大乱斗-乱斗场",
			game_id = 1004,
			order = 4,
			imageIndex = 4,
			base = 50000,
			enterMin = 1,
			enterMax = -1,
			min_coin = 1,
			max_coin = -1,
			gift_id = 62,
			pay_id = 4,
			ios_pay_id = 103,
			diamond_id = 4,
			isOnOff = 0,
			isLock = 1,
		},
		[5]=
		{
			id = 5,
			game_type = "game_LHD",
			game_name = "金蛋大乱斗-引导场",
			game_id = 1005,
			order = 5,
			imageIndex = 5,
			base = 1,
			enterMin = 100,
			enterMax = -1,
			min_coin = 100,
			max_coin = -1,
			gift_id = 44,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			isOnOff = 1,
			isLock = 0,
		},
	},
}