return {
	hbs=
	{
		[1]=
		{
			id = 1,
			game_tag = "hbs",
			award_id = 1,
			rank = "第1名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[2]=
		{
			id = 2,
			game_tag = "hbs",
			award_id = 1,
			rank = "第2名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[3]=
		{
			id = 3,
			game_tag = "hbs",
			award_id = 1,
			rank = "第3名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[4]=
		{
			id = 4,
			game_tag = "hbs",
			award_id = 2,
			rank = "第1名",
			award = "5福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[5]=
		{
			id = 5,
			game_tag = "hbs",
			award_id = 2,
			rank = "第2名",
			award = "2福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[6]=
		{
			id = 6,
			game_tag = "hbs",
			award_id = 2,
			rank = "第3名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[7]=
		{
			id = 7,
			game_tag = "hbs",
			award_id = 2,
			rank = "第4-6名",
			award = "6000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"6000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[8]=
		{
			id = 8,
			game_tag = "hbs",
			award_id = 2,
			rank = "第7-12名",
			award = "2500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[9]=
		{
			id = 9,
			game_tag = "hbs",
			award_id = 2,
			rank = "第13-24名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[10]=
		{
			id = 10,
			game_tag = "hbs",
			award_id = 3,
			rank = "第1名",
			award = "20福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[11]=
		{
			id = 11,
			game_tag = "hbs",
			award_id = 3,
			rank = "第2名",
			award = "8福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[12]=
		{
			id = 12,
			game_tag = "hbs",
			award_id = 3,
			rank = "第3名",
			award = "5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[13]=
		{
			id = 13,
			game_tag = "hbs",
			award_id = 3,
			rank = "第4-6名",
			award = "3.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"3.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[14]=
		{
			id = 14,
			game_tag = "hbs",
			award_id = 3,
			rank = "第7-12名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[15]=
		{
			id = 15,
			game_tag = "hbs",
			award_id = 3,
			rank = "第13-24名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[16]=
		{
			id = 16,
			game_tag = "hbs",
			award_id = 4,
			rank = "第1名",
			award = "100福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[17]=
		{
			id = 17,
			game_tag = "hbs",
			award_id = 4,
			rank = "第2名",
			award = "40福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"40福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[18]=
		{
			id = 18,
			game_tag = "hbs",
			award_id = 4,
			rank = "第3名",
			award = "25福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"25福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[19]=
		{
			id = 19,
			game_tag = "hbs",
			award_id = 4,
			rank = "第4-6名",
			award = "17.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"17.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[20]=
		{
			id = 20,
			game_tag = "hbs",
			award_id = 4,
			rank = "第7-12名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[21]=
		{
			id = 21,
			game_tag = "hbs",
			award_id = 4,
			rank = "第13-24名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[22]=
		{
			id = 22,
			game_tag = "hbs",
			award_id = 5,
			rank = "第1名",
			award = "5福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[23]=
		{
			id = 23,
			game_tag = "hbs",
			award_id = 5,
			rank = "第2名",
			award = "2福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[24]=
		{
			id = 24,
			game_tag = "hbs",
			award_id = 5,
			rank = "第3名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[25]=
		{
			id = 25,
			game_tag = "hbs",
			award_id = 5,
			rank = "第4名",
			award = "0.8福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"0.8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[26]=
		{
			id = 26,
			game_tag = "hbs",
			award_id = 5,
			rank = "第5-8名",
			award = "6000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"6000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[27]=
		{
			id = 27,
			game_tag = "hbs",
			award_id = 5,
			rank = "第9-16名",
			award = "2500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[28]=
		{
			id = 28,
			game_tag = "hbs",
			award_id = 5,
			rank = "第17-28名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[29]=
		{
			id = 29,
			game_tag = "hbs",
			award_id = 6,
			rank = "第1名",
			award = "20福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[30]=
		{
			id = 30,
			game_tag = "hbs",
			award_id = 6,
			rank = "第2名",
			award = "8福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[31]=
		{
			id = 31,
			game_tag = "hbs",
			award_id = 6,
			rank = "第3名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[32]=
		{
			id = 32,
			game_tag = "hbs",
			award_id = 6,
			rank = "第4名",
			award = "4福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"4福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[33]=
		{
			id = 33,
			game_tag = "hbs",
			award_id = 6,
			rank = "第5-8名",
			award = "3.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"3.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[34]=
		{
			id = 34,
			game_tag = "hbs",
			award_id = 6,
			rank = "第9-16名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[35]=
		{
			id = 35,
			game_tag = "hbs",
			award_id = 6,
			rank = "第17-28名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[36]=
		{
			id = 36,
			game_tag = "hbs",
			award_id = 7,
			rank = "第1名",
			award = "100福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[37]=
		{
			id = 37,
			game_tag = "hbs",
			award_id = 7,
			rank = "第2名",
			award = "40福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"40福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[38]=
		{
			id = 38,
			game_tag = "hbs",
			award_id = 7,
			rank = "第3名",
			award = "30福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"30福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[39]=
		{
			id = 39,
			game_tag = "hbs",
			award_id = 7,
			rank = "第4名",
			award = "20福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[40]=
		{
			id = 40,
			game_tag = "hbs",
			award_id = 7,
			rank = "第5-8名",
			award = "17.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"17.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[41]=
		{
			id = 41,
			game_tag = "hbs",
			award_id = 7,
			rank = "第9-16名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[42]=
		{
			id = 42,
			game_tag = "hbs",
			award_id = 7,
			rank = "第17-28名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[43]=
		{
			id = 43,
			game_tag = "hbs",
			award_id = 8,
			rank = "第1名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[44]=
		{
			id = 44,
			game_tag = "hbs",
			award_id = 8,
			rank = "第2名",
			award = "5000鲸币",
			icon = "matchpop_icon_6",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"5000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[45]=
		{
			id = 45,
			game_tag = "hbs",
			award_id = 8,
			rank = "第3名",
			award = "3000鲸币",
			icon = "matchpop_icon_5",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"3000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[46]=
		{
			id = 46,
			game_tag = "hbs",
			award_id = 8,
			rank = "第4-6名",
			award = "1500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"1500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[47]=
		{
			id = 47,
			game_tag = "hbs",
			award_id = 8,
			rank = "第7-12名",
			award = "1200鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"1200鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[48]=
		{
			id = 48,
			game_tag = "hbs",
			award_id = 8,
			rank = "第13-24名",
			award = "1000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"1000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[49]=
		{
			id = 49,
			game_tag = "hbs",
			award_id = 8,
			rank = "第25-36名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 25,
			max_rank = 36,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[50]=
		{
			id = 50,
			game_tag = "hbs",
			award_id = 8,
			rank = "第37-48名",
			award = "200鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 37,
			max_rank = 48,
			award_desc = {"200鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[51]=
		{
			id = 51,
			game_tag = "hbs",
			award_id = 9,
			rank = "第1名",
			award = "50福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[52]=
		{
			id = 52,
			game_tag = "hbs",
			award_id = 9,
			rank = "第2名",
			award = "20福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[53]=
		{
			id = 53,
			game_tag = "hbs",
			award_id = 9,
			rank = "第3名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[54]=
		{
			id = 54,
			game_tag = "hbs",
			award_id = 9,
			rank = "第4-6名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[55]=
		{
			id = 55,
			game_tag = "hbs",
			award_id = 9,
			rank = "第7-12名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[56]=
		{
			id = 56,
			game_tag = "hbs",
			award_id = 9,
			rank = "第13-24名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[57]=
		{
			id = 57,
			game_tag = "hbs",
			award_id = 10,
			rank = "第1名",
			award = "50福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[58]=
		{
			id = 58,
			game_tag = "hbs",
			award_id = 10,
			rank = "第2名",
			award = "20福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[59]=
		{
			id = 59,
			game_tag = "hbs",
			award_id = 10,
			rank = "第3名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[60]=
		{
			id = 60,
			game_tag = "hbs",
			award_id = 10,
			rank = "第4名",
			award = "8福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[61]=
		{
			id = 61,
			game_tag = "hbs",
			award_id = 10,
			rank = "第5-8名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[62]=
		{
			id = 62,
			game_tag = "hbs",
			award_id = 10,
			rank = "第9-16名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[63]=
		{
			id = 63,
			game_tag = "hbs",
			award_id = 10,
			rank = "第17-28名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
	},
	hbs_mj=
	{
		[1]=
		{
			id = 1,
			game_tag = "hbs_mj",
			award_id = 1,
			rank = "第1名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[2]=
		{
			id = 2,
			game_tag = "hbs_mj",
			award_id = 1,
			rank = "第2名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[3]=
		{
			id = 3,
			game_tag = "hbs_mj",
			award_id = 1,
			rank = "第3名",
			award = "0.8福卡，6000鲸币",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"0.8福卡","6000鲸币",},
			award_icon = {"matchpop_icon_1","matchpop_icon_4",},
		},
		[4]=
		{
			id = 4,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第1名",
			award = "5福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[5]=
		{
			id = 5,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第2名",
			award = "2福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[6]=
		{
			id = 6,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第3名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[7]=
		{
			id = 7,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第4-6名",
			award = "6000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"6000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[8]=
		{
			id = 8,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第7-12名",
			award = "2500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[9]=
		{
			id = 9,
			game_tag = "hbs_mj",
			award_id = 2,
			rank = "第13-24名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[10]=
		{
			id = 10,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第1名",
			award = "20福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[11]=
		{
			id = 11,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第2名",
			award = "8福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[12]=
		{
			id = 12,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第3名",
			award = "5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[13]=
		{
			id = 13,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第4-6名",
			award = "3.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"3.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[14]=
		{
			id = 14,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第7-12名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[15]=
		{
			id = 15,
			game_tag = "hbs_mj",
			award_id = 3,
			rank = "第13-24名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[16]=
		{
			id = 16,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第1名",
			award = "100福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[17]=
		{
			id = 17,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第2名",
			award = "40福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"40福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[18]=
		{
			id = 18,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第3名",
			award = "25福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"25福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[19]=
		{
			id = 19,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第4-6名",
			award = "17.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"17.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[20]=
		{
			id = 20,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第7-12名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[21]=
		{
			id = 21,
			game_tag = "hbs_mj",
			award_id = 4,
			rank = "第13-24名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[22]=
		{
			id = 22,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第1名",
			award = "5福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[23]=
		{
			id = 23,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第2名",
			award = "2福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[24]=
		{
			id = 24,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第3名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[25]=
		{
			id = 25,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第4名",
			award = "0.8福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"0.8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[26]=
		{
			id = 26,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第5-8名",
			award = "6000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"6000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[27]=
		{
			id = 27,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第9-16名",
			award = "2500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[28]=
		{
			id = 28,
			game_tag = "hbs_mj",
			award_id = 5,
			rank = "第17-28名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[29]=
		{
			id = 29,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第1名",
			award = "20福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[30]=
		{
			id = 30,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第2名",
			award = "8福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[31]=
		{
			id = 31,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第3名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[32]=
		{
			id = 32,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第4名",
			award = "4福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"4福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[33]=
		{
			id = 33,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第5-8名",
			award = "3.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"3.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[34]=
		{
			id = 34,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第9-16名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[35]=
		{
			id = 35,
			game_tag = "hbs_mj",
			award_id = 6,
			rank = "第17-28名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[36]=
		{
			id = 36,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第1名",
			award = "100福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[37]=
		{
			id = 37,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第2名",
			award = "40福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"40福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[38]=
		{
			id = 38,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第3名",
			award = "30福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"30福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[39]=
		{
			id = 39,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第4名",
			award = "20福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[40]=
		{
			id = 40,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第5-8名",
			award = "17.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"17.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[41]=
		{
			id = 41,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第9-16名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[42]=
		{
			id = 42,
			game_tag = "hbs_mj",
			award_id = 7,
			rank = "第17-28名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[43]=
		{
			id = 43,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第1名",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[44]=
		{
			id = 44,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第2名",
			award = "5000鲸币",
			icon = "matchpop_icon_6",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"5000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[45]=
		{
			id = 45,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第3名",
			award = "3000鲸币",
			icon = "matchpop_icon_5",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"3000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[46]=
		{
			id = 46,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第4-6名",
			award = "1500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"1500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[47]=
		{
			id = 47,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第7-12名",
			award = "1200鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"1200鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[48]=
		{
			id = 48,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第13-24名",
			award = "1000鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"1000鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[49]=
		{
			id = 49,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第25-36名",
			award = "500鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 25,
			max_rank = 36,
			award_desc = {"500鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[50]=
		{
			id = 50,
			game_tag = "hbs_mj",
			award_id = 8,
			rank = "第37-48名",
			award = "200鲸币",
			icon = "matchpop_icon_4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 37,
			max_rank = 48,
			award_desc = {"200鲸币",},
			award_icon = {"matchpop_icon_4",},
		},
		[51]=
		{
			id = 51,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第1名",
			award = "50福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[52]=
		{
			id = 52,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第2名",
			award = "20福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[53]=
		{
			id = 53,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第3名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[54]=
		{
			id = 54,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第4-6名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 6,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[55]=
		{
			id = 55,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第7-12名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 7,
			max_rank = 12,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[56]=
		{
			id = 56,
			game_tag = "hbs_mj",
			award_id = 9,
			rank = "第13-24名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 13,
			max_rank = 24,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[57]=
		{
			id = 57,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第1名",
			award = "50福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[58]=
		{
			id = 58,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第2名",
			award = "20福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[59]=
		{
			id = 59,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第3名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[60]=
		{
			id = 60,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第4名",
			award = "8福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 4,
			award_desc = {"8福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[61]=
		{
			id = 61,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第5-8名",
			award = "6福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 5,
			max_rank = 8,
			award_desc = {"6福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[62]=
		{
			id = 62,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第9-16名",
			award = "2.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 9,
			max_rank = 16,
			award_desc = {"2.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[63]=
		{
			id = 63,
			game_tag = "hbs_mj",
			award_id = 10,
			rank = "第17-28名",
			award = "0.5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 17,
			max_rank = 28,
			award_desc = {"0.5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
	},
	gms=
	{
		[1]=
		{
			id = 1,
			game_tag = "gms",
			award_id = 1,
			rank = "第1名",
			award = "1000福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[2]=
		{
			id = 2,
			game_tag = "gms",
			award_id = 1,
			rank = "第2名",
			award = "300福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[3]=
		{
			id = 3,
			game_tag = "gms",
			award_id = 1,
			rank = "第3名",
			award = "100福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[4]=
		{
			id = 4,
			game_tag = "gms",
			award_id = 1,
			rank = "第4-9名",
			award = "50福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[5]=
		{
			id = 5,
			game_tag = "gms",
			award_id = 1,
			rank = "第10-21名",
			award = "30福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[6]=
		{
			id = 6,
			game_tag = "gms",
			award_id = 1,
			rank = "第22-39名",
			award = "20福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[7]=
		{
			id = 7,
			game_tag = "gms",
			award_id = 1,
			rank = "第40-60名",
			award = "15福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[8]=
		{
			id = 8,
			game_tag = "gms",
			award_id = 1,
			rank = "第61-96名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[9]=
		{
			id = 9,
			game_tag = "gms",
			award_id = 1,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[10]=
		{
			id = 10,
			game_tag = "gms",
			award_id = 2,
			rank = "第1名",
			award = "1万元+周年感恩赛门票",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1万元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_3","com_award_icon_znq"},
		},
		[11]=
		{
			id = 11,
			game_tag = "gms",
			award_id = 2,
			rank = "第2名",
			award = "3000元+周年感恩赛门票",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"3000元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_2","com_award_icon_znq"},
		},
		[12]=
		{
			id = 12,
			game_tag = "gms",
			award_id = 2,
			rank = "第3名",
			award = "1000元+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1000元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[13]=
		{
			id = 13,
			game_tag = "gms",
			award_id = 2,
			rank = "第4-9名",
			award = "500福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"500元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[14]=
		{
			id = 14,
			game_tag = "gms",
			award_id = 2,
			rank = "第10-18名",
			award = "300福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 18,
			award_desc = {"300元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[15]=
		{
			id = 15,
			game_tag = "gms",
			award_id = 2,
			rank = "第19-33名",
			award = "100福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 19,
			max_rank = 33,
			award_desc = {"100元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[16]=
		{
			id = 16,
			game_tag = "gms",
			award_id = 2,
			rank = "第34-48名",
			award = "50福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 34,
			max_rank = 48,
			award_desc = {"50元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[17]=
		{
			id = 17,
			game_tag = "gms",
			award_id = 2,
			rank = "第49-72名",
			award = "20福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 49,
			max_rank = 72,
			award_desc = {"20元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[18]=
		{
			id = 18,
			game_tag = "gms",
			award_id = 2,
			rank = "第73-108名",
			award = "10福卡+周年感恩赛门票",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 73,
			max_rank = 108,
			award_desc = {"10元","周年感恩赛门票",},
			award_icon = {"matchpop_icon_1","com_award_icon_znq"},
		},
		[19]=
		{
			id = 19,
			game_tag = "gms",
			award_id = 2,
			rank = "109-162名",
			award = "5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 109,
			max_rank = 162,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[20]=
		{
			id = 20,
			game_tag = "gms",
			award_id = 2,
			rank = "163-240名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 163,
			max_rank = 240,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[21]=
		{
			id = 21,
			game_tag = "gms",
			award_id = 2,
			rank = "241名之后",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 241,
			max_rank = 999999,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
	},
	sws=
	{
		[1]=
		{
			id = 1,
			game_tag = "sws",
			award_id = 1,
			rank = "第1名",
			award = "打火机，口红二选一",
			icon = "matchpop_icon_10",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"打火机，口红二选一",},
			award_icon = {"matchpop_icon_10",},
		},
		[2]=
		{
			id = 2,
			game_tag = "sws",
			award_id = 1,
			rank = "第2名",
			award = "20福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[3]=
		{
			id = 3,
			game_tag = "sws",
			award_id = 1,
			rank = "第3名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[4]=
		{
			id = 4,
			game_tag = "sws",
			award_id = 1,
			rank = "第4-9名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[5]=
		{
			id = 5,
			game_tag = "sws",
			award_id = 1,
			rank = "第10-21名",
			award = "木锤×5",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"木锤×5",},
			award_icon = {"com_award_icon_cz2",},
		},
		[6]=
		{
			id = 6,
			game_tag = "sws",
			award_id = 1,
			rank = "第22-48名",
			award = "木锤×1",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 48,
			award_desc = {"木锤×1",},
			award_icon = {"com_award_icon_cz2",},
		},
	},
	qys=
	{
		[1]=
		{
			id = 1,
			game_tag = "qys",
			award_id = 1,
			rank = "第1名",
			award = "现场领奖",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"现场领奖",},
			award_icon = {"matchpop_icon_3",},
		},
		[2]=
		{
			id = 2,
			game_tag = "qys",
			award_id = 1,
			rank = "第2名",
			award = "现场领奖",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"现场领奖",},
			award_icon = {"matchpop_icon_3",},
		},
		[3]=
		{
			id = 3,
			game_tag = "qys",
			award_id = 1,
			rank = "第3名",
			award = "现场领奖",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"现场领奖",},
			award_icon = {"matchpop_icon_3",},
		},
		[4]=
		{
			id = 4,
			game_tag = "qys",
			award_id = 2,
			rank = "第1-60名",
			award = "现场领奖",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 60,
			award_desc = {"现场领奖",},
			award_icon = {"matchpop_icon_3",},
		},
	},
	mxb=
	{
		[1]=
		{
			id = 1,
			game_tag = "mxb",
			award_id = 1,
			rank = "第1名",
			award = "1000福卡",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[2]=
		{
			id = 2,
			game_tag = "mxb",
			award_id = 1,
			rank = "第2名",
			award = "300福卡",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[3]=
		{
			id = 3,
			game_tag = "mxb",
			award_id = 1,
			rank = "第3名",
			award = "100福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[4]=
		{
			id = 4,
			game_tag = "mxb",
			award_id = 1,
			rank = "第4-9名",
			award = "50福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[5]=
		{
			id = 5,
			game_tag = "mxb",
			award_id = 1,
			rank = "第10-21名",
			award = "30福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[6]=
		{
			id = 6,
			game_tag = "mxb",
			award_id = 1,
			rank = "第22-39名",
			award = "20福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[7]=
		{
			id = 7,
			game_tag = "mxb",
			award_id = 1,
			rank = "第40-60名",
			award = "15福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[8]=
		{
			id = 8,
			game_tag = "mxb",
			award_id = 1,
			rank = "第61-96名",
			award = "10福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[9]=
		{
			id = 9,
			game_tag = "mxb",
			award_id = 1,
			rank = "96名之后",
			award = "5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 9999,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
	},
	ges=
	{
		[1]=
		{
			id = 1,
			game_tag = "ges",
			award_id = 1,
			rank = "第1名",
			award = "5g金条+10斤长谷子大米",
			icon = "settlement_icon_jp4",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"5g金条","10斤长谷子大米",},
			award_icon = {"settlement_icon_jp4","settlement_icon_jp1"},
		},
		[2]=
		{
			id = 2,
			game_tag = "ges",
			award_id = 1,
			rank = "第2名",
			award = "2g金条+10斤长谷子大米",
			icon = "settlement_icon_jp3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"2g金条","10斤长谷子大米",},
			award_icon = {"settlement_icon_jp3","settlement_icon_jp1"},
		},
		[3]=
		{
			id = 3,
			game_tag = "ges",
			award_id = 1,
			rank = "第3名",
			award = "1g金条+10斤长谷子大米",
			icon = "settlement_icon_jp2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"1g金条","10斤长谷子大米",},
			award_icon = {"settlement_icon_jp2","settlement_icon_jp1"},
		},
		[4]=
		{
			id = 4,
			game_tag = "ges",
			award_id = 1,
			rank = "第4-9名",
			award = "200福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"200福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[5]=
		{
			id = 5,
			game_tag = "ges",
			award_id = 1,
			rank = "第10-18名",
			award = "100福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 18,
			award_desc = {"100福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[6]=
		{
			id = 6,
			game_tag = "ges",
			award_id = 1,
			rank = "第19-33名",
			award = "50福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 19,
			max_rank = 33,
			award_desc = {"50福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[7]=
		{
			id = 7,
			game_tag = "ges",
			award_id = 1,
			rank = "第34-48名",
			award = "30福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 34,
			max_rank = 48,
			award_desc = {"30福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[8]=
		{
			id = 8,
			game_tag = "ges",
			award_id = 1,
			rank = "第49-72名",
			award = "20福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 49,
			max_rank = 72,
			award_desc = {"20福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[9]=
		{
			id = 9,
			game_tag = "ges",
			award_id = 1,
			rank = "第73-108名",
			award = "10福卡+10斤长谷子大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 73,
			max_rank = 108,
			award_desc = {"10福卡","10斤长谷子大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[10]=
		{
			id = 10,
			game_tag = "ges",
			award_id = 1,
			rank = "109-162名",
			award = "5福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 109,
			max_rank = 162,
			award_desc = {"5福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[11]=
		{
			id = 11,
			game_tag = "ges",
			award_id = 1,
			rank = "163-240名",
			award = "2福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 163,
			max_rank = 240,
			award_desc = {"2福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[12]=
		{
			id = 12,
			game_tag = "ges",
			award_id = 1,
			rank = "241名之后",
			award = "1福卡",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 241,
			max_rank = 99999,
			award_desc = {"1福卡",},
			award_icon = {"matchpop_icon_1",},
		},
		[13]=
		{
			id = 13,
			game_tag = "ges",
			award_id = 2,
			rank = "第1名",
			award = "1000福卡+10斤稻花香大米",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[14]=
		{
			id = 14,
			game_tag = "ges",
			award_id = 2,
			rank = "第2名",
			award = "300福卡+10斤稻花香大米",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[15]=
		{
			id = 15,
			game_tag = "ges",
			award_id = 2,
			rank = "第3名",
			award = "100福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[16]=
		{
			id = 16,
			game_tag = "ges",
			award_id = 2,
			rank = "第4-9名",
			award = "50福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","+10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[17]=
		{
			id = 17,
			game_tag = "ges",
			award_id = 2,
			rank = "第10-21名",
			award = "30福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[18]=
		{
			id = 18,
			game_tag = "ges",
			award_id = 2,
			rank = "第22-39名",
			award = "20福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[19]=
		{
			id = 19,
			game_tag = "ges",
			award_id = 2,
			rank = "第40-60名",
			award = "15福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[20]=
		{
			id = 20,
			game_tag = "ges",
			award_id = 2,
			rank = "第61-96名",
			award = "10福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[21]=
		{
			id = 21,
			game_tag = "ges",
			award_id = 2,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[22]=
		{
			id = 22,
			game_tag = "ges",
			award_id = 3,
			rank = "第1名",
			award = "1000福卡+10斤扶贫大米",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","10斤扶贫大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[23]=
		{
			id = 23,
			game_tag = "ges",
			award_id = 3,
			rank = "第2名",
			award = "300福卡+10斤扶贫大米",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","10斤扶贫大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[24]=
		{
			id = 24,
			game_tag = "ges",
			award_id = 3,
			rank = "第3名",
			award = "100福卡+10斤扶贫大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","10斤扶贫大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[25]=
		{
			id = 25,
			game_tag = "ges",
			award_id = 3,
			rank = "第4-9名",
			award = "50福卡+10斤扶贫大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","10斤扶贫大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[26]=
		{
			id = 26,
			game_tag = "ges",
			award_id = 3,
			rank = "第10-21名",
			award = "30福卡+10斤扶贫大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","10斤扶贫大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[27]=
		{
			id = 27,
			game_tag = "ges",
			award_id = 3,
			rank = "第22-39名",
			award = "20福卡+铜梁鹌鹑蛋面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","铜梁鹌鹑蛋面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift91_gm"},
		},
		[28]=
		{
			id = 28,
			game_tag = "ges",
			award_id = 3,
			rank = "第40-60名",
			award = "15福卡+铜梁鹌鹑蛋面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","铜梁鹌鹑蛋面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift91_gm"},
		},
		[29]=
		{
			id = 29,
			game_tag = "ges",
			award_id = 3,
			rank = "第61-96名",
			award = "10福卡+铜梁鹌鹑蛋面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","铜梁鹌鹑蛋面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift91_gm"},
		},
		[30]=
		{
			id = 30,
			game_tag = "ges",
			award_id = 3,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[31]=
		{
			id = 31,
			game_tag = "ges",
			award_id = 4,
			rank = "第1名",
			award = "1000福卡+10斤稻花香大米",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[32]=
		{
			id = 32,
			game_tag = "ges",
			award_id = 4,
			rank = "第2名",
			award = "300福卡+10斤稻花香大米",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[33]=
		{
			id = 33,
			game_tag = "ges",
			award_id = 4,
			rank = "第3名",
			award = "100福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[34]=
		{
			id = 34,
			game_tag = "ges",
			award_id = 4,
			rank = "第4-9名",
			award = "50福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","+10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[35]=
		{
			id = 35,
			game_tag = "ges",
			award_id = 4,
			rank = "第10-21名",
			award = "30福卡+10斤稻花香大米",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","10斤稻花香大米",},
			award_icon = {"matchpop_icon_1","settlement_icon_jp1"},
		},
		[36]=
		{
			id = 36,
			game_tag = "ges",
			award_id = 4,
			rank = "第22-39名",
			award = "20福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[37]=
		{
			id = 37,
			game_tag = "ges",
			award_id = 4,
			rank = "第40-60名",
			award = "15福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[38]=
		{
			id = 38,
			game_tag = "ges",
			award_id = 4,
			rank = "第61-96名",
			award = "10福卡+3斤敦煌有机红枣",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","3斤敦煌有机红枣",},
			award_icon = {"matchpop_icon_1","activity_icon_gift67"},
		},
		[39]=
		{
			id = 39,
			game_tag = "ges",
			award_id = 4,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[40]=
		{
			id = 40,
			game_tag = "ges",
			award_id = 5,
			rank = "第1名",
			award = "1000福卡+抑菌洗手液",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[41]=
		{
			id = 41,
			game_tag = "ges",
			award_id = 5,
			rank = "第2名",
			award = "300福卡+抑菌洗手液",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[42]=
		{
			id = 42,
			game_tag = "ges",
			award_id = 5,
			rank = "第3名",
			award = "100福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[43]=
		{
			id = 43,
			game_tag = "ges",
			award_id = 5,
			rank = "第4-9名",
			award = "50福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[44]=
		{
			id = 44,
			game_tag = "ges",
			award_id = 5,
			rank = "第10-21名",
			award = "30福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[45]=
		{
			id = 45,
			game_tag = "ges",
			award_id = 5,
			rank = "第22-39名",
			award = "20福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[46]=
		{
			id = 46,
			game_tag = "ges",
			award_id = 5,
			rank = "第40-60名",
			award = "15福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[47]=
		{
			id = 47,
			game_tag = "ges",
			award_id = 5,
			rank = "第61-96名",
			award = "10福卡+抑菌洗手液",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","抑菌洗手液",},
			award_icon = {"matchpop_icon_1","activity_icon_gift128_xsy"},
		},
		[48]=
		{
			id = 48,
			game_tag = "ges",
			award_id = 5,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[49]=
		{
			id = 49,
			game_tag = "ges",
			award_id = 6,
			rank = "第1名",
			award = "1000福卡+金龙鱼挂面",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[50]=
		{
			id = 50,
			game_tag = "ges",
			award_id = 6,
			rank = "第2名",
			award = "300福卡+金龙鱼挂面",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[51]=
		{
			id = 51,
			game_tag = "ges",
			award_id = 6,
			rank = "第3名",
			award = "100福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[52]=
		{
			id = 52,
			game_tag = "ges",
			award_id = 6,
			rank = "第4-9名",
			award = "50福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[53]=
		{
			id = 53,
			game_tag = "ges",
			award_id = 6,
			rank = "第10-21名",
			award = "30福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[54]=
		{
			id = 54,
			game_tag = "ges",
			award_id = 6,
			rank = "第22-39名",
			award = "20福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[55]=
		{
			id = 55,
			game_tag = "ges",
			award_id = 6,
			rank = "第40-60名",
			award = "15福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[56]=
		{
			id = 56,
			game_tag = "ges",
			award_id = 6,
			rank = "第61-96名",
			award = "10福卡+金龙鱼挂面",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","金龙鱼挂面",},
			award_icon = {"matchpop_icon_1","activity_icon_gift136_jlygm"},
		},
		[57]=
		{
			id = 57,
			game_tag = "ges",
			award_id = 6,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[58]=
		{
			id = 58,
			game_tag = "ges",
			award_id = 7,
			rank = "第1名",
			award = "1000福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"1000福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[59]=
		{
			id = 59,
			game_tag = "ges",
			award_id = 7,
			rank = "第2名",
			award = "300福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"300福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[60]=
		{
			id = 60,
			game_tag = "ges",
			award_id = 7,
			rank = "第3名",
			award = "100福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"100福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[61]=
		{
			id = 61,
			game_tag = "ges",
			award_id = 7,
			rank = "第4-9名",
			award = "50福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[62]=
		{
			id = 62,
			game_tag = "ges",
			award_id = 7,
			rank = "第10-21名",
			award = "30福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[63]=
		{
			id = 63,
			game_tag = "ges",
			award_id = 7,
			rank = "第22-39名",
			award = "20福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[64]=
		{
			id = 64,
			game_tag = "ges",
			award_id = 7,
			rank = "第40-60名",
			award = "15福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[65]=
		{
			id = 65,
			game_tag = "ges",
			award_id = 7,
			rank = "第61-96名",
			award = "10福卡+珊瑚绒毛巾",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","珊瑚绒毛巾",},
			award_icon = {"matchpop_icon_1","activity_icon_gift152_shrmj"},
		},
		[66]=
		{
			id = 66,
			game_tag = "ges",
			award_id = 7,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[67]=
		{
			id = 67,
			game_tag = "ges",
			award_id = 8,
			rank = "第1名",
			award = "美的空调+黄桃罐头",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"美的空调","黄桃罐头",},
			award_icon = {"activity_icon_gift162_kt","activity_icon_gift166_htgt"},
		},
		[68]=
		{
			id = 68,
			game_tag = "ges",
			award_id = 8,
			rank = "第2名",
			award = "美的电饭锅+黄桃罐头",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"美的电饭锅","黄桃罐头",},
			award_icon = {"activity_icon_gift167_mddfb","activity_icon_gift166_htgt"},
		},
		[69]=
		{
			id = 69,
			game_tag = "ges",
			award_id = 8,
			rank = "第3名",
			award = "美的风扇+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"美的风扇","黄桃罐头",},
			award_icon = {"activity_icon_gift153_fs","activity_icon_gift166_htgt"},
		},
		[70]=
		{
			id = 70,
			game_tag = "ges",
			award_id = 8,
			rank = "第4-9名",
			award = "50福卡+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","黄桃罐头",},
			award_icon = {"matchpop_icon_1","activity_icon_gift166_htgt"},
		},
		[71]=
		{
			id = 71,
			game_tag = "ges",
			award_id = 8,
			rank = "第10-21名",
			award = "30福卡+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","黄桃罐头",},
			award_icon = {"matchpop_icon_1","activity_icon_gift166_htgt"},
		},
		[72]=
		{
			id = 72,
			game_tag = "ges",
			award_id = 8,
			rank = "第22-39名",
			award = "20福卡+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","黄桃罐头",},
			award_icon = {"matchpop_icon_1","activity_icon_gift166_htgt"},
		},
		[73]=
		{
			id = 73,
			game_tag = "ges",
			award_id = 8,
			rank = "第40-60名",
			award = "15福卡+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","黄桃罐头",},
			award_icon = {"matchpop_icon_1","activity_icon_gift166_htgt"},
		},
		[74]=
		{
			id = 74,
			game_tag = "ges",
			award_id = 8,
			rank = "第61-96名",
			award = "10福卡+黄桃罐头",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","黄桃罐头",},
			award_icon = {"matchpop_icon_1","activity_icon_gift166_htgt"},
		},
		[75]=
		{
			id = 75,
			game_tag = "ges",
			award_id = 8,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
		[76]=
		{
			id = 76,
			game_tag = "ges",
			award_id = 9,
			rank = "第1名",
			award = "美的冰箱+小麻花",
			icon = "matchpop_icon_3",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 1,
			max_rank = 1,
			award_desc = {"美的冰箱","小麻花",},
			award_icon = {"activity_icon_gift192_bx","activity_icon_gift191_xmh"},
		},
		[77]=
		{
			id = 77,
			game_tag = "ges",
			award_id = 9,
			rank = "第2名",
			award = "美的微波炉+小麻花",
			icon = "matchpop_icon_2",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 2,
			max_rank = 2,
			award_desc = {"美的微波炉","小麻花",},
			award_icon = {"activity_icon_gift193_wbl","activity_icon_gift191_xmh"},
		},
		[78]=
		{
			id = 78,
			game_tag = "ges",
			award_id = 9,
			rank = "第3名",
			award = "美的榨汁机+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 3,
			max_rank = 3,
			award_desc = {"美的榨汁机","小麻花",},
			award_icon = {"activity_icon_gift194_zzj","activity_icon_gift191_xmh"},
		},
		[79]=
		{
			id = 79,
			game_tag = "ges",
			award_id = 9,
			rank = "第4-9名",
			award = "50福卡+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 4,
			max_rank = 9,
			award_desc = {"50福卡","小麻花",},
			award_icon = {"matchpop_icon_1","activity_icon_gift191_xmh"},
		},
		[80]=
		{
			id = 80,
			game_tag = "ges",
			award_id = 9,
			rank = "第10-21名",
			award = "30福卡+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 10,
			max_rank = 21,
			award_desc = {"30福卡","小麻花",},
			award_icon = {"matchpop_icon_1","activity_icon_gift191_xmh"},
		},
		[81]=
		{
			id = 81,
			game_tag = "ges",
			award_id = 9,
			rank = "第22-39名",
			award = "20福卡+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 22,
			max_rank = 39,
			award_desc = {"20福卡","小麻花",},
			award_icon = {"matchpop_icon_1","activity_icon_gift191_xmh"},
		},
		[82]=
		{
			id = 82,
			game_tag = "ges",
			award_id = 9,
			rank = "第40-60名",
			award = "15福卡+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 40,
			max_rank = 60,
			award_desc = {"15福卡","小麻花",},
			award_icon = {"matchpop_icon_1","activity_icon_gift191_xmh"},
		},
		[83]=
		{
			id = 83,
			game_tag = "ges",
			award_id = 9,
			rank = "第61-96名",
			award = "10福卡+小麻花",
			icon = "matchpop_icon_1",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 61,
			max_rank = 96,
			award_desc = {"10福卡","小麻花",},
			award_icon = {"matchpop_icon_1","activity_icon_gift191_xmh"},
		},
		[84]=
		{
			id = 84,
			game_tag = "ges",
			award_id = 9,
			rank = "第97-258名",
			award = "千元大奖赛门票",
			icon = "com_award_icon_qys",
			is_local_icon = 1,
			is_show = 1,
			min_rank = 97,
			max_rank = 258,
			award_desc = {"千元大奖赛门票",},
			award_icon = {"com_award_icon_qys",},
		},
	},
}