return {
	hbs=
	{
		[1]=
		{
			id = 1,
			game_tag = "hbs",
			type_id = 1,
			game_type = "game_DdzMatch",
			pay_id = 0,
			ios_pay_id = 0,
			gift_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_jingbi",
			is_local_icon = 1,
			cup_image = "match_icon_banner5",
			match_time = "约8分钟",
			award = "免费鲸币",
			enter_num = "满3人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[2]=
		{
			id = 2,
			game_tag = "hbs",
			type_id = 2,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"prop_5y","prop_1","jing_bi",},
			enter_condi_item_count = {1,5,5000,},
			round = {36,24,12,6,3},
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 76,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner5",
			match_time = "约8分钟",
			award = "5红包券",
			enter_num = "满36人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[3]=
		{
			id = 3,
			game_tag = "hbs",
			type_id = 3,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"prop_20y","prop_1","jing_bi",},
			enter_condi_item_count = {1,30,30000,},
			round = {36,24,12,6,3},
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 77,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner1",
			match_time = "约8分钟",
			award = "20红包券",
			enter_num = "满36人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[4]=
		{
			id = 4,
			game_tag = "hbs",
			type_id = 4,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"prop_100y","prop_1","jing_bi",},
			enter_condi_item_count = {1,150,150000,},
			round = {36,24,12,6,3},
			pay_id = 2,
			ios_pay_id = 102,
			gift_id = 82,
			diamond_id = 2,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner2",
			match_time = "约8分钟",
			award = "100红包券",
			enter_num = "满36人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[5]=
		{
			id = 5,
			game_tag = "hbs",
			type_id = 8,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"prop_5","jing_bi",},
			enter_condi_item_count = {1,1200,},
			round = {48,36,24,12,6,3},
			pay_id = 0,
			ios_pay_id = 0,
			gift_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner11",
			match_time = "约8分钟",
			award = "1红包券",
			enter_num = "满48人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[6]=
		{
			id = 6,
			game_tag = "hbs",
			type_id = 9,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"prop_50y","prop_1","jing_bi",},
			enter_condi_item_count = {1,50,50000,},
			round = {36,24,12,6,3},
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 80,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner11",
			match_time = "约8分钟",
			award = "50红包券",
			enter_num = "满36人开赛",
			enter_image = "com_award_icon_jingbi",
		},
	},
	hbs_mj=
	{
		[1]=
		{
			id = 1,
			game_tag = "hbs_mj",
			type_id = 5,
			game_type = "game_MjXzMatch3D",
			enter_condi_itemkey = {"prop_5y","prop_1","jing_bi",},
			enter_condi_item_count = {1,5,5000,},
			round = {40,28,16,8,4},
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 78,
			diamond_id = 1,
			game_type_name = "血战到底",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner3",
			match_time = "约8分钟",
			award = "5红包券",
			enter_num = "满40人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[2]=
		{
			id = 2,
			game_tag = "hbs_mj",
			type_id = 6,
			game_type = "game_MjXzMatch3D",
			enter_condi_itemkey = {"prop_20y","prop_1","jing_bi",},
			enter_condi_item_count = {1,30,30000,},
			round = {40,28,16,8,4},
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 79,
			diamond_id = 1,
			game_type_name = "血战到底",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner7",
			match_time = "约8分钟",
			award = "20红包券",
			enter_num = "满40人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[3]=
		{
			id = 3,
			game_tag = "hbs_mj",
			type_id = 7,
			game_type = "game_MjXzMatch3D",
			enter_condi_itemkey = {"prop_100y","prop_1","jing_bi",},
			enter_condi_item_count = {1,150,150000,},
			round = {40,28,16,8,4},
			pay_id = 3,
			ios_pay_id = 102,
			gift_id = 83,
			diamond_id = 2,
			game_type_name = "血战到底",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner11",
			match_time = "约8分钟",
			award = "100红包券",
			enter_num = "满40人开赛",
			enter_image = "com_award_icon_jingbi",
		},
		[4]=
		{
			id = 4,
			game_tag = "hbs_mj",
			type_id = 10,
			game_type = "game_MjXzMatch3D",
			enter_condi_itemkey = {"prop_50y","prop_1","jing_bi",},
			enter_condi_item_count = {1,50,50000},
			round = {40,28,16,8,4},
			pay_id = 2,
			ios_pay_id = 101,
			gift_id = 81,
			diamond_id = 1,
			game_type_name = "血战到底",
			game_icon = "com_award_icon_money",
			is_local_icon = 1,
			cup_image = "match_icon_banner11",
			match_time = "约8分钟",
			award = "50红包券",
			enter_num = "满40人开赛",
			enter_image = "com_award_icon_jingbi",
		},
	},
	gms=
	{
		[1]=
		{
			id = 1,
			game_tag = "gms",
			type_id = 1,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"obj_qianyuansai_ticket","prop_2","jing_bi"},
			enter_condi_item_count = {1,1,100000,},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"obj_qianyuansai_ticket","prop_2","obj_qys_match_revive_ticket"},
			revive_item_count = {1,1,1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活，复活后你将拥有1000积分，一场比赛最多复活3次",
		},
		[2]=
		{
			id = 2,
			game_tag = "gms",
			type_id = 2,
			game_type = "game_DdzMatchNaming",
			iswy = 1,
			enter_condi_itemkey = {"prop_3","jing_bi"},
			enter_condi_item_count = {1,1000000,},
			round = {240,162,108,72,48,33,18,9,3},
			rank_num = 240,
			can_revive = 1,
			revive_item = {"prop_3","jing_bi"},
			revive_item_count = {1,1000000,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny4",
			is_local_icon = 1,
			match_time = "约60分钟",
			enter_num = "240人以上",
			revive_msg = "是否使用一张门票复活，复活后你将拥有1000积分，一场比赛最多复活3次",
		},
	},
	sws=
	{
		[1]=
		{
			id = 1,
			game_tag = "sws",
			type_id = 1,
			game_type = "game_DdzMatch",
			enter_condi_itemkey = {"jing_bi",},
			enter_condi_item_count = {25000,},
			round = {48,21,9,3},
			rank_num = 30,
			can_revive = 0,
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "matchpop_icon_10",
			is_local_icon = 1,
			cup_image = "match_icon_banner5",
			match_time = "约8分钟",
			award = "二选一",
			enter_num = "满48人开赛",
			enter_image = "com_award_icon_jingbi",
		},
	},
	qys=
	{
		[1]=
		{
			id = 1,
			game_tag = "qys",
			type_id = 1,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_4",},
			enter_condi_item_count = {1,},
			round = {21,15,9,3},
			rank_num = 30,
			can_revive = 0,
			revive_item = {"prop_4",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny2",
			is_local_icon = 1,
			match_time = "约20分钟",
			enter_num = "30人以上",
			revive_msg = "是否使用一张门票复活，复活后你将拥有1000积分，一场比赛最多复活3次",
		},
		[2]=
		{
			id = 2,
			game_tag = "qys",
			type_id = 2,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"jing_bi",},
			enter_condi_item_count = {1,},
			round = {24,18,15,12,9,6,3},
			rank_num = 60,
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny2",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "24人以上",
		},
	},
	mxb=
	{
		[1]=
		{
			id = 1,
			game_tag = "mxb",
			type_id = 1,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_6",},
			enter_condi_item_count = {1,},
			round = {96,60,39,21,9,3},
			rank_num = 200,
			can_revive = 0,
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "24人以上",
		},
	},
	ges=
	{
		[1]=
		{
			id = 1,
			game_tag = "ges",
			type_id = 1,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_7","jing_bi",},
			enter_condi_item_count = {1,100000},
			round = {240,162,108,72,48,33,18,9,3},
			rank_num = 200,
			can_revive = 1,
			revive_item = {"prop_7",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "settlement_icon_jp4",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[2]=
		{
			id = 2,
			game_tag = "ges",
			type_id = 2,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 200,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "settlement_icon_jp4",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[3]=
		{
			id = 3,
			game_tag = "ges",
			type_id = 3,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[4]=
		{
			id = 4,
			game_tag = "ges",
			type_id = 4,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[5]=
		{
			id = 5,
			game_tag = "ges",
			type_id = 5,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[6]=
		{
			id = 6,
			game_tag = "ges",
			type_id = 6,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[7]=
		{
			id = 7,
			game_tag = "ges",
			type_id = 7,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "com_award_icon_moeny3",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[8]=
		{
			id = 8,
			game_tag = "ges",
			type_id = 8,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "activity_icon_gift162_kt",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
		[9]=
		{
			id = 9,
			game_tag = "ges",
			type_id = 9,
			game_type = "game_DdzMatchNaming",
			enter_condi_itemkey = {"prop_gns_ticket","jing_bi",},
			enter_condi_item_count = {1,50000},
			round = {258,96,60,39,21,9,3},
			rank_num = 258,
			can_revive = 1,
			revive_item = {"prop_gns_ticket",},
			revive_item_count = {1,},
			pay_id = 0,
			diamond_id = 1,
			game_type_name = "经典斗地主",
			game_icon = "activity_icon_gift192_bx",
			is_local_icon = 1,
			match_time = "约40分钟",
			enter_num = "96人以上",
			revive_msg = "是否使用一张门票复活 ，复活后你将拥有 1000积分，一场比赛最多复活 3次",
		},
	},
}