return {
	tgjj=
	{
		[1]=
		{
			line = 1,
			id = 1,
			desc = "<color=#A7310E><size=48>每邀请一名好友完成新人福卡总计奖<color=#E60E14><size=68>5</size></color>元</size></color>",
			hint_desc = "每邀请一名好友完成新人福卡总计奖5元",
			goto_ui = {"share_hall",},
			noCloseUI = 1,
			icon = "sczd_icon_sc",
			order = 1,
		},
		[2]=
		{
			line = 2,
			id = 2,
			desc = "<color=#A7310E><size=48>每邀请一位好友购买金猪礼包奖<color=#E60E14><size=68>50</size></color>元</size></color>",
			hint_desc = "您还没有购买金猪礼包激活资格！\n购买后推广1个礼包奖励50元，是否现在立即购买？",
			noCloseUI = 1,
			icon = "sczd_icon_jz",
			order = 2,
		},
		[3]=
		{
			line = 3,
			id = 3,
			noCloseUI = 1,
			icon = "sczd_icon_jzrw",
			order = 3,
		},
	},
	wyhb=
	{
		[1]=
		{
			line = 1,
			id = 1,
			desc = "每天拿福卡",
			tip = "轻松完成生财任务奖福卡",
			goto_ui = {"hall_bbsc",},
			noCloseUI = 1,
			icon = "sczd_icon_sc",
			order = 1,
		},
		[2]=
		{
			line = 2,
			id = 2,
			desc = "玩匹配场得福卡",
			tip = "匹配场活动全天送福卡",
			goto_ui = {"free_hall",},
			noCloseUI = 1,
			icon = "sczd_icon_pp",
			order = 2,
		},
		[3]=
		{
			line = 3,
			id = 3,
			desc = "打比赛赢福卡",
			tip = "千元大奖赛\n万元大奖赛\n全天福卡赛",
			goto_ui = {"match_hall",},
			noCloseUI = 1,
			icon = "sczd_icon_bs",
			order = 3,
		},
	},
	income_spending_tge=
	{
		[1]=
		{
			id = 1,
			type = "income",
			tge_img = "sczd_imgf_srjl",
			mask_tge_img = "sczd_imgf_srjl1",
			order_id = 1,
			is_show = 1,
		},
		[2]=
		{
			id = 2,
			type = "spending",
			tge_img = "sczd_imgf_txjl",
			mask_tge_img = "sczd_imgf_txjl1",
			order_id = 2,
			is_show = 1,
		},
	},
	tglb=
	{
		[1]=
		{
			line = 1,
			good_id = 12,
			task_id = 7,
			price = 19900,
			name = "金猪礼包",
			desc = "5元×40次福卡任务 10张千元赛门票 1张万元赛门票 18万鲸币 30天记牌器",
			icon = "hall_btn_gift4",
			order = 2,
			on_off = 1,
			not_buy_show = 1,
			title = "在三星场以上对局8次",
			award = "奖励：<color=#ED8813FF><size=26>6.66</size></color>福卡",
			gotoUI = {"free_hall",},
			get_end_tips = "您当日奖励已领取，请明日6点再来",
			over_tips = "您已领满了40次奖励，邀请好友还可以领奖金哦！",
		},
		[2]=
		{
			line = 2,
			good_id = 30,
			task_id = 51,
			price = 19900,
			name = "新金猪礼包1",
			desc = "5元×40次福卡任务 10张千元赛门票 1张万元赛门票 18万鲸币 30天记牌器",
			icon = "hall_btn_jzlb1",
			order = 2,
			on_off = 1,
			not_buy_show = 1,
			title = "在三星场以上对局8次",
			award = "奖励：<color=#ED8813FF><size=26>5</size></color>福卡",
			gotoUI = {"free_hall",},
			get_end_tips = "您当日奖励已领取，请明日6点再来",
			over_tips = "您已领满了40次奖励，邀请好友还可以领奖金哦！",
		},
		[3]=
		{
			line = 3,
			good_id = 31,
			task_id = 51,
			price = 19900,
			name = "新金猪礼包1续购",
			desc = "5元×40次福卡任务 10张千元赛门票 1张万元赛门票 18万鲸币 30天记牌器",
			icon = "hall_btn_jzlb1",
			order = 2,
			on_off = 1,
			not_buy_show = 1,
			title = "在三星场以上对局8次",
			award = "奖励：<color=#ED8813FF><size=26>5</size></color>福卡",
			gotoUI = {"free_hall",},
			get_end_tips = "您当日奖励已领取，请明日6点再来",
			over_tips = "您已领满了40次奖励，邀请好友还可以领奖金哦！",
		},
		[4]=
		{
			line = 4,
			good_id = 32,
			task_id = 52,
			price = 49900,
			name = "新金猪礼包2",
			desc = "600万鲸币 10张千元赛门票 3张万元赛门票",
			icon = "hall_btn_jzlb2",
			order = 3,
			on_off = 1,
			not_buy_show = 1,
			title = "每日领取奖励",
			award = "奖励：<color=#ED8813FF><size=26>20万</size></color>鲸币",
			gotoUI = {"free_hall",},
			get_end_tips = "您当日奖励已领取，请明日6点再来",
			over_tips = "您已领满了30次奖励，邀请好友还可以领奖金哦！",
		},
		[5]=
		{
			line = 5,
			good_id = 33,
			task_id = 52,
			price = 49900,
			name = "新金猪礼包2续购",
			desc = "600万鲸币 10张千元赛门票 3张万元赛门票",
			icon = "hall_btn_jzlb2",
			order = 3,
			on_off = 1,
			not_buy_show = 1,
			title = "每日领取奖励",
			award = "奖励：<color=#ED8813FF><size=26>20万</size></color>鲸币",
			gotoUI = {"free_hall",},
			get_end_tips = "您当日奖励已领取，请明日6点再来",
			over_tips = "您已领满了30次奖励，邀请好友还可以领奖金哦！",
		},
		[6]=
		{
			line = 6,
			good_id = 43,
			task_id = 55,
			price = 9900,
			name = "vip礼包",
			desc = "10张千元赛门票（参与10场无论输赢返利100福卡）",
			icon = "hall_btn_gift14",
			order = 1,
			on_off = 1,
			not_buy_show = 1,
			title = "成功参与一次千元大奖赛",
			award = " 奖励：<color=#ED8813FF><size=26>10</size></color>福卡",
			remain = "剩余领取次数:%s/%s",
			gotoUI = {"match_hall","gms"},
			get_end_tips = "你今日的千元赛任务的奖励已经领取",
			over_tips = "你的千元赛任务的奖励都领取完了",
		},
		[7]=
		{
			line = 7,
			good_id = 43,
			task_id = 56,
			price = 9900,
			name = "vip礼包",
			desc = "10张千元赛门票（参与10场无论输赢返利100福卡）",
			icon = "hall_btn_gift14",
			order = 1,
			on_off = 1,
			not_buy_show = 0,
			title = "捕鱼当日累计赢金%s鲸币<size=26>(今日已累计赢金%s)</size>",
			award = "奖励：<color=#ED8813FF><size=26>5</size></color>福卡",
			remain = "剩余领取次数:%s/%s",
			gotoUI = {"game_FishingHall",},
			get_end_tips = "你今日的捕鱼任务的奖励已经领取",
			over_tips = "你的捕鱼任务的奖励都领取完了",
		},
	},
}