return {
	Sheet1=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			name = "name1",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_001",
			icon = "com_award_icon_dhk",
			desc = "大家好，很高兴见到各位",
			show_playerinfo = 0,
			order = 1,
			mood = 4,
			reply = {5,17},
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			name = "name2",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_002",
			icon = "com_award_icon_dhk",
			desc = "快点吧，我等的花儿都谢了",
			show_playerinfo = 0,
			order = 2,
			mood = 2,
			reply = {25,8,14},
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			name = "name3",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_003",
			icon = "com_award_icon_dhk",
			desc = "不怕神一样的对手，就怕猪一样的队友",
			show_playerinfo = 0,
			order = 3,
			mood = 1,
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			name = "name4",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_025",
			icon = "com_award_icon_dhk",
			desc = "和你合作，真是太愉快了",
			show_playerinfo = 0,
			order = 4,
			mood = 0,
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			name = "name5",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_004",
			icon = "com_award_icon_dhk",
			desc = "土豪，我们做朋友吧",
			show_playerinfo = 0,
			order = 5,
			mood = 0,
			reply = {34,17},
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			name = "name6",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_008",
			icon = "com_award_icon_dhk",
			desc = "来呀，互相伤害啊",
			show_playerinfo = 0,
			order = 6,
			mood = 1,
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			name = "name7",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_005",
			icon = "com_award_icon_dhk",
			desc = "辛辛苦苦几十年，一把回到解放前",
			show_playerinfo = 0,
			order = 7,
			mood = 1,
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			name = "name8",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_006",
			icon = "com_award_icon_dhk",
			desc = "催什么，我在想打哪张",
			show_playerinfo = 0,
			order = 8,
			mood = 3,
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			name = "name9",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_007",
			icon = "com_award_icon_dhk",
			desc = "哼，欠我的统统都要还回来",
			show_playerinfo = 0,
			order = 9,
			mood = 1,
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			name = "name10",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_009",
			icon = "com_award_icon_dhk",
			desc = "天灵灵，地灵灵，来手好牌行不行",
			show_playerinfo = 0,
			order = 10,
			mood = 4,
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			name = "name11",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_010",
			icon = "com_award_icon_dhk",
			desc = "哎呀，人霉不要怪社会",
			show_playerinfo = 0,
			order = 11,
			mood = 1,
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			name = "name12",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_011",
			icon = "com_award_icon_dhk",
			desc = "不好意思啦各位，我要走了",
			show_playerinfo = 0,
			order = 12,
			mood = 4,
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			name = "name13",
			type = 0,
			sex = 1,
			lv = 0,
			voice = "chat_012",
			icon = "com_award_icon_dhk",
			desc = "不要吵了，不要吵了，专心玩游戏吧",
			show_playerinfo = 0,
			order = 13,
			mood = 4,
		},
		[14]=
		{
			id = 14,
			item_id = 18,
			name = "name18",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_013",
			icon = "com_award_icon_dhk",
			desc = "大家好，很高兴见到各位",
			show_playerinfo = 0,
			order = 1,
			reply = {5,17},
		},
		[15]=
		{
			id = 15,
			item_id = 19,
			name = "name19",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_014",
			icon = "com_award_icon_dhk",
			desc = "快点吧，我等的花儿都谢了",
			show_playerinfo = 0,
			order = 2,
			reply = {25,8,14},
		},
		[16]=
		{
			id = 16,
			item_id = 20,
			name = "name20",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_015",
			icon = "com_award_icon_dhk",
			desc = "不怕神一样的对手，就怕猪一样的队友",
			show_playerinfo = 0,
			order = 3,
		},
		[17]=
		{
			id = 17,
			item_id = 21,
			name = "name21",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_026",
			icon = "com_award_icon_dhk",
			desc = "和你合作，真是太愉快了",
			show_playerinfo = 0,
			order = 4,
		},
		[18]=
		{
			id = 18,
			item_id = 22,
			name = "name22",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_016",
			icon = "com_award_icon_dhk",
			desc = "土豪，我们做朋友吧",
			show_playerinfo = 0,
			order = 5,
			reply = {34,17},
		},
		[19]=
		{
			id = 19,
			item_id = 23,
			name = "name23",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_020",
			icon = "com_award_icon_dhk",
			desc = "来呀，互相伤害啊",
			show_playerinfo = 0,
			order = 6,
		},
		[20]=
		{
			id = 20,
			item_id = 24,
			name = "name24",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_017",
			icon = "com_award_icon_dhk",
			desc = "辛辛苦苦几十年，一把回到解放前",
			show_playerinfo = 0,
			order = 7,
		},
		[21]=
		{
			id = 21,
			item_id = 25,
			name = "name25",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_018",
			icon = "com_award_icon_dhk",
			desc = "催什么，我在想打哪张",
			show_playerinfo = 0,
			order = 8,
		},
		[22]=
		{
			id = 22,
			item_id = 26,
			name = "name26",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_019",
			icon = "com_award_icon_dhk",
			desc = "哼，欠我的统统都要还回来",
			show_playerinfo = 0,
			order = 9,
		},
		[23]=
		{
			id = 23,
			item_id = 27,
			name = "name27",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_021",
			icon = "com_award_icon_dhk",
			desc = "天灵灵，地灵灵，来手好牌行不行",
			show_playerinfo = 0,
			order = 10,
		},
		[24]=
		{
			id = 24,
			item_id = 28,
			name = "name28",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_022",
			icon = "com_award_icon_dhk",
			desc = "哎呀，人霉不要怪社会",
			show_playerinfo = 0,
			order = 11,
		},
		[25]=
		{
			id = 25,
			item_id = 29,
			name = "name29",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_023",
			icon = "com_award_icon_dhk",
			desc = "不好意思啦各位，我要走了",
			show_playerinfo = 0,
			order = 12,
		},
		[26]=
		{
			id = 26,
			item_id = 30,
			name = "name30",
			type = 0,
			sex = 0,
			lv = 0,
			voice = "chat_024",
			icon = "com_award_icon_dhk",
			desc = "不要吵了，不要吵了，专心玩游戏吧",
			show_playerinfo = 0,
			order = 13,
		},
		[27]=
		{
			id = 27,
			item_id = 35,
			name = "开心",
			type = 1,
			lv = 0,
			effect = "BQweixiao",
			icon = "ddz_game_ui_happy",
			desc = "开心",
			show_playerinfo = 1,
			order = 1,
			mood = 0,
		},
		[28]=
		{
			id = 28,
			item_id = 36,
			name = "生气",
			type = 1,
			lv = 0,
			effect = "BQshengqi",
			icon = "ddz_game_ui_angry",
			desc = "生气",
			show_playerinfo = 1,
			order = 2,
			mood = 1,
		},
		[29]=
		{
			id = 29,
			item_id = 37,
			name = "哭泣",
			type = 1,
			lv = 0,
			effect = "BQshangxin",
			icon = "ddz_game_ui_cry",
			desc = "哭泣",
			show_playerinfo = 1,
			order = 3,
			mood = 1,
		},
		[30]=
		{
			id = 30,
			item_id = 38,
			name = "送花",
			type = 2,
			lv = 0,
			voice = "brow_001",
			effect = "HDsonghua",
			icon = "ddz_game_ui_xh",
			desc = "送花",
			show_playerinfo = 1,
			order = 4,
			mood = 5,
			reply = {35,},
		},
		[31]=
		{
			id = 31,
			item_id = 39,
			name = "丢炸弹",
			type = 2,
			lv = 0,
			voice = "brow_002",
			effect = "HDdiuzhadan",
			icon = "ddz_game_ui_zd",
			desc = "丢炸弹",
			show_playerinfo = 1,
			order = 5,
			mood = 6,
			reply = {40,55},
		},
		[32]=
		{
			id = 32,
			item_id = 40,
			name = "扔砖头",
			type = 2,
			lv = 0,
			voice = "brow_003",
			effect = "HDzhuan",
			icon = "ddz_game_ui_zt",
			desc = "扔砖头",
			show_playerinfo = 1,
			order = 6,
			mood = 6,
			reply = {39,55},
		},
		[33]=
		{
			id = 33,
			item_id = 54,
			name = "666表情",
			type = 2,
			lv = 0,
			voice = "brow_004",
			effect = "HD666",
			icon = "ddz_game_ui_666",
			desc = "老铁，666",
			ct_id = 20,
			show_playerinfo = 1,
			order = 7,
			mood = 5,
		},
		[34]=
		{
			id = 34,
			item_id = 41,
			name = "默认头像框",
			type = 3,
			lv = 0,
			icon = "hall_bg_head",
			desc = "默认头像框",
			show_playerinfo = 1,
			order = 1,
		},
		[35]=
		{
			id = 35,
			item_id = 56,
			name = "泼水",
			type = 2,
			lv = 0,
			voice = "brow_005",
			effect = "HDposhui",
			icon = "ddz_game_ui_water",
			desc = "泼水",
			ct_id = 20,
			show_playerinfo = 1,
			order = 7,
			mood = 5,
		},
		[36]=
		{
			id = 36,
			item_id = 57,
			name = "猪头",
			type = 2,
			lv = 0,
			voice = "brow_007",
			effect = "HDzhutou",
			icon = "ddz_game_ui_pig",
			desc = "变猪头",
			ct_id = 20,
			show_playerinfo = 1,
			order = 7,
			mood = 5,
		},
		[37]=
		{
			id = 37,
			item_id = 58,
			name = "VIP头像框",
			type = 3,
			lv = 0,
			icon = "com_head_vip",
			desc = "VIP头像框",
			show_playerinfo = 1,
			order = 1,
		},
	},
}