return {
	tge=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			type = "goods",
			name = "钻  石",
			icon_image = "pay_icon_diamond",
			is_new_tag = 0,
			order_id = 3,
			is_show = 1,
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			type = "jing_bi",
			name = "鲸  币",
			icon_image = "pay_icon_jb",
			is_new_tag = 0,
			order_id = 1,
			is_show = 1,
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			type = "item",
			name = "道  具",
			icon_image = "pay_icon_dj",
			is_new_tag = 1,
			order_id = 2,
			is_show = 1,
		},
	},
	goods=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			platform = "android",
			shop_type = "shop",
			price = 600,
			buy_asset_type = {"diamond",},
			buy_asset_count = {600,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 1,
			gzh_show = 0,
			is_show = 1,
			ui_order = 1,
			pay_title = "600钻石",
			ui_title = "600钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥6",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			platform = "android",
			shop_type = "shop",
			price = 1500,
			buy_asset_type = {"diamond",},
			buy_asset_count = {1500,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 2,
			gzh_show = 0,
			is_show = 1,
			ui_order = 2,
			pay_title = "1500钻石",
			ui_title = "1500钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥15",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			platform = "android",
			shop_type = "shop",
			price = 3000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {3000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 3,
			gzh_show = 0,
			is_show = 1,
			ui_order = 3,
			pay_title = "3000钻石",
			ui_title = "3000钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥30",
			ui_icon = "pay_icon_diamond3",
			ui_icon_bg = "pay_bg_light2",
		},
		[4]=
		{
			line_id = 4,
			id = 4,
			platform = "android",
			shop_type = "shop",
			price = 5000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {5000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 4,
			gzh_show = 0,
			is_show = 1,
			ui_order = 4,
			pay_title = "5000钻石",
			ui_title = "5000钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥50",
			ui_icon = "pay_icon_diamond4",
			ui_icon_bg = "pay_bg_light2",
		},
		[5]=
		{
			line_id = 5,
			id = 5,
			platform = "android",
			shop_type = "shop",
			price = 10000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {10000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 5,
			gzh_show = 0,
			is_show = 1,
			ui_order = 5,
			pay_title = "1万钻石",
			ui_title = "1万钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥100",
			ui_icon = "pay_icon_diamond5",
			ui_icon_bg = "pay_bg_light2",
		},
		[6]=
		{
			line_id = 6,
			id = 6,
			platform = "android",
			shop_type = "shop",
			price = 50000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {50000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 6,
			gzh_show = 0,
			is_show = 1,
			ui_order = 6,
			pay_title = "5万钻石",
			ui_title = "5万钻石",
			ui_describe = "1元=100钻石",
			ui_price = "￥500",
			ui_icon = "pay_icon_diamond8",
			ui_icon_bg = "pay_bg_light2",
		},
		[7]=
		{
			line_id = 7,
			id = 101,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond6",
			shop_type = "shop",
			price = 600,
			buy_asset_type = {"diamond",},
			buy_asset_count = {400,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			type = "goods",
			group_id = 1,
			gzh_order = 1,
			gzh_show = 0,
			is_show = 1,
			ui_order = 1,
			pay_title = "400钻石",
			ui_title = 400,
			ui_describe = "1元=66钻石",
			ui_price = "6元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[8]=
		{
			line_id = 8,
			id = 102,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond30",
			shop_type = "shop",
			price = 3000,
			buy_asset_type = {"diamond",},
			buy_asset_count = {2000,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			type = "goods",
			group_id = 1,
			gzh_order = 2,
			gzh_show = 0,
			is_show = 1,
			ui_order = 2,
			pay_title = "2000钻石",
			ui_title = 2000,
			ui_describe = "1元=66钻石",
			ui_price = "30元",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
		[9]=
		{
			line_id = 9,
			id = 103,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond98",
			shop_type = "shop",
			price = 9800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {6700,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			type = "goods",
			group_id = 1,
			gzh_order = 3,
			gzh_show = 0,
			is_show = 1,
			ui_order = 3,
			pay_title = "6700钻石",
			ui_title = 6700,
			ui_describe = "1元=66钻石",
			ui_price = "98元",
			ui_icon = "pay_icon_diamond3",
			ui_icon_bg = "pay_bg_light2",
		},
		[10]=
		{
			line_id = 10,
			id = 104,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond198",
			shop_type = "shop",
			price = 19800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {13200,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			type = "goods",
			group_id = 1,
			gzh_order = 4,
			gzh_show = 0,
			is_show = 1,
			ui_order = 4,
			pay_title = "1.32万钻石",
			ui_title = "1.32万",
			ui_describe = "1元=66钻石",
			ui_price = "198元",
			ui_icon = "pay_icon_diamond4",
			ui_icon_bg = "pay_bg_light2",
		},
		[11]=
		{
			line_id = 11,
			id = 105,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond298",
			shop_type = "shop",
			price = 29800,
			buy_asset_type = {"diamond",},
			buy_asset_count = {20400,},
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			type = "goods",
			group_id = 1,
			gzh_order = 5,
			gzh_show = 0,
			is_show = 1,
			ui_order = 5,
			pay_title = "2.04万钻石",
			ui_title = "2.04万",
			ui_describe = "1元=66钻石",
			ui_price = "298元",
			ui_icon = "pay_icon_diamond5",
			ui_icon_bg = "pay_bg_light2",
		},
		[12]=
		{
			line_id = 12,
			id = 106,
			platform = "ios",
			product_id = "com.jyjjddz.zs.diamond1",
			shop_type = "shop",
			price = 100,
			buy_asset_type = {"diamond",},
			buy_asset_count = {100,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "goods",
			group_id = 1,
			gzh_order = 11,
			gzh_show = 0,
			is_show = 0,
			ui_order = 0,
			pay_title = "100钻石",
			ui_title = 100,
			ui_describe = "1元=66钻石",
			ui_price = "1元",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[13]=
		{
			line_id = 13,
			id = 22,
			shop_type = "shop",
			price = 600,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {60000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 1,
			gzh_show = 1,
			is_show = 0,
			ui_order = 1,
			pay_title = "6万鲸币",
			ui_title = "6万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥6",
			ui_icon = "pay_icon_diamond1",
			ui_icon_bg = "pay_bg_light2",
		},
		[14]=
		{
			line_id = 14,
			id = 23,
			shop_type = "shop",
			price = 1500,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {150000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 2,
			gzh_show = 1,
			is_show = 0,
			ui_order = 2,
			pay_title = "15万鲸币",
			ui_title = "15万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥15",
			ui_icon = "pay_icon_diamond2",
			ui_icon_bg = "pay_bg_light2",
		},
		[15]=
		{
			line_id = 15,
			id = 24,
			shop_type = "shop",
			price = 3000,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {300000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 3,
			gzh_show = 1,
			is_show = 0,
			ui_order = 3,
			pay_title = "30万鲸币",
			ui_title = "30万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥30",
			ui_icon = "pay_icon_diamond3",
			ui_icon_bg = "pay_bg_light2",
		},
		[16]=
		{
			line_id = 16,
			id = 25,
			shop_type = "shop",
			price = 5000,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {500000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 4,
			gzh_show = 1,
			is_show = 0,
			ui_order = 4,
			pay_title = "50万鲸币",
			ui_title = "50万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥50",
			ui_icon = "pay_icon_diamond4",
			ui_icon_bg = "pay_bg_light2",
		},
		[17]=
		{
			line_id = 17,
			id = 26,
			shop_type = "shop",
			price = 10000,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {1000000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 5,
			gzh_show = 1,
			is_show = 0,
			ui_order = 5,
			pay_title = "100万鲸币",
			ui_title = "100万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥100",
			ui_icon = "pay_icon_diamond5",
			ui_icon_bg = "pay_bg_light2",
		},
		[18]=
		{
			line_id = 18,
			id = 27,
			shop_type = "shop",
			price = 50000,
			buy_asset_type = {"jing_bi",},
			buy_asset_count = {5000000,},
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			group_id = 1,
			gzh_order = 6,
			gzh_show = 1,
			is_show = 0,
			ui_order = 6,
			pay_title = "500万鲸币",
			ui_title = "500万鲸币",
			ui_describe = "1元=100钻石",
			ui_price = "￥500",
			ui_icon = "pay_icon_diamond8",
			ui_icon_bg = "pay_bg_light2",
		},
	},
	gift_bag=
	{
		[1]=
		{
			line_id = 1,
			id = 7,
			on_off = 0,
			pay_title = "二元礼包",
			gzh_order = 7,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,3},
			buy_limt = 0,
			count = 0,
			start_time = 0,
			end_time = 1,
		},
		[2]=
		{
			line_id = 2,
			id = 8,
			on_off = 0,
			pay_title = "合伙人礼包",
			gzh_order = 8,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,4},
			buy_limt = 0,
			count = 0,
			start_time = 0,
			end_time = 1,
		},
		[3]=
		{
			line_id = 3,
			id = 9,
			on_off = 0,
			pay_title = "圣诞礼包",
			gzh_order = 9,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 200,
			buy_asset_type = {"jing_bi","shop_gold_sum","jipaiqi"},
			buy_asset_count = {20000,200,5},
			buy_limt = 0,
			count = 0,
			start_time = 0,
			end_time = 1,
		},
		[4]=
		{
			line_id = 4,
			id = 10,
			product_id = "com.jyjjddz.zs.diamond1",
			on_off = 1,
			pay_title = "一元超值礼包",
			gzh_order = -4,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi","shop_gold_sum"},
			buy_asset_count = {10000,50},
			buy_limt = 1,
			count = 99999999,
			start_time = 0,
			end_time = 2552233600,
		},
		[5]=
		{
			line_id = 5,
			id = 11,
			on_off = 0,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -5,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 100,
			buy_asset_type = {"jing_bi","shop_gold_sum","prop_2"},
			buy_asset_count = {10000,100,1},
			buy_limt = 0,
			count = 0,
			start_time = 0,
			end_time = 1,
		},
		[6]=
		{
			line_id = 6,
			id = 12,
			on_off = 1,
			pay_title = "金猪大礼包",
			gzh_order = -10,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 19900,
			buy_asset_type = {"jing_bi","prop_hammer_2","jipaiqi","prop_2","prop_3","expression_54"},
			buy_asset_count = {180000,200,30,10,1,50},
			buy_limt = 0,
			count = 100,
			start_time = 0,
			end_time = 2552233600,
		},
		[7]=
		{
			line_id = 7,
			id = 13,
			on_off = 1,
			pay_title = "千元大奖赛门票礼包",
			gzh_order = -6,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 1000,
			buy_asset_type = {"jing_bi","prop_2"},
			buy_asset_count = {100000,1},
			buy_limt = 0,
			count = 9999999,
			start_time = 0,
			end_time = 2552233600,
		},
		[8]=
		{
			line_id = 8,
			id = 20,
			on_off = 1,
			pay_title = "迎新春礼包",
			gzh_order = -7,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 2800,
			buy_asset_type = {"jing_bi","jipaiqi","prop_2"},
			buy_asset_count = {320000,3,1},
			buy_limt = 0,
			count = 999999,
			start_time = 0,
			end_time = 1548950400,
		},
		[9]=
		{
			line_id = 9,
			id = 21,
			on_off = 1,
			pay_title = "春节礼包",
			gzh_order = -7,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 1900,
			buy_asset_type = {"jing_bi","jipaiqi","prop_2"},
			buy_asset_count = {270000,3,1},
			buy_limt = 0,
			count = 0,
			start_time = 0,
			end_time = 1550592000,
		},
		[10]=
		{
			line_id = 10,
			id = 28,
			on_off = 1,
			pay_title = "女神礼包",
			gzh_order = -7,
			gzh_show = 1,
			shop_type = "gift_bag",
			price = 3800,
			buy_asset_type = {"jing_bi","prop_hammer_3","prop_2",},
			buy_asset_count = {380000,10,1},
			buy_limt = 1,
			count = 999999,
			start_time = 1551888000,
			end_time = 1552233600,
		},
	},
	jing_bi=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			platform = "android",
			goods_id = 1,
			use_type = "diamond",
			use_count = 600,
			jing_bi = 60000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 1,
			ui_title = "6万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 600,
			ui_icon = "pay_icon_gold3",
			ui_icon_bg = "pay_bg_light1",
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			platform = "android",
			goods_id = 2,
			use_type = "diamond",
			use_count = 1500,
			jing_bi = 150000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 2,
			ui_title = "15万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 1500,
			ui_icon = "pay_icon_gold4",
			ui_icon_bg = "pay_bg_light1",
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			platform = "android",
			goods_id = 3,
			use_type = "diamond",
			use_count = 3000,
			jing_bi = 300000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 3,
			ui_title = "30万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 3000,
			ui_icon = "pay_icon_gold5",
			ui_icon_bg = "pay_bg_light1",
		},
		[4]=
		{
			line_id = 4,
			id = 4,
			platform = "android",
			goods_id = 4,
			use_type = "diamond",
			use_count = 5000,
			jing_bi = 500000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 4,
			ui_title = "50万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 5000,
			ui_icon = "pay_icon_gold6",
			ui_icon_bg = "pay_bg_light1",
		},
		[5]=
		{
			line_id = 5,
			id = 5,
			platform = "android",
			goods_id = 5,
			use_type = "diamond",
			use_count = 10000,
			jing_bi = 1000000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 5,
			ui_title = "100万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 10000,
			ui_icon = "pay_icon_gold7",
			ui_icon_bg = "pay_bg_light1",
		},
		[6]=
		{
			line_id = 6,
			id = 6,
			platform = "android",
			goods_id = 6,
			use_type = "diamond",
			use_count = 50000,
			jing_bi = 5000000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 6,
			ui_title = "500万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 50000,
			ui_icon = "pay_icon_gold8",
			ui_icon_bg = "pay_bg_light1",
		},
		[7]=
		{
			line_id = 7,
			id = 7,
			platform = "android",
			goods_id = 1,
			use_type = "diamond",
			use_count = 100,
			jing_bi = 10000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 0,
			ui_title = "1万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 100,
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
		},
		[8]=
		{
			line_id = 8,
			id = 101,
			platform = "ios",
			goods_id = 101,
			use_type = "diamond",
			use_count = 400,
			jing_bi = 40000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 1,
			ui_title = "4万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 400,
			ui_icon = "pay_icon_gold3",
			ui_icon_bg = "pay_bg_light1",
		},
		[9]=
		{
			line_id = 9,
			id = 102,
			platform = "ios",
			goods_id = 102,
			use_type = "diamond",
			use_count = 2000,
			jing_bi = 200000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 2,
			ui_title = "20万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 2000,
			ui_icon = "pay_icon_gold4",
			ui_icon_bg = "pay_bg_light1",
		},
		[10]=
		{
			line_id = 10,
			id = 103,
			platform = "ios",
			goods_id = 103,
			use_type = "diamond",
			use_count = 6700,
			jing_bi = 670000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 3,
			ui_title = "67万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 6700,
			ui_icon = "pay_icon_gold5",
			ui_icon_bg = "pay_bg_light1",
		},
		[11]=
		{
			line_id = 11,
			id = 104,
			platform = "ios",
			goods_id = 104,
			use_type = "diamond",
			use_count = 13200,
			jing_bi = 1320000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 4,
			ui_title = "132万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 13200,
			ui_icon = "pay_icon_gold6",
			ui_icon_bg = "pay_bg_light1",
		},
		[12]=
		{
			line_id = 12,
			id = 105,
			platform = "ios",
			goods_id = 105,
			use_type = "diamond",
			use_count = 20400,
			jing_bi = 2040000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 5,
			ui_title = "204万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 20400,
			ui_icon = "pay_icon_gold7",
			ui_icon_bg = "pay_bg_light1",
		},
		[13]=
		{
			line_id = 13,
			id = 106,
			platform = "ios",
			goods_id = 101,
			use_type = "diamond",
			use_count = 100,
			jing_bi = 10000,
			gift_asset_type = {nil,},
			gift_asset_count = {100,200,300},
			type = "jing_bi",
			is_show = 1,
			ui_order = 0,
			ui_title = "1万鲸币",
			ui_describe = "100钻=1万鲸币",
			ui_price = 100,
			ui_icon = "pay_icon_gold2",
			ui_icon_bg = "pay_bg_light1",
		},
	},
	item=
	{
		[1]=
		{
			line_id = 1,
			id = 1,
			type = "expression",
			use_type = "jing_bi",
			use_count = 60000,
			num = 1,
			group = "expression_666",
			item_id = 54,
			max = 999999,
			condition = {22,},
			is_show = 1,
			ui_order = 1,
			ui_title = "666表情",
			ui_givedesc = "有几率中红包",
			ui_describe = "表情在任意游戏通用",
			ui_price = 60000,
			ui_icon = "pay_icon_666",
			ui_icon_bg = "pay_bg_light1",
		},
		[2]=
		{
			line_id = 2,
			id = 2,
			type = "expression",
			use_type = "jing_bi",
			use_count = 500000,
			num = 10,
			group = "expression_666",
			item_id = 54,
			max = 999999,
			condition = {23,},
			is_show = 1,
			ui_order = 2,
			ui_title = "666表情",
			ui_givedesc = "必中红包",
			ui_describe = "表情在任意游戏通用",
			ui_price = 500000,
			ui_icon = "pay_icon_666",
			ui_icon_bg = "pay_bg_light1",
			ui_discount = 8.300000,
		},
		[3]=
		{
			line_id = 3,
			id = 3,
			type = "jipaiqi",
			use_type = "jing_bi",
			use_count = 15000,
			jipaiqi_time = 1,
			gift_asset_type = {nil,},
			gift_asset_count = 100200300,
			is_show = 1,
			ui_order = 3,
			ui_title = "记牌器1天",
			ui_describe = "斗地主使用，可累积",
			ui_price = 15000,
			ui_icon = "pay_icon_memorycard",
			ui_icon_bg = "pay_bg_light1",
		},
		[4]=
		{
			line_id = 4,
			id = 1,
			type = "room_card",
			use_type = "jing_bi",
			use_count = 15000,
			num = 15,
			gift_asset_type = {nil,},
			is_show = 1,
			ui_order = 4,
			ui_title = "15房卡",
			ui_describe = "1000鲸币=1房卡",
			ui_price = 15000,
			ui_icon = "pay_icon_rc1",
			ui_icon_bg = "pay_bg_light1",
		},
		[5]=
		{
			line_id = 5,
			id = 1,
			type = "prop_2",
			use_type = "jing_bi",
			use_count = 100000,
			num = 1,
			gift_asset_type = {nil,},
			item_id = 27,
			is_show = 0,
			ui_order = 0,
			ui_price = 100000,
			ui_icon = "com_award_icon_qys",
			ui_icon_bg = "pay_bg_light1",
		},
		[6]=
		{
			line_id = 6,
			id = 1,
			type = "prop_3",
			use_type = "jing_bi",
			use_count = 1000000,
			num = 1,
			gift_asset_type = {nil,},
			item_id = 34,
			is_show = 0,
			ui_order = 0,
			ui_price = 100000,
			ui_icon = "com_award_icon_qys",
			ui_icon_bg = "pay_bg_light1",
		},
	},
}