return {
	config=
	{
		[1]=
		{
			id = 1,
			game_id = 1,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {250,},
			award_icon = {"ty_icon_flq1",},
		},
		[2]=
		{
			id = 2,
			game_id = 1,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {100,},
			award_icon = {"ty_icon_flq1",},
		},
		[3]=
		{
			id = 3,
			game_id = 1,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {50,},
			award_icon = {"ty_icon_flq1",},
		},
		[4]=
		{
			id = 4,
			game_id = 1,
			rank_range = {4,10},
			award_type = {"jing_bi",},
			award_num = {25000,},
			award_icon = {"ty_icon_jb_30y",},
		},
		[5]=
		{
			id = 5,
			game_id = 2,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {2500,},
			award_icon = {"ty_icon_flq1",},
		},
		[6]=
		{
			id = 6,
			game_id = 2,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {1000,},
			award_icon = {"ty_icon_flq1",},
		},
		[7]=
		{
			id = 7,
			game_id = 2,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {500,},
			award_icon = {"ty_icon_flq1",},
		},
		[8]=
		{
			id = 8,
			game_id = 2,
			rank_range = {4,10},
			award_type = {"jing_bi",},
			award_num = {250000,},
			award_icon = {"ty_icon_jb_30y",},
		},
		[9]=
		{
			id = 9,
			game_id = 3,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {25000,},
			award_icon = {"ty_icon_flq1",},
		},
		[10]=
		{
			id = 10,
			game_id = 3,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {10000,},
			award_icon = {"ty_icon_flq1",},
		},
		[11]=
		{
			id = 11,
			game_id = 3,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {5000,},
			award_icon = {"ty_icon_flq1",},
		},
		[12]=
		{
			id = 12,
			game_id = 3,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {2500,},
			award_icon = {"ty_icon_flq1",},
		},
		[13]=
		{
			id = 13,
			game_id = 4,
			rank_range = {1,1},
			award_type = {"shop_gold_sum",},
			award_num = {250000,},
			award_icon = {"ty_icon_flq1",},
		},
		[14]=
		{
			id = 14,
			game_id = 4,
			rank_range = {2,2},
			award_type = {"shop_gold_sum",},
			award_num = {100000,},
			award_icon = {"ty_icon_flq1",},
		},
		[15]=
		{
			id = 15,
			game_id = 4,
			rank_range = {3,3},
			award_type = {"shop_gold_sum",},
			award_num = {50000,},
			award_icon = {"ty_icon_flq1",},
		},
		[16]=
		{
			id = 16,
			game_id = 4,
			rank_range = {4,10},
			award_type = {"shop_gold_sum",},
			award_num = {25000,},
			award_icon = {"ty_icon_flq1",},
		},
	},
	pms_config=
	{
		[1]=
		{
			id = 1,
			game_tag = "pms",
			game_id = 2,
			game_type = "game_Fishing3D",
			game_name = "250福利券赛",
			game_type_name = "3D捕鱼神秘海域场",
			ui_order = 1,
			enter_condi_itemkey = {"obj_3d_50flq","prop_3d_50flq","jing_bi",},
			enter_condi_item_count = {1,1,5000,},
			award_desc = {"250福利券",},
			award_icon = {"ty_icon_flq1",},
			jing_bi_min = 10000,
			jing_bi_max = 1000000,
			match_bullet_num = 1000,
			match_time = 10,
			award = "250福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 76,
			diamond_id = 1,
			award_id = 1,
		},
		[2]=
		{
			id = 2,
			game_tag = "pms",
			game_id = 3,
			game_type = "game_Fishing3D",
			game_name = "2500福利券赛",
			game_type_name = "3D捕鱼海底宝藏场",
			ui_order = 2,
			enter_condi_itemkey = {"obj_3d_200flq","prop_3d_200flq","jing_bi",},
			enter_condi_item_count = {1,1,50000,},
			award_desc = {"2500福利券",},
			award_icon = {"ty_icon_flq2",},
			jing_bi_min = 100000,
			jing_bi_max = 200000000,
			match_bullet_num = 1000,
			match_time = 10,
			award = "2500福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 77,
			diamond_id = 1,
			award_id = 2,
		},
		[3]=
		{
			id = 3,
			game_tag = "pms",
			game_id = 4,
			game_type = "game_Fishing3D",
			game_name = "25000福利券赛",
			game_type_name = "3D捕鱼藏宝海湾场",
			ui_order = 3,
			enter_condi_itemkey = {"obj_3d_500flq","prop_3d_500flq","jing_bi",},
			enter_condi_item_count = {1,1,500000,},
			award_desc = {"25000福利券",},
			award_icon = {"ty_icon_flq3",},
			jing_bi_min = 1000000,
			jing_bi_max = 800000000,
			match_bullet_num = 1000,
			match_time = 10,
			award = "25000福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 101,
			gift_id = 80,
			diamond_id = 1,
			award_id = 3,
		},
		[4]=
		{
			id = 4,
			game_tag = "pms",
			game_id = 5,
			game_type = "game_Fishing3D",
			game_name = "250000福利券赛",
			game_type_name = "3D捕鱼深海沉船场",
			ui_order = 4,
			enter_condi_itemkey = {"obj_3d_1000flq","prop_3d_1000flq","jing_bi",},
			enter_condi_item_count = {1,1,5000000,},
			award_desc = {"250000福利券",},
			award_icon = {"ty_icon_flq4",},
			jing_bi_min = 10000000,
			jing_bi_max = 99999999999,
			match_bullet_num = 1000,
			match_time = 10,
			award = "250000福利券赛",
			desc = "满20人开赛",
			pay_id = 1,
			ios_pay_id = 102,
			gift_id = 82,
			diamond_id = 2,
			award_id = 4,
		},
	},
	pms_award=
	{
		[1]=
		{
			id = 1,
			award_id = 1,
			rank_name = "黄金段位",
			icon = "3dby_icon_ph_1",
			is_local_icon = 1,
			min_score = 1750,
			max_score = -1,
			award_desc = {"50",},
			award_icon = {"ty_icon_flq1",},
		},
		[2]=
		{
			id = 2,
			award_id = 1,
			rank_name = "白银段位",
			icon = "3dby_icon_ph_2",
			is_local_icon = 1,
			min_score = 1400,
			max_score = 1749,
			award_desc = {"2万",},
			award_icon = {"ty_icon_jb_30y",},
		},
		[3]=
		{
			id = 3,
			award_id = 1,
			rank_name = "青铜段位",
			icon = "3dby_icon_ph_3",
			is_local_icon = 1,
			min_score = 1050,
			max_score = 1399,
			award_desc = {"1万",},
			award_icon = {"ty_icon_jb_15y",},
		},
		[4]=
		{
			id = 4,
			award_id = 2,
			rank_name = "黄金段位",
			icon = "3dby_icon_ph_1",
			is_local_icon = 1,
			min_score = 1750,
			max_score = -1,
			award_desc = {"500",},
			award_icon = {"ty_icon_flq1",},
		},
		[5]=
		{
			id = 5,
			award_id = 2,
			rank_name = "白银段位",
			icon = "3dby_icon_ph_2",
			is_local_icon = 1,
			min_score = 1400,
			max_score = 1749,
			award_desc = {"20万",},
			award_icon = {"ty_icon_jb_30y",},
		},
		[6]=
		{
			id = 6,
			award_id = 2,
			rank_name = "青铜段位",
			icon = "3dby_icon_ph_3",
			is_local_icon = 1,
			min_score = 1050,
			max_score = 1399,
			award_desc = {"10万",},
			award_icon = {"ty_icon_jb_15y",},
		},
		[7]=
		{
			id = 7,
			award_id = 3,
			rank_name = "黄金段位",
			icon = "3dby_icon_ph_1",
			is_local_icon = 1,
			min_score = 1750,
			max_score = -1,
			award_desc = {"5000",},
			award_icon = {"ty_icon_flq3",},
		},
		[8]=
		{
			id = 8,
			award_id = 3,
			rank_name = "白银段位",
			icon = "3dby_icon_ph_2",
			is_local_icon = 1,
			min_score = 1400,
			max_score = 1749,
			award_desc = {"2000",},
			award_icon = {"ty_icon_flq2",},
		},
		[9]=
		{
			id = 9,
			award_id = 3,
			rank_name = "青铜段位",
			icon = "3dby_icon_ph_3",
			is_local_icon = 1,
			min_score = 1050,
			max_score = 1399,
			award_desc = {"1000",},
			award_icon = {"ty_icon_flq1",},
		},
		[10]=
		{
			id = 10,
			award_id = 4,
			rank_name = "黄金段位",
			icon = "3dby_icon_ph_1",
			is_local_icon = 1,
			min_score = 1750,
			max_score = -1,
			award_desc = {"50000",},
			award_icon = {"ty_icon_flq3",},
		},
		[11]=
		{
			id = 11,
			award_id = 4,
			rank_name = "白银段位",
			icon = "3dby_icon_ph_2",
			is_local_icon = 1,
			min_score = 1400,
			max_score = 1749,
			award_desc = {"20000",},
			award_icon = {"ty_icon_flq2",},
		},
		[12]=
		{
			id = 12,
			award_id = 4,
			rank_name = "青铜段位",
			icon = "3dby_icon_ph_3",
			is_local_icon = 1,
			min_score = 1050,
			max_score = 1399,
			award_desc = {"10000",},
			award_icon = {"ty_icon_flq1",},
		},
	},
}