return {
	config=
	{
		[1]=
		{
			line = 1,
			gift_key = "gift_kllb",
			temp = "T3",
			gift_id = {10081,10082,10083},
			bg_img = "sdlb_bg",
			enter_icon = "sdlb_btn_lb",
			icon_img = {"sdlb_btn_1","sdlb_btn_2","sdlb_btn_3"},
			btn_img = {"sdlb_btn_1_2","sdlb_btn_2_2","sdlb_btn_3_2"},
			btn_img_no = {"sdlb_btn_1_1","sdlb_btn_2_1","sdlb_btn_3_1"},
			isOnOff = 1,
		},
		[2]=
		{
			line = 2,
			gift_key = "gift_bybs",
			temp = "T1",
			gift_id = {10025,},
			bg_img = "gy_57",
			enter_icon = "by_match_btn_thmp",
			isOnOff = 1,
		},
		[3]=
		{
			line = 3,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10778,10779,10780,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"6万","1万","5000","48万","2万","1万","98万","3万","2万",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","ty_icon_yxb_2","ty_icon_jb_998y","ty_icon_jb_50y","ty_icon_yxb_2","ty_icon_jb_2498y","ty_icon_jb_198y","ty_icon_yxb_2",},
			isOnOff = 1,
		},
		[4]=
		{
			line = 4,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10781,10782,10783,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"1万","1万","1","3万","2万","2","6万","3万","3",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","3dby_btn_sd","ty_icon_jb_998y","ty_icon_jb_50y","3dby_btn_sd","ty_icon_jb_2498y","ty_icon_jb_198y","3dby_btn_sd",},
			isOnOff = 1,
		},
		[5]=
		{
			line = 5,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10784,10785,10786,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"6万","2万","3","10万","2万","1万","18万","2万","2万",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","3dby_btn_sd","ty_icon_jb_998y","ty_icon_jb_50y","ty_icon_yxb_2","ty_icon_jb_2498y","ty_icon_jb_198y","ty_icon_yxb_4",},
			isOnOff = 1,
		},
		[6]=
		{
			line = 6,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10787,10788,10789,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"18万","1万","1万","48万","2万","1万","98万","3万","2万",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","ty_icon_yxb_2","ty_icon_jb_998y","ty_icon_jb_50y","ty_icon_yxb_4","ty_icon_jb_2498y","ty_icon_jb_198y","ty_icon_yxb_5",},
			isOnOff = 1,
		},
		[7]=
		{
			line = 7,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10790,10791,10792,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"48万","2万","1万","98万","3万","2万","198万","8万","3万",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","ty_icon_yxb_2","ty_icon_jb_998y","ty_icon_jb_50y","ty_icon_yxb_4","ty_icon_jb_2498y","ty_icon_jb_198y","ty_icon_yxb_5",},
			isOnOff = 1,
		},
		[8]=
		{
			line = 8,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10793,10794,10795,},
			bg_img = "mrth_bg_mrth",
			db_img = "mrth_dk_mrth",
			enter_icon = "mrth_btn_mrth",
			is_hz = 1,
			name_c = "FFF0DFFF",
			name_outline = "9A201FFF",
			font_c = "CB5D11FF",
			outline_c = "FFFFFFFF",
			gift_c = "FFEABFFF",
			pay_name = {"98万","3万","2万","198万","8万","3万","498万","15万","5万",},
			icon_img = {"ty_icon_jb_498y","ty_icon_jb_30y","ty_icon_yxb_2","ty_icon_jb_998y","ty_icon_jb_50y","ty_icon_yxb_4","ty_icon_jb_2498y","ty_icon_jb_198y","ty_icon_yxb_5",},
			isOnOff = 1,
		},
	},
	Sheet1=
	{
	},
	Sheet2=
	{
	},
}