return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			title = "积分抽大奖",
			noCloseUI = 0,
			order = 1,
			key = "act_024_jfcdj",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_jfcdj","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "Sign_in_popup_old",
		},
		[2]=
		{
			id = 2,
			ID = 2,
			title = "我要赚积分",
			noCloseUI = 0,
			order = 2,
			key = "act_024_wyzjf",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_024_wyzjf","panel"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "Sign_in_popup_old",
		},
		[3]=
		{
			id = 3,
			ID = 3,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl1_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl1_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl2",
		},
		[4]=
		{
			id = 4,
			ID = 4,
			title = "连购返利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_024_lgfl2_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_024_lgfl2_config"},
			tag = "hot",
			beginTime = 1597102200,
			endTime = 1597679999,
			condi_key = "actp_own_task_p_summer_lgfl1",
		},
		[5]=
		{
			id = 5,
			ID = 5,
			title = "小龙虾榜",
			noCloseUI = 0,
			order = 1,
			key = "act_025_xlxphb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_025_xlxphb","panel"},
			tag = "hot",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "actp_rank_xiaolongxiaquan_025_rank",
		},
		[6]=
		{
			id = 6,
			ID = 6,
			title = "龙虾兑换",
			noCloseUI = 0,
			order = 2,
			key = "act_025_lxdh",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_025_lxdh","panel"},
			tag = "normal",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "lxdh_025_notnew",
		},
		[7]=
		{
			id = 7,
			ID = 7,
			title = "捕虾福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_025_bxfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_025_bxfl_config"},
			tag = "hot",
			beginTime = 1597707000,
			endTime = 1598284799,
			condi_key = "actp_own_task_p_0818_bxfl",
		},
		[8]=
		{
			id = 8,
			ID = 8,
			title = "表白礼包",
			noCloseUI = 0,
			order = 1,
			key = "act_026_bblb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_bblb","panel"},
			tag = "hot",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_own_task_p_026_dove_gift",
		},
		[9]=
		{
			id = 9,
			ID = 9,
			title = "真爱榜单",
			noCloseUI = 0,
			order = 2,
			key = "act_026_zabd",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_zabd","panel"},
			tag = "normal",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_rank_true_love_026_rank",
		},
		[10]=
		{
			id = 10,
			ID = 10,
			title = "浪漫礼盒",
			noCloseUI = 0,
			order = 3,
			key = "act_026_lmlh",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_026_lmlh","panel"},
			tag = "normal",
			beginTime = 1598311800,
			endTime = 1598889599,
			condi_key = "actp_own_task_p_026_lmqx_lmlh",
		},
		[11]=
		{
			id = 11,
			ID = 11,
			title = "小游戏福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_030_xyxfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_030_xyxfl_config"},
			tag = "hot",
			beginTime = 1610380800,
			endTime = 1611590399,
			condi_key = "actp_own_task_p_030_xyxfl",
		},
		[12]=
		{
			id = 12,
			ID = 12,
			title = "五星换好礼",
			noCloseUI = 0,
			order = 1,
			key = "act_031_wxhhl",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_031_wxhhl","panel"},
			tag = "normal",
			beginTime = 1601335800,
			endTime = 1601913599,
			condi_key = "actp_buy_gift_bag_class_031_gqfd_gift",
		},
		[13]=
		{
			id = 13,
			ID = 13,
			title = "国庆福袋",
			noCloseUI = 0,
			order = 2,
			key = "act_031_gqfd",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_031_gqfd","panel"},
			tag = "normal",
			beginTime = 1601335800,
			endTime = 1601913599,
			condi_key = "actp_buy_gift_bag_class_031_gqfd_gift",
		},
		[14]=
		{
			id = 14,
			ID = 14,
			title = "国庆福利",
			noCloseUI = 1,
			order = 3,
			type = "activity",
			isOnOff = 0,
			showType = "image",
			parmData = "gqflmfs_bg_1",
			is_local_icon = 1,
			gotoUI = {"act_031_gqfl","share_link"},
			tag = "normal",
			beginTime = 1601335800,
			endTime = 1601913599,
			condi_key = "actp_buy_gift_bag_class_031_gqfd_gift",
		},
		[15]=
		{
			id = 15,
			ID = 15,
			title = "立冬福袋",
			noCloseUI = 0,
			order = 2,
			key = "act_034_ldfd",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_034_ldfd","panel"},
			tag = "normal",
			beginTime = 1604359800,
			endTime = 1604937599,
			condi_key = "cpl_notcjj",
		},
		[16]=
		{
			id = 16,
			ID = 16,
			title = "小游戏福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_034_xyxfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_034_xyxfl_config"},
			tag = "normal",
			beginTime = 1604359800,
			endTime = 1604937599,
			condi_key = "actp_own_task_p_034_xyxfl",
		},
		[17]=
		{
			id = 17,
			ID = 17,
			title = "感恩礼包",
			noCloseUI = 0,
			order = 2,
			key = "act_036_gelb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_036_gelb","panel"},
			tag = "normal",
			beginTime = 1606176000,
			endTime = 1606751999,
		},
		[18]=
		{
			id = 18,
			ID = 18,
			title = "火鸡换好礼",
			noCloseUI = 0,
			order = 1,
			key = "act_036_hjhhl",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_036_hjhhl","panel"},
			tag = "normal",
			beginTime = 1606176000,
			endTime = 1606751999,
		},
		[19]=
		{
			id = 19,
			ID = 19,
			title = "兑换好礼",
			noCloseUI = 0,
			order = 1,
			key = "act_038_s12dhhl",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_038_s12dhhl","panel"},
			tag = "normal",
			beginTime = 1607385600,
			endTime = 1607961599,
		},
		[20]=
		{
			id = 20,
			ID = 20,
			title = "礼盒收集榜",
			noCloseUI = 0,
			order = 2,
			key = "act_038_s12lhsjb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_038_s12lhsjb","panel"},
			tag = "normal",
			beginTime = 1607385600,
			endTime = 1607961599,
		},
		[21]=
		{
			id = 21,
			ID = 21,
			title = "欢乐福利",
			noCloseUI = 0,
			order = 1,
			key = "act_039_ty_by_hhl",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_ty_by_hhl","panel"},
			tag = "normal",
			beginTime = 1610380800,
			endTime = 1611590399,
		},
		[22]=
		{
			id = 22,
			ID = 22,
			title = "星星排行榜",
			noCloseUI = 0,
			order = 2,
			key = "act_039_jzsjb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_jzsjb","panel"},
			tag = "normal",
			beginTime = 1610380800,
			endTime = 1611590399,
		},
		[23]=
		{
			id = 23,
			ID = 23,
			title = "冬至福袋",
			noCloseUI = 0,
			order = 3,
			key = "act_034_ldfd",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_034_ldfd","panel"},
			tag = "hot",
			beginTime = 1607990400,
			endTime = 1608566399,
		},
		[24]=
		{
			id = 24,
			ID = 24,
			title = "小游戏福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_041_xyxfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_041_xyxfl_config"},
			tag = "hot",
			beginTime = 1609804800,
			endTime = 1610380799,
			condi_key = "actp_own_task_p_041_xyxfl",
		},
		[25]=
		{
			id = 25,
			ID = 25,
			title = "兑换奖励",
			noCloseUI = 0,
			order = 1,
			key = "act_039_ty_by_hhl",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_ty_by_hhl","panel"},
			tag = "normal",
			beginTime = 1610380800,
			endTime = 1611590399,
		},
		[26]=
		{
			id = 26,
			ID = 26,
			title = "礼盒排行榜",
			noCloseUI = 0,
			order = 2,
			key = "act_039_jzsjb",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_jzsjb","panel"},
			tag = "normal",
			beginTime = 1610409600,
			endTime = 1610985599,
		},
		[27]=
		{
			id = 27,
			ID = 27,
			title = "欢乐礼包",
			noCloseUI = 0,
			order = 3,
			key = "act_ty_lb1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_ty_lb1","panel"},
			tag = "hot",
			beginTime = 1610409600,
			endTime = 1610985599,
		},
		[28]=
		{
			id = 28,
			ID = 28,
			title = "欢乐福利",
			noCloseUI = 0,
			order = 4,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_042_hlfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_042_hlfl_config"},
			tag = "hot",
			beginTime = 1610409600,
			endTime = 1610985599,
		},
		[29]=
		{
			id = 29,
			ID = 29,
			title = "暖心好礼",
			noCloseUI = 0,
			order = 1,
			key = "act_039_ty_by_hhl",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_ty_by_hhl","panel"},
			tag = "normal",
			beginTime = 1611619200,
			endTime = 1612195199,
		},
		[30]=
		{
			id = 30,
			ID = 30,
			title = "阳光榜单",
			noCloseUI = 0,
			order = 2,
			key = "act_039_ty_sjb",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_039_ty_sjb","panel"},
			tag = "normal",
			beginTime = 1611619200,
			endTime = 1612195199,
		},
		[31]=
		{
			id = 31,
			ID = 31,
			title = "狂欢福利",
			noCloseUI = 0,
			order = 3,
			key = "GameComAct1",
			type = "activity",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity_task",
			activity_config = "activity_043_khfl_config",
			is_local_icon = 1,
			gotoUI = {"GameComAct1","activity_043_khfl_config"},
			tag = "hot",
			beginTime = 1611014400,
			endTime = 1611590399,
		},
		[32]=
		{
			id = 32,
			ID = 32,
			title = "赢一把就睡觉",
			noCloseUI = 0,
			order = 3,
			key = "act_041_yybjsj",
			type = "activity",
			isOnOff = 1,
			showType = "prefab",
			parmData = "activity_task",
			is_local_icon = 1,
			gotoUI = {"act_041_yybjsj","panel_act"},
			tag = "normal",
			beginTime = 1611619200,
			endTime = 1612195199,
		},
	},
}